### ISSUE TITLE
Feature request: Run pre/post scripts as root instead of user specified with "su"

### ISSUE THREAD

**Issue by anlutro** [logrotate/logrotate#106]
Some of our applications are really not good at managing permissions to their log files. We either have to set up Linux FACL to ensure correct permissions or set up a cronjob that runs before logrotate that fixes permissions on existing files, otherwise logrotate will fail because it can't either create the new log file, move existing log files, or delete the oldest rotated log file.

It would be nice if we could move the logic in this cronjob of ours into a logrotate prescript, and that way avoid the edge case of a new log file being created after our cronjob, but before logrotate.

**Comment by kdudka** [comment]
Why are you using the ```su``` directive then?

You can set user/group with the ```create``` directive, or run ```chown``` in ```postrotate``` if you use ```copytruncate```.

**Comment by anlutro** [comment]
Because the directory of logs to be rotated is owned by a specific user, so if I leave out `su` I get permissions warnings/errors. Am I meant to ignore these?

**Comment by kdudka** [comment]
What kind of warnings/errors?

Please give us a full example: file system layout, logrotate configuration, the actual result and the expected result.

**Comment by anlutro** [comment]
Sure thing. Here's what we have today:

```
$ cat /etc/logrotate.d/example.conf 
/var/www/example/static/var/log/*.log /var/www/example/static/var/log/*/*.log {
  su www-data www-data
  create 0660 www-data www-data
  weekly
  size 10M
  rotate 9
  compress
  missingok
}

$ sudo logrotate -f -d /etc/logrotate.d/example.conf
reading config file /etc/logrotate.d/example.conf

Handling 1 logs

rotating pattern: /var/www/example/static/var/log/*.log /var/www/example/static/var/log/*/*.log  forced from command line (9 rotations)
empty log files are rotated, old logs are removed
switching euid to 500 and egid to 500
considering log /var/www/example/static/var/log/*.log
  log /var/www/example/static/var/log/*.log does not exist -- skipping
considering log /var/www/example/static/var/log/*/*.log
  log /var/www/example/static/var/log/*/*.log does not exist -- skipping
switching euid to 0 and egid to 0
```

If I remove the `su` line in order to run a prescript as root:

```
$ sudo logrotate -f -d /etc/logrotate.d/example.conf
reading config file /etc/logrotate.d/example.conf

Handling 1 logs

rotating pattern: /var/www/example/static/var/log/*.log /var/www/example/static/var/log/*/*.log  forced from command line (9 rotations)
empty log files are rotated, old logs are removed
considering log /var/www/example/static/var/log/*.log
error: skipping "/var/www/example/static/var/log/*.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
considering log /var/www/example/static/var/log/*/*.log
```

The directory's permissions:

```
$ stat /var/www/example/static/var/log
  File: ‘/var/www/example/static/var/log’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fe00h/65024d	Inode: 697385      Links: 2
Access: (2770/drwxrws---)  Uid: (  500/www-data)   Gid: (  500/www-data)
Access: 2017-02-24 11:56:06.009085850 +0000
Modify: 2017-01-25 14:21:11.867152410 +0000
Change: 2017-02-15 10:51:10.262252234 +0000
 Birth: -
```

**Comment by kdudka** [comment]
I see.  So you are proposing to optionally make logrotate restore the original euid/egid while running scripts?

Btw. while debugging this, I discovered that using 'su root root' makes the warnings go away without securing anything.  I doubt it is intentional but it is probably too late to change it...

**Comment by anlutro** [comment]
Correct. Ironically `su root root` is probably what we might end up doing if it works, but I agree that doesn't look correct.

**Comment by kdudka** [comment]
I was about to implement such an option but discovered that logrotate already does it, unconditionally.  The code doing it was introduced (or at least significantly changed) in a commit named "Add support for building using automake/autoconf", so it was not obvious:

https://github.com/logrotate/logrotate/commit/ec235d2a#diff-c77f766704c11808480548296cdd6787L308

It might not cover all cases though.  Could you please show us an example where logrotate scripts do not run as root despite logrotate itself runs as root?

**Comment by anlutro** [comment]
```
$ cat /etc/logrotate.d/example.conf 
/var/www/example/static/var/log/*.log /var/www/example/static/var/log/*/*.log {
  su www-admin www-data
  create 0660 www-admin www-data

  weekly
  size 10M
  rotate 9
  compress
  missingok

  sharedscripts
  prerotate
    find /var/www/example/static/var/log -mindepth 1 -print0 | xargs -0 --no-run-if-empty chown www-admin:www-data;
    find /var/www/example/static/var/log -mindepth 1 -type d -print0 | xargs -0 --no-run-if-empty chmod ug+rwx;
    find /var/www/example/static/var/log -type f -print0 | xargs -0 --no-run-if-empty chmod ug+rw;
  endscript
}

$ sudo logrotate -f -d /etc/logrotate.d/example.conf
reading config file /etc/logrotate.d/example.conf

Handling 1 logs

rotating pattern: /var/www/example/static/var/log/*.log /var/www/example/static/var/log/*/*.log  forced from command line (9 rotations)
empty log files are rotated, old logs are removed
switching euid to 1000 and egid to 1000
considering log /var/www/example/static/var/log/bar.log
error: stat of /var/www/example/static/var/log/bar.log failed: Permission denied
considering log /var/www/example/static/var/log/foo.log
error: stat of /var/www/example/static/var/log/foo.log failed: Permission denied
considering log /var/www/example/static/var/log/*/*.log
error: stat of /var/www/example/static/var/log/*/*.log failed: Permission denied
switching euid to 0 and egid to 0
```

**Comment by anlutro** [comment]
Sorry, I realized now that the above example was a separate issue, I've updated it now to show an example where the prerotate fails to run due to lack of permissions (and a case where I'd like it to run as root).

**Comment by kdudka** [comment]
I fail to see any error from the prerotate script.  The only permission-related error I see in the output is ```error: error setting owner of /var/www/example/static/var/log/bar.log.1.gz to uid 501 and gid 500: Operation not permitted``` which is printed by logrotate itself, not the prerotate script.

**Comment by anlutro** [comment]
Hm, it is possible that I've been misreading the logs this entire time. I'm going to write a few more tests and come back to you.

**Comment by kdudka** [comment]
Thanks for the clarification!  Please open a new issue when you are ready.

**Comment by partizanes** [comment]
Hello!
Can you give me some comments

logrotate 3.18.1 

#test logrotate file 
/var/log/test.log {
    **su nobody nobody**
    daily
    rotate 3
    missingok
    ifempty
    compress
    delaycompress
    dateext
    create 0644 nobody nobody
    sharedscripts
    postrotate
        **/home/nobody/test.sh**
    endscript
}

**# postrotate test script /home/nobody/test.sh**

**#!/bin/sh
echo $USER >> /home/nobody/test.log**

**After i run "logrotate --force test" in log file i got "root" user.**

**postrotate script run as root and ignore su option or anything else?**

**Comment by kdudka** [comment]
`$USER` is just an environment variable.  It is not updated each time the identity is changed.  Please try to run `id` instead.

**Comment by partizanes** [comment]
> `$USER` is just an environment variable. It is not updated each time the identity is changed. Please try to run `id` instead.

Thank you for you answer. Yes you right, su work correct in logrotate. My problem is something else.

**Comment by partizanes** [comment]
Sorry i hide my last comment because have error in my last test environment. In my logrotate script force use sudo -u testuser and this influenced the test results.

so now i have Centos 6.10 ( Yes, outdated) 

# logrotate test
/var/log/test.log {
    **su nobody nobody**
    daily
    rotate 3
    missingok
    ifempty
    compress
    delaycompress
    dateext
    create 0644 nobody nobody
    sharedscripts
    postrotate
        **/home/nobody/test.sh**
    endscript
}

**# /home/nobody/test.sh**

**#!/bin/sh
id >> /home/nobody/test.log**


**i run testing  "logrotate --force test" and got in my /home/nobody/test.log
uid=0(root) gid=0(root) groups=0(root)**

**Comment by kdudka** [comment]
Thanks for checking!  So it works as expected, doesn't it?

This issue was a request to "run pre/post scripts as root instead of user specified with `su`", which later appeared to be already resolved.  One can use `su` or `runuser` within logrotate scripts as needed.

**Comment by partizanes** [comment]
Sorry, i check man and found:

` Scripts are run as the invoking user and group, irrespective of any su directive
`

It works as declared, the issue misled me.

**Comment by kdudka** [comment]
Glad to see it clarified.  The mentioned statement in the documentation was introduced in `logrotate-3.17.0` via e28e0c28268e37542264c40351a6fc1b6a114817.
