### ISSUE TITLE
Regression tests fail for logrotate-3.11.0

### ISSUE THREAD

**Issue by bdubbs** [logrotate/logrotate#107]
Four tests fail after building.  The errors look  like:

error: uncompress command failed mailing /tmp/logrotate/logrotate-3.11.0/test/test.log.1.gz
--- - 2017-02-28 11:42:17.897924701 -0600
+++ mail-out   2017-02-28 11:42:17.834676842 -0600
@@ -1,2 +1 @@
 -s /tmp/logrotate/logrotate-3.11.0/test/test.log user@myhost.org
-zero

Tests 8, 9, 10, and 64 all fail in the same way.  

The uncompress command we use is built from Gzip-1.8.

  -- Bruce Dubbs 
      linuxfromscratch.org

**Comment by kdudka** [comment]
I run the test-suite with ```gzip-1.8``` installed on my system regularly without any issues.

Could you please check the path of compress/uncompress binaries that is compiled in logroate?
```
$ strings logrotate | grep zip
```

After the failed test, do you have ```/tmp/logrotate/logrotate-3.11.0/test/test.log.1.gz``` on your file system?

Are you able to uncompress the file manually using the same command as logrotate uses?

**Comment by bdubbs** [comment]
$ strings /usr/sbin/logrotate | grep zip
gzip
bzip2

$ which gzip
/bin/gzip

The test script does leave /tmp/logrotate/logrotate-3.11.0/test/test.log.1.gz and I am able to decompress it with gzip -d.  The contents seem to be correct.

$ cat test.log.1
zero

**Comment by kdudka** [comment]
On Friday, March 03, 2017 09:29:36 bdubbs wrote:
> $ strings /usr/sbin/logrotate | grep zip
> gzip
> bzip2

You are checking logrotate executable installed on your system.  The
executable is stripped, so it does not contain the needed strings.
Please check the executable in logrotate's build directory instead.
That executable is the one that is used by the test-suite after all.

> $ which gzip
> /bin/gzip
>
> The test script does leave
> /tmp/logrotate/logrotate-3.11.0/test/test.log.1.gz and I am able to
> decompress it with gzip -d.  The contents seem to be correct.

Did you check that the decompressor returned zero exit status?

Kamil

> $ cat test.log.1
> zero

**Comment by bdubbs** [comment]
[ /tmp/logrotate/logrotate-3.11.0 ]$ strings logrotate|grep zip
gzip
bzip2

$ file logrotate
logrotate: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped, with debug_info

[ /tmp/logrotate/logrotate-3.11.0 ]$ diff logrotate /usr/sbin/logrotate 
[ /tmp/logrotate/logrotate-3.11.0 ]$

 [ /tmp/logrotate/logrotate-3.11.0/test ]$ gzip -d test.log.1.gz
[ /tmp/logrotate/logrotate-3.11.0/test ]$ echo $?
0

Everything on my system seems to check out.  Is there something I can add to my copy of the code to help debug this?

  -- Bruce

Note: The reference to the above Linux 2.6.32 is because of a configure option to glibc.  I am using glibc-2.25, linux-4.9.9, and gcc-6.3.0.

**Comment by kdudka** [comment]
Could you please patch the test to capture strace:

```
--- a/test/test
+++ b/test/test
@@ -376,7 +376,7 @@ cleanup 8

 # ------------------------------- Test 8 -------------------------------------
 preptest test.log 8 1 1
-$RLR test-config.8 --force
+strace -fo test-8.strace $RLR test-config.8 --force

 checkoutput <<EOF
 test.log 0
```

... run the test-suite again and attach the resulting file ```test-8.strace```?

**Comment by bdubbs** [comment]
Thanks for the patch.  I figured out what is happening.  We have gzip in /bin because we still support a separate /usr, but gunzip is in /usr/bin.  When I create a symlink /bin/gunzip->/usr/bin/gunzip, then all tests pass.

27569 execve("/bin/gunzip", ["/bin/gunzip"], [/* 61 vars */] <unfinished ...>

The question I have is why logrotate thinks gunzip is in /bin and does not just use PATH?

Indeed if I remove the /bin/gunzip symlink and change config.h:

//#define UNCOMPRESS_COMMAND "/bin/gunzip"
#define UNCOMPRESS_COMMAND "gunzip"

then all tests still pass.  Indeed, I'd recommend removing the path from DEFAULT_MAIL_COMMAND, COMPRESS_COMMAND, and UNCOMPRESS_COMMAND in config.h.

I'm not familiar with hpux, sunos, or netbsd, but I suspect the same goes for those OSes also.

  -- Bruce

**Comment by kdudka** [comment]
Perfect.  Thanks for clarifying it!

The upcoming release of logrotate is going to have the default compress/uncompress commands configurable at build time thanks to 58e33d126e9422ac5271d6bda724c9065564a440.

As for your question, I guess that using absolute path is more secure in certain environments, so it seems to be good default.  Given the fact that the default can be easily overridden both at build time and run time, I would prefer to keep it as it is.

**Comment by bdubbs** [comment]
OK, We've solved this issue.  Thanks for your responsiveness.

  -- Bruce
