### ISSUE TITLE
race-condition on state file when multiple logrotates are executing

### ISSUE THREAD

**Issue by dekimsey** [logrotate/logrotate#113]
In 3.8.6 on EL7 we noticed a race-condition on logrotate if it is executed by two different processes with the same state file (differing configuration files).

    error: error renaming temp state file /var/lib/logrotate.status.tmp

Perhaps logrotate might obtain a lock on its state file before attempting to perform changes.

Version: logrotate-3.8.6-7.el7_2.x86_64

**Comment by kdudka** [comment]
Sorry for replying late.  For some reason, I did not receive any notification about this issue.

I believe that the correct approach is to use separate state files for each of those processes.

**Comment by dekimsey** [comment]
How would logrotate track the rotated logs if they are in separate log files?

The reason we are executing it in this manner is on-application-start we ask logrotate to rotate the logs for specific applications.

Essentially what is being done in this (admittedly odd) case:

  * logrotate runs crond nightly targeting logrotate.conf.d (pretty standard).
  * on-app-start we have a pre-start step to force a logrotate run using their logrotate.conf.d/$service.conf file.

People seem to be big on the clean log after starts. Not my choice, but I have to support it for our custom services.

I've worked around the behavior by wrapping our logrotate exec in a flock. But it does seem something logrotate should guard against since it is designed to run arbitrary configuration and state files. A corrupted state file can break the application in non-obvious ways.

**Comment by kdudka** [comment]
As I understand it, you use logrotate to rotate separate sets of log files by separate sets of config files.  This is perfectly fine.  Just use the ```-s``` option of logrotate to make it also use a separate state file for each of the set.

**Comment by kdudka** [comment]
A user-side solution has been suggested.  No changes in logrotate's code are needed.
