### ISSUE TITLE
compresscmd should locate cmd in $PATH environment variable

### ISSUE THREAD

**Issue by bruceauyeung** [logrotate/logrotate#122]
if using `compresscmd xz`, logrotate will complain:

> compression program xz is not an executable file

but if using `compresscmd /usr/bin/xz` , it works.
seems `compresscmd` directive doesn't try to locate command in $PATH environment variable

logrotate :3.11

**Comment by kdudka** [comment]
logrotate uses ```execvp()``` to execute the command, which should search ```$PATH``` if available.  How are you confirming that ```/usr/bin``` is contained in ```$PATH``` in the environment where you run logrotate?

**Comment by bruceauyeung** [comment]
> -bash-4.2# logrotate -f /etc/logrotate.d/kubernetes
> error: /etc/logrotate.d/kubernetes:8 compression program xz is not an executable file
> error: found error in /etc/kubernetes/logs/*[0-9] , skipping
> -bash-4.2# echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

**Comment by kdudka** [comment]
Thanks for reply!  I did not realize there were ```access(..., X_OK)``` checks for ```compresscmd``` and ```uncompresscmd``` in ```config.c```.  In my opinion, those checks are unnecessary, incomplete, and only cause troubles like this.  Is anybody against just removing those checks?
