### ISSUE TITLE
logrotate uses unsafe writing file when rotating extra log files

### ISSUE THREAD

**Issue by ylse** [logrotate/logrotate#124]
When the parameter rotate is set to n(e.g. rotate 2) in configuration file, there should be n+1 files(e.g. x.log, x.log.1, x.log.2) at most. If there are already n+1 files in the directory, the process logrotate will use unsafe writing file(not using temporary file) when processing the extra file(e.g. rename x.log.2 to x.log.3; then delete x.log.3). 

A example of configuration file: 
/usr/local/syslog.log
{
	nocreate
	missingok
	**nodateext
	rotate 2**
	size=5000
	postrotate
		/bin/systemctl kill --signal HUP syslog-ng.service
	endscript
}

I followed the file processing of logrotate using strace and found some clues. 
When it needs to rotate extra file, what logrotate has done is listed as bellow:  
_rename("/usr/local/syslog.log.2", "/usr/local/syslog.log.3") = 0
access("/usr/local/syslog.log.3", F_OK) = 0
**open("/usr/local/syslog.log.3", O_RDWR|O_NOFOLLOW) = 3**
unlink("/usr/local/syslog.log.3")       = 0_
It is the third line open(...O_RDWR...) that didn't use temporary file such as syslog.log.3.tmp. 
I wonder whether it is necessary here to use open(O_RDWR) since the file is only to be deleted. Maybe access/status/open(O_RDONLY)/unlink is enough.

**Comment by ylse** [comment]
After reading the related code, I find that opening syslog.log.3 with mode O_RDWR is prepared for the possible use of dup2 in case the file be shared. If the file is not shared, it is not necessary to open with O_RDWR. Would it be better to use different branches, open/dup2/unlink for shared files while access/unlink for unshared files?

**Comment by ylse** [comment]
After reading the code of logrotate, I find that open(...O_RDWR...) is for the possible parameter "shred" in configuration file. If "shred" is demanded, open(...O_RDWR...) is useful because it will use dup2(...) next. But, if "shred" is not demanded, open(...O_RDWR...) is unnecessary and access is enough. So I wonder the answer to **two questions**:
(supposed "rotate 2" is configured in configuration file and syslog.log.2 needs to be rotated)
1 Since the syslog.log.2 is destined to be deleted soon, why does logrotate rename syslog.log.2 to syslog.log.3 first and then delete syslog.log.3? Would it be better if logrotate delete syslog.log.2 directly so as to save resources? 
2 For the file syslog.log.3 which is to be deleted, why does logrotate use open(...O_RDWR...) first and then go to different branches according to parameter "shred"? This can cause unnecessary open(...O_RDWR...) if no "shred" is demanded. Would it be better if logrotate goes into different branches with and without parameter "shred"? If "shred", it uses open(...O_RDWR...) and then dup2() and so on. If no "shred", it uses unlink directly.

**Comment by kdudka** [comment]
On Monday, May 08, 2017 06:48:12 ylse wrote:
> 1 Since the syslog.log.2 is destined to be deleted soon, why does
> logrotate rename syslog.log.2 to syslog.log.3 first and then delete
> syslog.log.3?Would it be better if logrotate delete syslog.log.2 directly
> so as to save resources?

Nope.  This would change the interface for preremove scripts.

> 2 For the file syslog.log.3 which is to be
> deleted, why does logrotate use open(...O_RDWR...) first and then go to
> different branches according to parameter "shred"? This can cause
> unnecessary open(...O_RDWR...) if no "shred" is demanded. Would it be
> better if logrotate goes into different branches with and without parameter
> "shred"? If "shred", it uses open(...O_RDWR...) and then dup2() and so on.
> If no "shred", it uses unlink directly.

Yes, it looks like the open() call can be skipped unless shred is enabled.

**Comment by kdudka** [comment]
Please have a look at a possible fix in the ```kdudka/issue-124``` branch:

https://github.com/logrotate/logrotate/compare/kdudka/issue-124

**Comment by ylse** [comment]
@kdudka , thank you for your response. I have verified that the fix works. Now it won't open syslog.log.3 if no shred is demanded. Thanks a lot.

**Comment by ylse** [comment]
It works and when will this be accepted by upstream? So that we can apply this fix for our service.

**Comment by kdudka** [comment]
Thanks for the confirmation!  I have been just waiting for your reply, will push it shortly...
