### ISSUE TITLE
add missingok for /var/log/wtmp in logrotate-default 

### ISSUE THREAD

**Issue by ylse** [logrotate/logrotate#125]
There are rotation strategies for /var/log/wtmp and /var/log/btmp in the default config file: logrotate/examples/logrotate-default

missingok is configured for /var/log/btmp while not for /var/log/wtmp

It will complain if I delete /var/log/wtmp. 
Shall we add missingok for it? Is there any special consideration not doing this?

**Comment by kdudka** [comment]
Not that I know of.  I am fine with using ```missingok``` for ```/var/log/wtmp``` in the default configuration.
