### ISSUE TITLE
Logrotate does not support RO root anymore. The state file needs to move from /var/lib/logrotate.status to /var/lib/logrotate/status and rwtab entry should be changed to "dirs /var/lib/logrotate"

### ISSUE THREAD

**Issue by zhishupp** [logrotate/logrotate#127]
https://bugzilla.redhat.com/show_bug.cgi?id=1272236

has this issue been fixed ?

I checked the latest code, the STATFILE is still as following: 
#define STATEFILE "/var/lib/logrotate.status"

**Comment by kdudka** [comment]
For RHEL-7, the default location is being fixed via https://bugzilla.redhat.com/1381719 while the cron job is already fixed since logrotate-3.8.6-12.el7.  Upstream consumers need to configure the default location of the state file themselves using the ```--with-state-file-path``` option of the configure script.

**Comment by zhishupp** [comment]
get it, thanks !
