### ISSUE TITLE
Patches to port logrotate to Cygwin

### ISSUE THREAD

**Issue by alavrentiev** [logrotate/logrotate#133]
Hi,
Attached are patches that I had to make to port logrotate to Cygwin:

```
*** logrotate-3.12.3/config.c   2017-05-22 08:10:22.000000000 -0400
--- logrotate-3.12.3-1/config.c 2017-07-19 17:36:54.000000000 -0400
*************** static int readModeUidGid(const char *co
*** 291,297 ****
--- 291,310 ----
        }

        if (rc > 1) {
+ #ifdef __CYGWIN__
+                 static struct passwd root = {
+                   .pw_name = "root",
+                   .pw_passwd = "*",
+                   .pw_uid = 0,
+                   .pw_gid = 0,
+                   .pw_gecos = "",
+                   .pw_dir = "/",
+                   .pw_shell = "/bin/sh"
+                 };
+                 pw = strcmp(u, "root") == 0 ? &root : getpwnam(u);
+ #else
                pw = getpwnam(u);
+ #endif
                if (!pw) {
                        message(MESS_ERROR, "%s:%d unknown user '%s'\n",
                                configFile, lineNum, u);
*************** static int readModeUidGid(const char *co
*** 301,307 ****
--- 314,336 ----
                endpwent();
        }
        if (rc > 2) {
+ #ifdef __CYGWIN__
+                 static struct group root = {
+                   .gr_name = "root",
+                   .gr_passwd = "*",
+                   .gr_gid = 0,
+                   .gr_mem = 0
+                 };
+               char* c = g;
+               while (*c) {
+                 if (*c == '+')
+                     *c  = ' ';
+                   ++c;
+                  }
+                 group = strcmp(g, "root") == 0 ? &root : getgrnam(g);
+ #else
                group = getgrnam(g);
+ #endif
                if (!group) {
                        message(MESS_ERROR, "%s:%d unknown group '%s'\n",
                                configFile, lineNum, g);
```

and

```
*** logrotate-3.12.3/test/test  2017-06-20 07:35:27.000000000 -0400
--- logrotate-3.12.3-1/test/test        2017-07-26 13:27:12.751228700 -0400
*************** genconfig() {
*** 81,87 ****
      input=test-config.$1.in
      output=test-config.$1
      user=$(id -u -n)
!     group=$(id -g -n)
      sed "s,&DIR&,$PWD,g" < $input | sed "s,&USER&,$user,g" | sed "s,&GROUP&,$group,g" > $output
      config_crc=$(md5sum $output)
  }
--- 81,87 ----
      input=test-config.$1.in
      output=test-config.$1
      user=$(id -u -n)
!     group=$(id -g -n|tr ' ' '+')
      sed "s,&DIR&,$PWD,g" < $input | sed "s,&USER&,$user,g" | sed "s,&GROUP&,$group,g" > $output
      config_crc=$(md5sum $output)
  }
```

That adds support of groupnames with spaces (coded as "+").

Unfortunately, `strptime()` in Cygwin is missing the `"%s"` format, and also support for sparse files is not on by default, so test 55 cannot be performed, and 62 and 63 must be excluded if the file system is not mounted with the `"sparse"` option.

Otherwise, it works great!

**Comment by kdudka** [comment]
Thank you for sharing  the patches!  It seems redundant to initialize all members of ```struct passwd``` and ```struct group``` when only ```pw_uid``` and ```gr_gid``` is used afterwards.  Let me try to simplify the first patch.

**Comment by kdudka** [comment]
@alavrentiev Could you please have a look at the ```kdudka/issue-133``` branch?

https://github.com/logrotate/logrotate/compare/kdudka/issue-133

Does it work for you on Cygwin?

**Comment by alavrentiev** [comment]
I'd strongly advise against using -1L as a return value to denote failure: some Un*ces were known to use -1 as a user "nobody" and a group "nogroup", which were the real user and group for various maintenance needs.  Now, if uid_t / gid_t are typed as signed (even if short) ints (which they usually are) , then the sign extensions of those IDs will result in false-positives for the above mentioned special user and group.  Just an observation.
Also, my patch included a treatment for spaces in group names (like "Domain+Users") which Cygwin encounters all the time while pulling user/group info from AD.

**Comment by kdudka** [comment]
Thank you for letting me know about the -1 being used as valid uid/gid on some systems.  I did not  realize it was possible because the data types are unsigned on my system.  I will prepare a better patch then...

Please open a separate pull request for the test-suite fix.  I will apply it on top of #132.

**Comment by alavrentiev** [comment]
>  [logrotate/logrotate] Logrotate Errors on Username/Groups with Spaces (#105)
> Which patch? The only patch I know of changes just the test-suite. It does not change the behavior of logrotate itself.

I was talking about this part of the patch to config.c:
```
+               char* c = g;
+               while (*c) {
+                 if (*c == '+')
+                     *c  = ' ';
+                   ++c;
+                  }
```

**Comment by kdudka** [comment]
Sorry but I still cannot see the patch you are talking about...  Where can I get the whole patch?

**Comment by alavrentiev** [comment]
Hmm, it's all right up there in this very issue 133, in my initial post, in the addition to the "root" group resolution for Cygwin.

**Comment by kdudka** [comment]
Either I am blind, or there is no such patch in this issue.  Please repost it as a separate PR.

**Comment by alavrentiev** [comment]
```
```







```
*** 301,307 ****
--- 314,336 ----
                endpwent();
        }
        if (rc > 2) {
+ #ifdef __CYGWIN__
+                 static struct group root = {
+                   .gr_name = "root",
+                   .gr_passwd = "*",
+                   .gr_gid = 0,
+                   .gr_mem = 0
+                 };
+               char* c = g;
+               while (*c) {
+                 if (*c == '+')
+                     *c  = ' ';
+                   ++c;
+                  }
+                 group = strcmp(g, "root") == 0 ? &root : getgrnam(g);
+ #else
                group = getgrnam(g);
+ #endif

**Comment by kdudka** [comment]
It is indeed there.  Sorry for not spotting it previously...

Anyway, I do not think it should be considered as fix for #105 because it works only for group names and only on cygwin.  Moreover, it prevents logrotate from handling groups containing ```+``` in their names.

#105 needs to be fixed properly, on all architectures, in a backward compatible way, and with the possibility to escape any characters that can appear in user/group names.

**Comment by alavrentiev** [comment]
It all was suggested as a porting patch for Cygwin; but it may be retrofitted to those needing spaces in the group names.  I've never seen usernames with spaces, nor group/user names with the plus signs.  Anyways, the plus sign was chosen to mimic the standard URL-encoding, so that it can potentially be extended to recognize the percent (%) notation (namely, %2B for the plus sign), but I doubt that ever be needed, in practice.

**Comment by kdudka** [comment]
@alavrentiev Could you please have a look at the updated kdudka/issue-133 branch?

https://github.com/logrotate/logrotate/compare/kdudka/issue-133

Are you fine with merging it such?

**Comment by alavrentiev** [comment]
Yes, looks good.

**Comment by kdudka** [comment]
Thanks for review!  Merging now...
