### ISSUE TITLE
Log rotation not working when logrotate.status file is corrupted

### ISSUE THREAD

**Issue by JamesArthurHolland** [logrotate/logrotate#135]
When the logrotate.status file is corrupted, the log rotation doesn't work, resulting in a huge log file, which uses up all disk space if left unattended.

We are unsure as to how this file came to be corrupted. 

This bug has been reported by others : 
https://bugzilla.redhat.com/show_bug.cgi?id=447022

We are using logrotate 3.8.7, has this issue solved in newer versions of logrotate?

**Comment by kdudka** [comment]
Yes, this has been fixed in b9d82003002c98370e4131a7e43c76afcd23306a.  See issue #45 for details.
