### ISSUE TITLE
logrotate.status should not reside in /var/lib

### ISSUE THREAD

**Issue by nimiux** [logrotate/logrotate#136]
This is an old issue. The ticket got lost after fedorahosted.org shutdown:

https://fedorahosted.org/logrotate/ticket/29

More info at:
https://bugzilla.redhat.com/show_bug.cgi?id=681649
https://bugs.gentoo.org/show_bug.cgi?id=357275

**Comment by kdudka** [comment]
Upstream consumers need to configure the default location of the state file themselves using the ```--with-state-file-path``` option of the configure script.  See issue #127 and pull request #85.

**Comment by wltjr** [comment]
Nice, I do not think that was a configure option long ago when first reporting. Thanks for mentioning!

**Comment by kdudka** [comment]
It was certainly not.  See the release notes of ```logrotate-3.11.0```:

https://github.com/logrotate/logrotate/releases/tag/3.11.0

Sorry for loosing track of the original bug report!  I overtook the maintenance of logrotate just recently...

**Comment by wltjr** [comment]
This was first reported in 2011. Your pointing to a release in 2016.

Reported: | 2011-03-03 21:32 UTC by  William L. Thomson Jr.
https://bugs.gentoo.org/show_bug.cgi?id=357275

**Comment by wltjr** [comment]
Sorry I thought you were saying it was :) damn coffee kick in!!!! :)

**Comment by kdudka** [comment]
No problem.  Glad to see it fixed in Gentoo Linux now!
