### ISSUE TITLE
Systemd hardening options

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#141]
Currently I am testing logrotate with the following additional systemd service options:

```
ProtectSystem=full
ProtectHome=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectControlGroups=true
ProtectKernelModules=true
PrivateNetwork=true
```

Could some of these get included?

**Comment by kdudka** [comment]
Any systemd expert around to review this?  Could it break any commonly used lgoratate configurations?

Please open a pull request for this.  From your description it is not clear where exactly these lines should go...

**Comment by glensc** [comment]
#143 got merged, so this can be closed i believe
