### ISSUE TITLE
logrotate emails compressed logs

### ISSUE THREAD

**Issue by gpakosz** [logrotate/logrotate#151]
Hello, I'm running Debian Stretch:
```
# logrotate
logrotate 3.11.0 - Copyright (C) 1995-2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License
```

I'm facing a situation where `logrotate` emails compressed logs.
Here are the reproduction steps:

1. Open a terminal and write the date/time to a log file every 2 seconds
    ```
    # mkdir -p /tmp/log
    # while :; do date >> /tmp/log/test.log; sleep 2; done
    ```

2. Create a test `logrotate` configuration:
    ```
    # cat /tmp/test.conf
    /tmp/log/*.log {
      mail www
      daily
      rotate 2
      missingok
      compress
      delaycompress
      notifempty
      sharedscripts
    }
    ```

3. Create a mailer shim:
    ```
    # cat /tmp/mail.sh
    #!/bin/sh

    shift # get rid of -s always being passed by logrotate
    printf "Subject: %s\n" "$1" > /tmp/mail.txt
    printf "Recipient: %s\n" "$2" >> /tmp/mail.txt
    printf "%s\n" "----------" >> /tmp/mail.txt
    cat >> /tmp/mail.txt
    ```

4. Now force `logrotate` to rotate log files
    ```
    # rm /tmp/logrotate.status && logrotate -m /tmp/mail.sh -vf -s /tmp/logrotate.status /tmp/test.conf
    ```

Here is the content of `/tmp/mail.txt` after logrotate has rotated the logs:
```
# cat mail.txt
Subject: /tmp/log/test.log.3.gz
Recipient: www
----------
Aӱ
 ќ*\>
n[@"$6EHOϷYFpUPU*T4vծTT9U@U*PJT%UA
>(|P||/;uV
```

As you can see, the body corresponds to gziped content.

Now, change the mailer shim a little bit to pipe to gunzip (pay attention to **`cat | gunzip >> /tmp/mail.txt`**):
```
#!/bin/sh

shift
printf "Subject: %s\n" "$1" > /tmp/mail.txt
printf "Recipient: %s\n" "$2" >> /tmp/mail.txt
printf "%s\n" "----------" >> /tmp/mail.txt
cat | gunzip >> /tmp/mail.txt
```

Rotate the logs again. Now the content of `/tmp/mail.txt` is correct:
```
Subject: /tmp/log/test.log.3.gz
Recipient: www
----------
Thu Sep 21 10:33:06 CEST 2017
Thu Sep 21 10:33:08 CEST 2017
Thu Sep 21 10:33:10 CEST 2017
Thu Sep 21 10:33:12 CEST 2017
Thu Sep 21 10:33:14 CEST 2017
Thu Sep 21 10:33:16 CEST 2017
...
```

Best.

**Comment by kdudka** [comment]
Logs should be uncompressed before they are mailed but there seems to be some exception for the ```delaycompress``` directive:

https://github.com/logrotate/logrotate/blob/8523cb35/logrotate.c#L877

I do not understand the logic and the comment above it does not help either.  I guess the intention was to avoid running the uncompress command on logs that have not yet been compressed.  But it apparently does not work as intended.

The funny thing is that the code in question has not been changed much since 2005: 62b4a6fe1ac52ca88a52b75fb6578b689a2bb54e

**Comment by gpakosz** [comment]
> The funny thing is that the code in question has not been changed much since 2005: 62b4a6f

Yeah I bit the Wheezy → Jessie → Stretch bullet on an old box and I'm un covering many many things 😀

BTW forgot to mention another poor soul faced it and reported it to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854216 without much follow up.

**Comment by kdudka** [comment]
Interesting.  The Debian reporter says it started to misbehave after an update from logrotate-3.8.7.  It must be caused by some change elsewhere then...

**Comment by kdudka** [comment]
OK.  I overlooked a minor difference between the original code in 2005 and the current version.  This bug was introduced in ```logrotate-3.9.2``` by commit dd139ef33b163b7f5252c9db3ed4a39586008719, which also includes unnecessary white-space changes to make the bug introduction less obvious.

The original condition was meant to cover the case where both ```delaycompress``` and ```mailfirst``` are set because the first log is always uncompressed (unlike the last one).  The mentioned commit broke this logic without explaining why.  So I will just revert the problematic part of that commit...

**Comment by gpakosz** [comment]
Thanks for the follow up.

On my side I think I will just use a mailer shim and pipe to `gunzip` as I'm unfamiliar with the pace at which bugs are eventually fixed in Debian stable.

**Comment by glensc** [comment]
the mentioned commit diff with whitespace ignored view:
https://github.com/logrotate/logrotate/commit/dd139ef33b163b7f5252c9db3ed4a39586008719?w=1

**Comment by gpakosz** [comment]
BTW, what should be the subject of the mail?

Should it say?
  - ... `foo.log`
  or
  - ... `foo.log.X.gz` where X corresponds to the value of `rotate` + 1 (e.g. `8` when using `rotate 7`)

**Comment by kdudka** [comment]
It also depends whether you are using ```mailfirst``` or ```maillast``` (the default).  While fixing this issue I avoided to change anything that was covered by already existing regression tests (including the subject).  If you think it really needs to be changed, please open a separate PR with some justification.  I do not use the mailing facility of logrotate myself...

**Comment by gpakosz** [comment]
Well I observed the behavior changed.

Previously I received emails titled "... `foo.log`" and now it's "... `foo.log.366.gz`" (with `rotate 365` and no`mailfirst` directive so I assume it's `maillast`).

With your fix, I expect I will receive emails titled "... `foo.log.366.gz`" with non gziped body.
I will happily open another issue or PR if we conclude something needs to be changed. Commit  https://github.com/logrotate/logrotate/commit/dd139ef33b163b7f5252c9db3ed4a39586008719?w=1 changed tests but I want to confirm the expected behavior with you.

**Comment by kdudka** [comment]
I am confused.  Are you saying that it was my commit 1a0bd966e1267dab8e95f564de014d33eb958f3d what changed the behavior (namely the subject being sent)?

If not, please open a separate PR.

**Comment by gpakosz** [comment]
No it's not your commit. It's commit dd139ef that changed the mail subject.

I can open another issue but technically until we have discussed it's not an issue **yet** imho :)

**Comment by kdudka** [comment]
I do not know the exact reasoning behind that commit.  Its summary says _"Fix bad filename in subject of email when compress and maillast is used"_.  So one would expect it not to change the subject when ```maillast``` is **not** used.  This could be yet another unwanted side effect of this poorly coded and poorly documented code change.

Anyway, please open a separate issue to discuss it.  We can easily close the issue in case we agreed that the current behavior is correct.
