### ISSUE TITLE
Logrotate expects valid stdin

### ISSUE THREAD

**Issue by sumitkamath** [logrotate/logrotate#154]
I found an issue where if I called logrotate from runit or fcron it fails with:

gzip: standard input: Bad file descriptor

The issue is here:  logrotate.c
`
  dup2(inFile,0);  
  close(inFile);  
  dup2(outFile,1);  
  close(outFile);  
  ...  
  execvp(...); // gzip . 
`

If logrotate does not have a valid fd0, when inFile is opened the kernel/libc allocates fd 0. The forked process dupes the FD to 0, which is the same FD and immediately closes inFile. This leads to the problem where gzip fails because stdin (0) has now closed. We fixed it by adding:
` if (inFile != STDIN_FILENO)  `
before closing inFile.

**Comment by kdudka** [comment]
Thank you for reporting the bug!  There is exactly the same problem with stdout and also with the uncompress/mail pipe.  I am just pushing a fix for this...
