### ISSUE TITLE
logrotate  --version returns UNKNOWN

### ISSUE THREAD

**Issue by bd-01** [logrotate/logrotate#156]
Hi,

I compiled logrotate 3.12.3 for an embedded environment under yocto and I used the tarball.
Logrotate works fine but the –version option returns « UNKNOWN ».

I understood that in configure.ac , the version is initialized with the git tag :
```
AC_INIT([logrotate],m4_esyscmd([build-aux/git-version-gen --prefix '' .tarball-version]),
```

But when we use the tarball to build logrotate, the .version and .tarball-version files are missing.

In  build-aux/git-version-gen, you will find the following comment:
```
 Use the following line in your configure.ac, so that $(VERSION) will
 automatically be up-to-date each time configure is run (and note that
 since configure.ac no longer includes a version string, Makefile rules
 should not depend on configure.ac for version updates).

 AC_INIT([GNU project],
         m4_esyscmd([build-aux/git-version-gen .tarball-version]),
         [bug-project@example])

 Then use the following lines in your Makefile.am, so that .version
 will be present for dependencies, and so that .version and
 .tarball-version will exist in distribution tarballs.

 EXTRA_DIST = $(top_srcdir)/.version
 BUILT_SOURCES = $(top_srcdir)/.version
 $(top_srcdir)/.version:
	echo $(VERSION) > $@-t && mv $@-t $@
 dist-hook:
	echo $(VERSION) > $(distdir)/.tarball-version
```
But it seems there is no modification in Makefile.am to generate the .version and .tarball-version files...

Regards,

**Comment by kdudka** [comment]
Thank you for reporting the issue!  It should be at least partially fixed by d85c496fbd0ecdcf5d7a36d7876673c69bfdda8c.  Could you please retest it with [logrotate-3.13.0](https://github.com/logrotate/logrotate/releases/tag/3.13.0)?

Anyway, I am not against fixing it properly :-)  Will you open a pull request for this?  Or should I prepare one on your behalf?

**Comment by bd-01** [comment]
Hi,

Yes, it's working with 3.13.0 release!
I'm newbie on GitHub, it was my first post... I prefer you manage the pull request.
Thank you for your help.

Regards.

**Comment by kdudka** [comment]
I have just pushed the fix.  Sorry for the delay!
