### ISSUE TITLE
logrotate not * moving * files to olddir

### ISSUE THREAD

**Issue by sowri-varanasi** [logrotate/logrotate#157]
Configuration is as follows: 
```
 /var/log/tomcat7/* {
        size 10M
        rotate 5
        missingok
        compress
        notifempty
        copy
        dateext
        dateformat %s
        olddir /var/log/tomcat7/rotated
        }
```
During rotation its observed that the original files are left in tact and they are * copied * to olddir specified rather than * moving *. 

As per the manual - 

olddir directory
Logs are moved into directory for rotation. The directory must be on the same physical device as the log file being rotated, and is assumed to be relative to the directory holding the log file unless an absolute path name is specified. When this option is used all old versions of the log end up in directory. This option may be overridden by the noolddir option.

Old logs are supposed to be moved. Can you explain.

**Comment by kdudka** [comment]
Why are you using the ```copy``` directive then?

**Comment by sowri-varanasi** [comment]
Thanks for the quick response @kdudka. 

Our logs have to work with both logrotate as well as with AWS Kinesis agent. AWS Kinesis agent will run into issues if we use COPYTRUNCATE/CREATE and we are left with only COPY.

**Comment by kdudka** [comment]
I am afraid that the ```copy```directive documented differently:

> Make a copy of the log file, but don't change the original at all.
> This option can be used, for instance, to make a snapshot of the current
> log file, or when some other utility needs to truncate or parse the file.
> When this option is used, the create option will have no effect,
> as the old log file stays in place.

**Comment by kdudka** [comment]
logrotate just seems to work as documented.  Feel free to reopen if it is not the case.
