### ISSUE TITLE
logrotate doesn't handle ",v" properly in "tabooext"

### ISSUE THREAD

**Issue by yermulnik** [logrotate/logrotate#160]
```
10:19:44 [yz@nb][w:1][j:0][~]> fgrep tabooext /usr/local/etc/logrotate.conf
tabooext + .sample ,v
10:19:49 [yz@nb][w:1][j:0][~]> /usr/local/sbin/logrotate -d 2>&1 | head -1
logrotate 3.13.0 - Copyright (C) 1995-2001 Red Hat, Inc.
10:19:53 [yz@nb][w:1][j:0][~]> /usr/local/sbin/logrotate -d /usr/local/etc/logrotate.conf | head -10

reading config file /usr/local/etc/logrotate.conf
including /usr/local/etc/logrotate.d
Ignoring RCS, because of * pattern match
Ignoring cups, because of * pattern match
Ignoring yz, because of * pattern match
Ignoring rsync, because of * pattern match
Ignoring apache, because of * pattern match
Ignoring clamav, because of * pattern match
Ignoring ntpd, because of * pattern match
Ignoring mpd, because of * pattern match
Reading state from file: /var/lib/logrotate.status
Allocating hash table for state file, size 64 entries

Handling 0 logs
```
```
10:24:25 [root#mh][j:1][.../sysutils/logrotate]> fgrep tabooext /usr/local/etc/logrotate.conf
tabooext + .sample ,v
10:24:32 [root#mh][j:1][.../sysutils/logrotate]> /usr/local/sbin/logrotate -d 2>&1 | head -1
logrotate 3.9.2 - Copyright (C) 1995-2001 Red Hat, Inc.
10:24:48 [root#mh][j:1][.../sysutils/logrotate]> /usr/local/sbin/logrotate -d /usr/local/etc/logrotate.conf | head -10
reading config file /usr/local/etc/logrotate.conf
including /usr/local/etc/logrotate.d
Ignoring RCS, because of  ending
Ignoring sphinxsearch, because of  ending
Ignoring apache, because of  ending
Ignoring backup, because of  ending
Ignoring clamav, because of  ending
Ignoring ftpd, because of  ending
Ignoring mysql, because of  ending
Ignoring nginx, because of  ending
Ignoring php, because of  ending
Ignoring syslog.sample, because of .sample ending
Ignoring syslog, because of  ending
Ignoring ttrss, because of  ending
Allocating hash table for state file, size 64 entries

Handling 0 logs
```

**Comment by kdudka** [comment]
To be honest, I have no idea why we have ```,v``` on the default ```tabooext list```.  It is there since the very first introduction of ```tabooext``` in ed48e68ad9879f8772eb4fe1fdbd50917bcc4852.

However, I fail to see what exactly went wrong in your example.  What is the file name that was matched incorrectly?

Have you tried the ```taboopat``` directive, which is more flexible?

**Comment by yermulnik** [comment]
In the example above `,v` was added by me. And the issue is that having `,v` on `tabooext` in `logrotate.conf` makes logrotate ignore files which should not be ignored (as seen from the examples above all of files in `logrotate.d` dir were ignored). I assume it's going to happen with any file extension matching `,*` as the value for `tabooext`. I haven't tried `taboopat`. I just noticed that my logfiles were not rotated anymore since update of logrotate about a month and a half ago.
Can you try adding `,v` to `tabooext` and running `logrotate -d logrotate.conf` to verify it on your side?

**Comment by kdudka** [comment]
I tried to add ```tabooext + .sample ,v``` to my ```/etc/logrotate.conf``` but it did not change anything.  The only related line in logrotate's debug output was:
```
Ignoring yum.rpmsave, because of *.rpmsave pattern match
```
... which has always been there.  It must be something else in your configuration what causes it.

Why are you adding ```,v``` to ```tabooext``` despite it is there by default?

**Comment by yermulnik** [comment]
It had been there for historical reasons for a pretty long time (e.g. `,v` is not listed as predefined ext for v3.8.7). It worked before and I never expected logrotate to fail because of it.
Can't get why this issue is not raising for you though %-\ Do you use v3.13.0?

**Comment by yermulnik** [comment]
It ignores legitimate files for me with v3.8.7 as well:
```
15:58:03 [root#local][w:2][j:1][~]> fgrep tabooext /etc/logrotate.conf
tabooext + .sample ,v
15:58:09 [root#local][w:2][j:1][~]> logrotate -d 2>&1 | head -1
logrotate 3.8.7 - Copyright (C) 1995-2001 Red Hat, Inc.
15:58:15 [root#local][w:2][j:1][~]> logrotate -d /etc/logrotate.conf 2>&1 | head -24
reading config file /etc/logrotate.conf
including /etc/logrotate.d
Ignoring python-pip, because of  ending
Ignoring nginx, because of  ending
Ignoring unattended-upgrades, because of  ending
Ignoring clamav-daemon, because of  ending
Ignoring rsync, because of  ending
Ignoring consolekit, because of  ending
Ignoring dpkg, because of  ending
Ignoring clamav-freshclam, because of  ending
Ignoring speech-dispatcher, because of  ending
Ignoring stunnel4, because of  ending
Ignoring apt, because of  ending
Ignoring upstart, because of  ending
Ignoring cups-daemon, because of  ending
Ignoring rsyslog, because of  ending
Ignoring samba, because of  ending
Ignoring aptitude, because of  ending
Ignoring ppp, because of  ending
Ignoring ufw, because of  ending
Ignoring pm-utils, because of  ending
Ignoring pure-ftpd-common, because of  ending

Handling 2 logs
```

**Comment by kdudka** [comment]
Yes, I tried it with 3.13.0.

From the pasted output it looks like that an empty string ended up on your ```tabooext``` list.  The would explain the outcome because an empty string can be matched at the end of any file name.  Please check your config file with a hexeditor to make sure that there are no invisible characters contained in your ```tabooext``` line.

**Comment by yermulnik** [comment]
> it looks like that an empty string ended up on your tabooext list.

No, it's not. It's exactly `tabooext + .sample ,v`.
E.g.:
```
16:11:28 [root#nb][w:2][j:1][.../sysutils/logrotate]> egrep "tabooext .+ext" /usr/local/etc/logrotate.conf
tabooext + .sample ,v .ext
16:11:57 [root#nb][w:2][j:1][.../sysutils/logrotate]> /usr/local/sbin/logrotate -d /usr/local/etc/lo
grotate.conf
reading config file /usr/local/etc/logrotate.conf
including /usr/local/etc/logrotate.d
Ignoring RCS, because of * pattern match
Ignoring cups, because of * pattern match
Ignoring yz, because of * pattern match
Ignoring rsync, because of * pattern match
Ignoring apache, because of * pattern match
Ignoring clamav, because of * pattern match
Ignoring ntpd, because of * pattern match
Ignoring mpd, because of * pattern match
[...]
```
Notice modified `tabooext` string.
In 3.13.0 it says `because of * pattern match`, in previous versions `because of  ending`.

**Comment by kdudka** [comment]
The change in the output is caused by 7ab464134721024504acbac22b557b4a2667c524 which introduced the ```taboopat``` directive.  Nevertheless, you get the same outcome with/without that commit, so it could hardly be the cause of your troubles.

As you are the only one who observes the bogus behavior, it is up to you to debug it further.  Try to remove the line that you think causes the problem, try to remove ```+``` from that line, try to remove ```.sample```, etc.  Either you will end up with a minimal example that works for other people, too, or you will have to debug it even deeper, e.g. by using a debugger.

**Comment by yermulnik** [comment]
Don't have a time for that and as I'm the only one suffering from this issue I've closed this issue.

**Comment by glensc** [comment]
you may wish to provide your configs in some binary form, so some characters don't get lost with text based communication. for example `^M` could be source of evil, or `U+00A0`.

choices for 
- use base64, uuencode
- or tar.gz and file attachment to comment form in gitlab.

**Comment by yermulnik** [comment]
@glensc So you tried `tabooext + ,v` in your `logrotate.conf` too and there were no `Ignoring ...` lines when you ran `logrotate -d /etc/logrotate.conf`?

I'd appreciate if you can verify string for illegal chars which I'm sure not present:
```
00:00:17 [root#local][w:2][j:1][~]> egrep ^taboo /etc/logrotate.conf | base64
dGFib29leHQgKyAsdgo=
00:00:52 [root#local][w:2][j:1][~]> egrep ^taboo /etc/logrotate.conf
tabooext + ,v
00:01:33 [root#local][w:2][j:1][~]> logrotate -d /etc/logrotate.conf 2>&1 | head -10
reading config file /etc/logrotate.conf
including /etc/logrotate.d
Ignoring python-pip, because of  ending
Ignoring nginx, because of  ending
Ignoring unattended-upgrades, because of  ending
Ignoring clamav-daemon, because of  ending
Ignoring rsync, because of  ending
Ignoring consolekit, because of  ending
Ignoring dpkg, because of  ending
Ignoring clamav-freshclam, because of  ending
```

**Comment by yermulnik** [comment]
Asked my colleague and he has exactly the same issue.

**Comment by sergiyksv** [comment]
Have got the same with:
`tabooext + ,v`
Out:
```
$ sudo logrotate -d /etc/logrotate.conf
reading config file /etc/logrotate.conf
including /etc/logrotate.d
Ignoring libvirtd.lxc, because of  ending
Ignoring unattended-upgrades, because of  ending
Ignoring ufw, because of  ending
Ignoring consolekit, because of  ending
Ignoring libvirtd, because of  ending
Ignoring cups-daemon, because of  ending
Ignoring dirmngr, because of  ending
Ignoring conntrackd, because of  ending
Ignoring ppp, because of  ending
Ignoring libvirtd.qemu, because of  ending
Ignoring samba, because of  ending
Ignoring stunnel4, because of  ending
Ignoring rsyslog, because of  ending
Ignoring openvswitch-switch, because of  ending
Ignoring nginx, because of  ending
Ignoring aptitude, because of  ending
Ignoring dpkg, because of  ending
Ignoring pm-utils, because of  ending
Ignoring upstart, because of  ending
Ignoring apt, because of  ending
Ignoring libvirtd.uml, because of  ending
Ignoring speech-dispatcher, because of  ending
...
```

`tabooext + .sample,v`
includes run as expected
```
reading config file /etc/logrotate.conf
including /etc/logrotate.d
reading config file apt
reading config file aptitude
reading config file conntrackd
reading config file consolekit
reading config file cups-daemon
reading config file dirmngr
reading config file dpkg
reading config file libvirtd
reading config file libvirtd.lxc
reading config file libvirtd.qemu
reading config file libvirtd.uml
reading config file nginx
reading config file openvswitch-switch
reading config file pm-utils
reading config file ppp
reading config file rsyslog
reading config file samba
reading config file speech-dispatcher
reading config file stunnel4
reading config file ufw
reading config file unattended-upgrades
reading config file upstart
...
```

Description:    Linux Mint 17.3 Rosa
logrotate 3.8.7

**Comment by kdudka** [comment]
Please provide self-contained instructions to reproduce the bug locally.

**Comment by kdudka** [comment]
OK, I got a reproducer.  ```tabooext``` needs to be before ```include``` to actually take an effect.  ```,``` is used as a delimiter, so ```",v"``` is parsed as ```""``` and ```"v"```, resulting in an empty string in the ```tabooext``` list.  Just do not add empty strings to ```tabooext``` and everything will work as expected.  Anyway, I will fix ```tabooext``` to ignore empty strings in the next release of logrotate.

**Comment by yermulnik** [comment]
Thank you! @kdudka
