### ISSUE TITLE
error: failed to compress log

### ISSUE THREAD

**Issue by yermulnik** [logrotate/logrotate#161]
Looks like after upgrade to logrotate 3.13.0 it's stared to generate errors `error: failed to compress log <logfilename>`. How do I find out what has become wrong with my configuration?
```
00:20:48 [root#mh][j:0][.../local/etc]> egrep -v "^(#|$)" logrotate.conf
weekly
rotate 5
create
compress
missingok
copytruncate
tabooext + .sample
include /usr/local/etc/logrotate.d
00:22:18 [root#mh][j:0][.../local/etc]> cat logrotate.d/apache
/var/log/apache/access.log /var/log/apache/*.access.log
{
        daily
        rotate 15
        compress
        delaycompress
        sharedscripts
        postrotate
                /usr/local/sbin/apachectl graceful >/dev/null 2>&1
        endscript
}

/var/log/apache/error.log {
        daily
}
```
Error:
```
Subject: Cron <root@mh> /usr/local/sbin/logrotate /usr/local/etc/logrotate.conf

error: failed to compress log /var/log/apache/access.log.1
error: destination /var/log/apache/error.log.1 already exists, renaming to
/var/log/apache/error.log.1-2017121200.backup
error: failed to compress log /var/log/apache/error.log.1
```

**Comment by yermulnik** [comment]
Looks like related: https://github.com/Froxlor/Froxlor/issues/482

**Comment by yermulnik** [comment]
Well, https://github.com/Froxlor/Froxlor/issues/482 is FreeBSD-specific (don't know if indeed related to issue I've hit though):
```
00:44:24 [yz@nb][w:1][j:0][~]> uname -srm
FreeBSD 10.4-STABLE i386
00:44:26 [yz@nb][w:1][j:0][~]> pkg info -i -g -x logrotate
logrotate-3.13.0
00:44:28 [yz@nb][w:1][j:0][~]> strings `which logrotate` | egrep ^/bin/
/bin/gzip
/bin/gunzip
/bin/mail
/bin/sh
00:44:30 [yz@nb][w:1][j:0][~]> for i in gzip gunzip mail; do which $i; done
/usr/bin/gzip
/usr/bin/gunzip
/usr/bin/mail
```

**Comment by yermulnik** [comment]
Definitely not related: `compresscmd` and `uncompresscmd` to actual paths didn't help with original issue =(

**Comment by yermulnik** [comment]
It helps. But I had to add `nodelaycompress` to **ALL** log definitions in **ALL** included files to make `logrotate` work as expected %-\

**Comment by click0** [comment]
After creating the symlink to the desired compressor, logrotate has earned as it should.
`ln -s /usr/bin/gzip /bin/gzip`

**Comment by glensc** [comment]
looks like your distribution build error.

the defaults are set here:

https://github.com/logrotate/logrotate/blob/3.13.0/configure.ac#L58-L82

which can be overriden with:
- https://github.com/logrotate/logrotate/blob/3.13.0/configure.ac#L117-L118
- https://github.com/logrotate/logrotate/blob/3.13.0/configure.ac#L133-L134

**Comment by yermulnik** [comment]
@glensc Why closing this issue if it still has something to do with `delaycompress`/`nodelaycompress` inheritance? %-\

**Comment by click0** [comment]
While I see it is necessary to impose such a patch:

```
#diff configure.ac configure.ac.orig
73c73
<   *-netbsd*|*-freebsd*)
---
>   *-netbsd*)

```

**Comment by click0** [comment]
After applying this patch, everything became good
```
#cat /usr/ports/sysutils/logrotate/files/patch-configure.ac
--- configure.ac.orig   2017-12-19 23:08:12.842309000 +0200
+++ configure.ac        2017-12-19 23:08:35.313816000 +0200
@@ -70,7 +70,7 @@
   *-solaris*|*-sunos*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mailx"
           ;;
-  *-netbsd*)
+  *-netbsd*|*-freebsd*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mail"
           COMPRESS_COMMAND="/usr/bin/gzip"
           UNCOMPRESS_COMMAND="/usr/bin/gunzip"

```

```
# strings /usr/ports/sysutils/logrotate/work/stage/usr/local/sbin/logrotate | egrep /bin/
/usr/bin/gzip
/usr/bin/gunzip
Command to send mail (instead of `/usr/bin/mail')
/usr/bin/mail
/bin/sh
```

**Comment by yermulnik** [comment]
Vladislav, would you please submit this patch to ports collection while (and if) it's not incorporated upstream?

**Comment by click0** [comment]
There already is a similar [PR with two patches.](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223227)

**Comment by yermulnik** [comment]
@glensc pls take a look at https://github.com/logrotate/logrotate/issues/161#issuecomment-352882228

**Comment by glensc** [comment]
this is downstream building your package wrong.

- `--with-state-file-path` was added in **3.11.0** (2016-12-02), #85
- `--with-default-mail-command`, `--with-compress-command=COMMAND`, `--with-uncompress-command=COMMAND` were added in **3.12.0** (2017-04-21), #102 

and i see they are on right track now:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223227#c6

**Comment by kdudka** [comment]
@click0  is proposing to use the same default paths to executables for ```*-freebsd*``` as what we already have for ```*-netbsd*```.  So I guess we could easily fix it like this:
```
--- a/configure.ac
+++ b/configure.ac
@@ -70,7 +70,7 @@ case "$host" in
   *-solaris*|*-sunos*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mailx"
           ;;
-  *-netbsd*)
+  *-freebsd*|*-netbsd*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mail"
           COMPRESS_COMMAND="/usr/bin/gzip"
           UNCOMPRESS_COMMAND="/usr/bin/gunzip"
```
... or even like this:
```
--- a/configure.ac
+++ b/configure.ac
@@ -70,7 +70,7 @@ case "$host" in
   *-solaris*|*-sunos*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mailx"
           ;;
-  *-netbsd*)
+  *-*bsd*)
           DEFAULT_MAIL_COMMAND="/usr/bin/mail"
           COMPRESS_COMMAND="/usr/bin/gzip"
           UNCOMPRESS_COMMAND="/usr/bin/gunzip"
```

**Comment by click0** [comment]
I am against such a union of sections.
For FreeBSD, you asked to change the STATE_FILE_PATH variable to 
`STATE_FILE_PATH = "/var/run/logrotate.status". `
I do not know how NetBSD has the presence of this directory ...

**Comment by click0** [comment]
Still there is a question, why it is necessary to duplicate value 
`compresscmd /usr/bin/bzip2 `
in snippets from /usr/local/etc/logrotate.d, so that the logs are compressed by the required compressor.

```
# /usr/local/sbin/logrotate -fv /usr/local/etc/logrotate.conf
reading config file /usr/local/etc/logrotate.conf
including /usr/local/etc/logrotate.d
reading config file nginx.conf
compress_prog is now /usr/bin/bzip2
compress_ext was changed to .bz2
uncompress_prog is now /usr/bin/bunzip2
compress_options is now  -9
compress_ext is now .bz2
Reading state from file: /var/run/logrotate.status
Allocating hash table for state file, size 64 entries
...
dateext suffix '-20171220'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
compressing log with: /usr/bin/gzip
...
```

**Comment by yermulnik** [comment]
So this issue is not about `delaycompress`/`nodelaycompress` only. Other options are affected as well (at least `compresscmd` as shown in the previous comment). So I kindly ask to re-open this issue.

**Comment by kdudka** [comment]
On Wednesday, December 20, 2017 1:58:16 AM CET Vladislav V. Prodan wrote:
> I am against such a union of sections.

And I am against duplicating the sections.

> For FreeBSD, you asked to change the STATE_FILE_PATH variable to
> `STATE_FILE_PATH = "/var/run/logrotate.status". `

Nope.  Only paths to executables will change on FreeBSD in order to resolve 
this issue.  The intention was to make upstream logrotate work on FreeBSD.
It is orthogonal to the packaging-level fix that @glensc was talking about.

> I do not know how NetBSD has the presence of this directory ...

That is exactly why I do not change anything for NetBSD by the proposed patch.
