### ISSUE TITLE
empty log files after logrotate and postrotate 

### ISSUE THREAD

**Issue by nareshku** [logrotate/logrotate#163]
Here is the config:

```
"/var/log/httpd/*.log" {
  daily
  create 644 root root
  maxsize 500M
  rotate 5
  size 500M
  missingok
  compress
  notifempty
  sharedscripts
  dateext
  postrotate
    /sbin/service httpd reload > /dev/null 2>/dev/null || true
  endscript
}
```

After rotation we do see the new file being created, but after the postrotate the log files stay empty. 

Log files are of size 10 to 20GB

**Comment by kdudka** [comment]
What happens if you run the reload command manually?

**Comment by nareshku** [comment]
it works upon reloading manually.

**Comment by kdudka** [comment]
So the postrotate script either does not run, or fails somehow when invoked from logrotate's environment.  I would suggest to start with removing ```> /dev/null 2>/dev/null || true``` because it trashes stdout, stderr, and exit code, which makes it difficult to debug.

**Comment by nareshku** [comment]
Initially, I thought the same, but looking at the apache error_log it did reload successfully. But for some reason the httpd process still hold the old file handler.

Planning to pursue the option of copytruncate instead. The only thing need to check who this will work for log files for size 10-20GB.

**Comment by kdudka** [comment]
If httpd reloads successfully but then continues to log into the previously opened log file, it is an httpd issue you need to debug.  And yes, ```copytruncate``` is designed to make logrotate work in this case.
