### ISSUE TITLE
Add %H (hour) to dateformat

### ISSUE THREAD

**Issue by higuita** [logrotate/logrotate#164]
I want to rotate some heavy logs every 6 hours and i use `dateext`, but if i use hour rotate, the dateformat  `-%Y%m%d` is wrong... but the man page reports that it do not support the %H and using `-%Y%m%d-%s` makes the log names not easy to read and very long.

This could be simple to solve if the %H was added and one could setup `-%Y%m%d_%H`
%M might not be that important, but if adding the %H, why not adding also the %M, if someone ever needs it

thanks

**Comment by kdudka** [comment]
You forgot to tell us which version of logrotate you are using.

```%H``` was introduced in ```3.9.0```: 9edfa9f40fa4aa20b010c829d10eedb3e1bf985b

```%M``` was introduced in ```3.9.2```: d9166cdb424d186ad50aa0c450ae877ad1f0da64

Either update logrotate to a newer version, or just pick the commits above.

**Comment by higuita** [comment]
oops, sorry!
i'm using logrotate 3.8.7... if it is supported in newer versions will try to upgrade.
Thanks for the help and for logstash

**Comment by kdudka** [comment]
No problem.  Thank you for clarifying it.  Good luck with the upgrade!
