### ISSUE TITLE
"No such file or directory" error

### ISSUE THREAD

**Issue by daaru00** [logrotate/logrotate#165]
Hi,
I'm trying to configure a log rotate to delete files when they exceed the size of 100MB but I always get this error:
```
renaming /var/log/magento/test3.log.1 to /var/log/magento/test3.log.2 (rotatecount 1, logstart 1, i 1), 
renaming /var/log/magento/test3.log.0 to /var/log/magento/test3.log.1 (rotatecount 1, logstart 1, i 0), 
renaming /var/log/magento/test3.log to /var/log/magento/test3.log.1
disposeName will be /var/log/magento/test3.log.1
removing old log /var/log/magento/test3.log.1
error: error opening /var/log/magento/test3.log.1: No such file or directory
```
and the file `/var/log/magento/test3.log` is not rotated, not renamed, not deleted, nothing. I can not understand this error what it refers to.

My configuration file is:
/etc/logrotate.d/magento
```
/var/log/magento/*.log
{
  size 100M
  rotate 0
}
```
and I running the test using:
```
sudo logrotate /etc/logrotate.d/magento --debug
```

I also tried to change the directory permissions using root,adm,syslog as owner, changing permission 755, 640 but I still receiving the same error. Am I doing something wrong?

I'm working on Ubuntu 16.04 using logrotate version 3.8.7

**Comment by kdudka** [comment]
It seems to be just ```--debug``` what causes you problems.  Please try using ```--verbose``` instead.

**Comment by daaru00** [comment]
Yep, the problem is the "debug" flag, now working.. 

Please provide a better debug alert message, something like "logrotate is running in debug mode, no changes is made", see an error creates a lot of confusion.

**Comment by kdudka** [comment]
On Thursday, January 18, 2018 12:20:50 PM CET Fabio Gollinucci wrote:
> Yep, the problem is the "debug" flag, now working..

Thanks for confirmation!

> Please provide a better debug alert message, something like "logrotate is
> running in debug mode, no changes is made",

Sounds reasonable.  I will prepare a PR for that as time permits.

> see an error creates a lot of confusion.

The error seems to be specific to the old version of logrotate you are using.
I am not able to reproduce it with logrotate-3.13.0.

**Comment by daaru00** [comment]
>Sounds reasonable.  I will prepare a PR for that as time permits.

Great! 

>I am not able to reproduce it with logrotate-3.13.0.

I'm using the latest version from official ubuntu ppa.

Anyway, for me the issue can be closed. Thanks for the help.
