### ISSUE TITLE
compilation errors on NetBSD, episode 2

### ISSUE THREAD

**Issue by ahpnils** [logrotate/logrotate#17]
Long story short : some errors, identical to issue #1 , are still present.

Here are the errors :
onfig.c: In function 'isolateValue':
config.c:149:5: error: array subscript has type 'char' [-Werror=char-subscripts]
     while (chptr - *buf < length && isblank(*chptr))
     ^
config.c:153:2: error: array subscript has type 'char' [-Werror=char-subscripts]
  while ( chptr - *buf < length && isblank(*chptr))
  ^
config.c: In function 'isolateWord':
config.c:170:2: error: array subscript has type 'char' [-Werror=char-subscripts]
  while (start - *buf < length && isblank(*start))
  ^
config.c: In function 'readConfigFile':
config.c:871:4: error: array subscript has type 'char' [-Werror=char-subscripts]
    if (isblank(*start))
    ^
config.c:1536:4: error: array subscript has type 'char' [-Werror=char-subscripts]
    if (isblank(*start))
    ^

**Comment by hanzz** [comment]
I presume you have fixed it in following pull request, right?

https://github.com/logrotate/logrotate/commit/cb8e25c58988b14742aaa818a55e6342c947db2e

Can you verify that current master compiles for you?

**Comment by ahpnils** [comment]
The current master compiles for me, and yes, the pull request was the fix. Thanks for the merge !

**Comment by hanzz** [comment]
OK, so I'm closing this bug.
