### ISSUE TITLE
Feature Request: To make anonymous ip addresses in log files

### ISSUE THREAD

**Issue by Tronde** [logrotate/logrotate#185]
Hello,

I would like to have an option in logrotate that allows me to make anonymous ip addresses in log files. For example, in standard logfile ip addresses are being logged like 192.168.10.11. The whole ip address is only needed for a short period of time for troubleshooting purpose.

The logs are being rotated by logrotate and after some time the ip address should be made anonymous like 192.168.XXX.XXX. This way it should be not possible to identify a single host but I could keep the log files for a longer period of time for several reasons.

If logrotate could offer an option to do that I would not have to use other tools to work on my log files.

Maybe you or some other users like this idea, too. I would be happy to see such an option in some future release of logrotate.

Kind regards,
Tronde

**Comment by kdudka** [comment]
As I understand it, you want to replace some pattern in the files being rotated by a fixed string?

You should be able to do that by running `sed -i ...` in a `postrotate` script.  Or am I missing something?

**Comment by Tronde** [comment]
Well I'm not familiar with the postrotate option, yet. I have to think about it.

I would like to keep the pattern in the files for a certain time. After this time a part of this pattern should be replaced by a fixed string. So let's say I would like to rotate the files on a daily basis, keep them for 90 days but replace the pattern after 14 days.

I'll have to think about how to accomplish that with the help of a postrotate script. But thanks for this hint.

**Comment by kdudka** [comment]
Yes, I think you can do that with some scripting around.  I do not see an immediate need to change anything in logrotate's implementation.  I am afraid we could hardly find any generic enough interface for this task, compared to what we already have with `postrotate` and friends.

**Comment by rigid** [comment]
I've got the same problem. Is there a way to `sed -e 's/\(\([0-9]\{1,3\}\.\)\{3\}\)[0-9]\{1,3\}/\1xx/g'` every file when I already have a sharedscripts postrotate script to restart the web server?

**Comment by kdudka** [comment]
I hope so -- you can have more than one commands in your postrotate script.  Just make sure that the sed command is idempotent (does nothing when applied the second time).

**Comment by rigid** [comment]
I'm confused. Do you mean using the default "nosharedscripts" and make the webserver restart idempotent?
Currently I use:
```
/var/log/nginx/*_log {
        missingok
        delaycompress
        sharedscripts
        postrotate
                test -r /run/nginx.pid && kill -USR1 `cat /run/nginx.pid`
        endscript
}
```

Naively, I could only imagine something like:
```
/var/log/nginx/*_log {
        missingok
        delaycompress
        # only run once
        sharedscripts
        postrotate
                test -r /run/nginx.pid && kill -USR1 "$(cat /run/nginx.pid)"
        endscript
        # runs for every logfile
        nosharedscripts
        postrotate
                sed -ie 's/\(\([0-9]\{1,3\}\.\)\{3\}\)[0-9]\{1,3\}/\1xx/g' "$1"
        endscript
}
```

But according to the documentation, nosharedscripts would override sharedscripts.

**Comment by kdudka** [comment]
No, I meant something like this:
```
/var/log/nginx/*_log {
        ...
        sharedscripts
        postrotate
                test -r /run/nginx.pid && kill -USR1 "$(cat /run/nginx.pid)"
                sed -e ... -i ...
        endscript
}
```
... where the `sed` command is idempotent.

**Comment by rigid** [comment]
ah i see. I suppose there's no way to get the filenames of all rotated logs?

**Comment by kdudka** [comment]
When using `sharedscripts`, logrotate passes the `/var/log/nginx/*_log` pattern as the only argument of the script.  You can use shell globbing to run the sed command on the rotated files only.  It depends on whether you are using `datexet`, or numbering.  It could be something like `/var/log/nginx/*_log.[0-9]`.  You can limit the list of files such that each file is processed by sed only once ... but it is not so important if the sed command is idempotent and not much expensive performance-wise.

**Comment by rigid** [comment]
That works. Thank you!

**Comment by lpirl** [comment]
Another pointer: you can also globally hook a script up with the `compresscmd` ([example in the docstring at the top of this script](https://github.com/lpirl/admintools/blob/master/scripts/anonymize-log)).
