### ISSUE TITLE
Unify code indentation

### ISSUE THREAD

**Issue by johnlinp** [logrotate/logrotate#188]
The indentation in the code is not consistent. Tabs and spaces are mixed. Some code blocks inside `for` or `if` are not indent properly. The problems increase the difficulty to understand the code.

I would like to submit a pull request to clean up the indentation. Any suggestions are welcome.

**Comment by kdudka** [comment]
There seems to be no discussion any more.  There were just few comments on #189.  To put it simple, does anybody object against unifying the indentation of logrotate source code as such?

We will of course do our best to keep the changes minimal and preserve majority of the current coding style.

**Comment by johnlinp** [comment]
With the "4-space" vim config:

```
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
```

I got:

```
 config.c    | 3098 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------
 log.c       |  116 +++---
 log.h       |    8 +-
 logrotate.c | 3730 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------------------------
 logrotate.h |    4 +-
 queue.h     |  480 ++++++++++++-------------
 6 files changed, 3718 insertions(+), 3718 deletions(-)
```

Then with the "tab" vim config:

```
set noexpandtab
```

I got:

```
 config.c    | 2418 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------
 log.c       |   22 +-
 log.h       |   10 +-
 logrotate.c | 3088 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------------------------
 logrotate.h |   78 ++---
 queue.h     |  218 +++++++-------
 6 files changed, 2917 insertions(+), 2917 deletions(-)
```

It seems that using tabs will make less changes than using 4 spaces. I will update #189 based on tabs.

By the way, I am working on the latest commit: 3bb59ca.

**Comment by kdudka** [comment]
There might be some misunderstanding on my part but I fail to see how the above is better than:
```
 config.c    | 2494 +++++++++++++++++++++++++++++------------------------------
 log.c       |  108 +--
 log.h       |    8 +-
 logrotate.c | 2012 +++++++++++++++++++++++------------------------
 logrotate.h |    6 +-
 5 files changed, 2314 insertions(+), 2314 deletions(-)
```
... which was the result of my 10 minutes effort described at https://github.com/logrotate/logrotate/pull/189#issuecomment-375228922

I though that by further tweaks we would end up with an even smaller diffstat.

**Comment by kdudka** [comment]
Those options were not set arbitrarily.  They were chosen because they seemed to reflect the majority of the current coding style.  I believe that the resulting diffstat confirms it.  Am I missing anything?

**Comment by kdudka** [comment]
Also, when I checkout `r3-0` dated back to 1999, this seems to be the only coding style used over the whole code base.  The coding style has diverged during the development of the subsequent `3.x.x` releases because contributors simply did not care about the original coding style.

**Comment by johnlinp** [comment]
> ...contributors simply did not care about the original coding style.

Maybe it's because of the confusion of mixing spaces and tabs? If we continue using this mixed indentation style, I believe that the future contributors will continue ignore the coding style. 

I suggest that we should stick to one style, either spaces or tabs.

**Comment by kdudka** [comment]
Not really.  `vim: noet sw=4 ts=8` is one style.  We just need to make sure that the coding style will not diverge again by adding vim modeline and perhaps some Travis CI hook.  Otherwise, these troubles may reoccur, no matter which style you choose.

To be clear, `vim: noet sw=4 ts=8` is not my personal preference and I have never used it for my own projects.  It is just the original indentation style of logrotate and still used by majority of its current code base.

**Comment by johnlinp** [comment]
When I use `vim: noet sw=4 ts=8` against the latest commit (3bb59ca), the result is:

```
 config.c    | 2496 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------------------------
 log.c       |  108 ++++-----
 log.h       |    8 +-
 logrotate.c | 2010 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
 logrotate.h |    4 +-
 queue.h     |  442 +++++++++++++++++-----------------
 6 files changed, 2534 insertions(+), 2534 deletions(-)
```

So basically we have 2 options:

1. 4-space style indentation: change 2917 lines.
2. mixed style (spaces + tabs) indentation: change 2534 lines.

I would say that I will vote for the 4-space style.

**Comment by kdudka** [comment]
I have prepared two competing pull request for comparison: #212 and #213 

Could you please all have a look and comment on them?

**Comment by johnlinp** [comment]
+1 for #213 since I prefer all-space or all-tab style.

**Comment by kdudka** [comment]
So far 2 people have voted for #213 and nobody for #212.  Nobody is proposing anything else...

**Comment by glensc** [comment]
i see 1 and 0 ;)

**Comment by kdudka** [comment]
@glensc I counted your "like" on #213 as a vote.

**Comment by kdudka** [comment]
Nobody has commented on this in the last two weeks.  I am going to merge #213 on Friday September 14th unless someone objects till then.

**Comment by johnlinp** [comment]
@kdudka Thank you very much for resolving this issue. I really appreciate this.
