### ISSUE TITLE
How can I reference the post-rotated log in postrotate?

### ISSUE THREAD

**Issue by brianjmurrell** [logrotate/logrotate#19]
I want to run an analysis process on the post-rotated/pre-compressed log in the ```postrotate``` handler, but by default on RHEL, ```dateext``` is being used so I cannot depend on using ```logname.1```.  Is there any "handle" I can use to reference the post-rotated log in the ```postrotate``` handler?

**Comment by hanzz** [comment]
What version of logrotate is it? Generally it should be possible to use postrotate scripts arguments. Use "echo $*" in postrotate script to find out what arguments your logrotate version passes to the postscript.
