### ISSUE TITLE
"rotate 0" seems not to work with "copytruncate"

### ISSUE THREAD

**Issue by TheKLARKEN** [logrotate/logrotate#191]
Hi, everyone! After some extensive testing, mostly on `3.9.2`, it seems that there's no way to truncate a file without creating a copy.

I heard that using `rotate 0` with `copytruncate` was likely supposed to work, but after no luck with that, I was pointed here thanks to help from @kdudka, who suggested I create an issue for others to look at (it didn't seem to be working on the latest version, as well).

I apologize if this is the normal, expected behavior or if I'm missing something simple, but I tried my best to use as many different configurations as possible to see if any would work. 🤔 

I appreciate your time, and I appreciate this awesome tool we use for other scenarios hundreds of times every week!

**Comment by kdudka** [comment]
Indeed.  I see no valid reason why these two option should not work together.

**Comment by kdudka** [comment]
#195 should fix this.  @TheKLARKEN could you please have a look?

**Comment by TheKLARKEN** [comment]
Hi, @kdudka, I'm sorry for the late reply! I'll take a look at that right away.
