### ISSUE TITLE
Add support for %H, %M, and %S to date format

### ISSUE THREAD

**Issue by dmccombs** [logrotate/logrotate#194]
For my log files to match patterns of tooling I use, it would be helpful if the date format supported `%H`, `%M`, and `%S`.

I can look at adding support for this and open a pull request, but the documentation seems pretty clear to purposefully only support `%Y` `%m` `%d` and `%s`.

What's the reason for this before I go any further?

**Comment by kdudka** [comment]
Which version of logrotate are you using?

The proposed improvement seems to be already implemented by commits 9edfa9f40fa4aa20b010c829d10eedb3e1bf985b and d9166cdb424d186ad50aa0c450ae877ad1f0da64.  So it should be available since logrotate-3.9.2 onward.

**Comment by dmccombs** [comment]
Great, I had been using version 3.8.7 and saw at a glance in current master the comment at https://github.com/logrotate/logrotate/blob/master/logrotate.c#L1449

**Comment by kdudka** [comment]
Indeed. The comment is misleading.  What about the following patch?

```
--- a/logrotate.c
+++ b/logrotate.c
@@ -1443,8 +1443,7 @@ static int prerotateSingleLog(struct logInfo *log, int logNum,
         mktime(&now);
     }

-       /* Allow only %Y %d %m and create valid strftime format string
-        * Construct the glob pattern corresponding to the date format */
+       /* Construct the glob pattern corresponding to the date format */
        dext_str[0] = '\0';
        if (log->dateformat) {
                size_t i = 0, j = 0;
```

**Comment by kdudka** [comment]
Pushed.  Thanks!
