### ISSUE TITLE
Error Renaming logrotate.status.tmp File

### ISSUE THREAD

**Issue by histamineblkr** [logrotate/logrotate#197]
# Renaming Error
There seems to be this intermittent renaming error that I am experiencing on only one server. It also seems to happen more frequently in the mornings from 3am to 10am. However, I haven't been able to determine any real pattern or cause. 
Logrotate seems to be rotating the logs so I'm not reporting anything about that functionality. I'm just unsure if it rotates when the intermittent error happens.

## Info
**version:** logrotate-3.7.8-28.el6.x86_64
**os:** CentOS 6.3
**error:** error renaming temp state file /var/lib/logrotate.status.tmp
**use:** A cron job invoked every 15 minutes

### Manual Run with Verbosity 
I ran it manually with `logrotate -v /etc/logrotate.conf`, which produced no noticeable errors.

### Specified a State File
I tried explicitly running with the `-s` flag `logrotate -s /tmp/logrotate /etc/logrotate.conf`. The error persisted.

### Removing the Logrotate Status File
I removed the `/var/lib/logrotate.status` file and then used `logrotate -f /etc/logrotate.d/syslog` to create a new one. This was from an old bug [here](https://bugzilla.redhat.com/show_bug.cgi?id=447022) I thought may solve the issue. It did not.

### STraced
I went ahead and straced it and this gave me some insight into what was happening.
Note: the elipses is /etc/localtime and is many lines so I left out for clarity as it doesn't seem to have anything to do with the logrotate.status errors.

#### Error Run
```
stat("/var/lib/logrotate.status", {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
09:30:01 open("/var/lib/logrotate.status", O_RDONLY) = 3
09:30:01 fstat(3, {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
09:30:01 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f82e27cf000
09:30:01 read(3, "logrotate state -- version 2\n\"/v"..., 4096) = 928
...
...
09:30:01 unlink("/var/lib/logrotate.status.tmp") = 0
09:30:01 open("/var/lib/logrotate.status", O_RDONLY) = 3
09:30:01 fgetxattr(3, "system.posix_acl_access", 0x7fff0210a910, 132) = -1 EOPNOTSUPP (Operation not supported)
09:30:01 close(3)                       = 0
09:30:01 stat("/var/lib/logrotate.status", {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
09:30:01 umask(0777)                    = 022
09:30:01 getpid()                       = 17898
09:30:01 open("/var/lib/logrotate_temp.qY37wE", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
09:30:01 umask(022)                     = 0777
09:30:01 fstat(3, {st_mode=S_IFREG, st_size=0, ...}) = 0
09:30:01 fchmod(3, 0100644)             = 0
09:30:01 rename("/var/lib/logrotate_temp.qY37wE", "/var/lib/logrotate.status.tmp") = 0
09:30:01 fcntl(3, F_GETFL)              = 0x8002 (flags O_RDWR|O_LARGEFILE)
09:30:01 fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
09:30:01 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f82e27cf000
09:30:01 lseek(3, 0, SEEK_CUR)          = 0
09:30:01 fsync(3)                       = 0
09:30:01 write(3, "logrotate state -- version 2\n\"/v"..., 928) = 928
09:30:01 close(3)                       = 0
09:30:01 munmap(0x7f82e27cf000, 4096)   = 0
09:30:01 rename("/var/lib/logrotate.status.tmp", "/var/lib/logrotate.status") = 0
09:30:01 exit_group(0)                  = ?
 such file or directory)
09:30:01 unlink("/var/lib/logrotate.status.tmp") = -1 ENOENT (No such file or directory)
09:30:01 write(2, "error: ", 7)         = 7
09:30:01 write(2, "error renaming temp state file /"..., 61) = 61
09:30:01 exit_group(1)
```
#### Working Run...?
```
stat("/var/lib/logrotate.status", {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
10:15:01 open("/var/lib/logrotate.status", O_RDONLY) = 3
10:15:01 fstat(3, {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
10:15:01 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f596fa47000
10:15:01 read(3, "logrotate state -- version 2\n\"/v"..., 4096) = 928
...
...
10:15:01 unlink("/var/lib/logrotate.status.tmp") = -1 ENOENT (No such file or directory)
10:15:01 open("/var/lib/logrotate.status", O_RDONLY) = 3
10:15:01 fgetxattr(3, "system.posix_acl_access", 0x7fff90171390, 132) = -1 EOPNOTSUPP (Operation not supported)
10:15:01 close(3)                       = 0
10:15:01 stat("/var/lib/logrotate.status", {st_mode=S_IFREG|0644, st_size=928, ...}) = 0
10:15:01 umask(0777)                    = 022
10:15:01 getpid()                       = 8010
10:15:01 open("/var/lib/logrotate_temp.vWdK6Y", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
10:15:01 umask(022)                     = 0777
10:15:01 fstat(3, {st_mode=S_IFREG, st_size=0, ...}) = 0
10:15:01 fchmod(3, 0100644)             = 0
10:15:01 rename("/var/lib/logrotate_temp.vWdK6Y", "/var/lib/logrotate.status.tmp") = 0
10:15:01 fcntl(3, F_GETFL)              = 0x8002 (flags O_RDWR|O_LARGEFILE)
10:15:01 fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
10:15:01 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f596fa47000
10:15:01 lseek(3, 0, SEEK_CUR)          = 0
10:15:01 fsync(3)                       = 0
10:15:01 write(3, "logrotate state -- version 2\n\"/v"..., 928) = 928
10:15:01 close(3)                       = 0
10:15:01 munmap(0x7f596fa47000, 4096)   = 0
10:15:01 rename("/var/lib/logrotate.status.tmp", "/var/lib/logrotate.status") = 0
10:15:01 exit_group(0)                  = ?
```
When we look at the error run, We have an "fgetxattr" system call that throws a EOPNOTSUPP (operation not supported on socket). Not sure if this is meaningful to the error. 
Then we can see that during the unlink() function is where we get the error for the logrotate.status.tmp with an ENOENT (which is No such file or directory). This makes sense because there are two rename() function calls: 
`rename("/var/lib/logrotate_temp.qY37wE", "/var/lib/logrotate.status.tmp")`
and then 
`rename("/var/lib/logrotate.status.tmp", "/var/lib/logrotate.status") = 0`. 
This would mean when the unlink runs, there is no longer a file named "logrotate.status.tmp". Why this happens and in this order, I have no idea since /usr/sbin/logrotate is a binary.

## Thoughts?
Any ideas or anything else I can do or try?
Is there any more information I can provide that would be helpful to look into this problem?

**Comment by kdudka** [comment]
Thank you for providing all the details!

There seems to be some leftover or missing part in the `Error Run` strace around here:
```
09:30:01 rename("/var/lib/logrotate.status.tmp", "/var/lib/logrotate.status") = 0
09:30:01 exit_group(0)                  = ?
 such file or directory)
09:30:01 unlink("/var/lib/logrotate.status.tmp") = -1 ENOENT (No such file or directory)
```

Could you please review the original capture and fix this as it seems to be the most important part of the output?

> When we look at the error run, We have an "fgetxattr" system call that throws a EOPNOTSUPP (operation not supported on socket). Not sure if this is meaningful to the error.

I do not think it is related as it appears in both the `Error` and `Working` runs.

> This would mean when the unlink runs, there is no longer a file named "logrotate.status.tmp". Why this happens and in this order, I have no idea since /usr/sbin/logrotate is a binary.

Could you please check which version of logrotate you are using?
```
logrotate --version
```

Up2date version of the code in question is available here:
https://github.com/logrotate/logrotate/blob/3bb59ca2/logrotate.c#L2217

The idea behind is that, if any error occurs while writing the new state into temporary file, the previous state is preserved instead of overwriting it by the newly written temporary file and the temporary file (with possibly corrupted data inside) is unlinked.  You can see that the `error` flag can be set at quite many places in the code, so it is difficult to tell what happens without additional debugging.

**Comment by histamineblkr** [comment]
The logrotate version is in the post above (Info -> version) and is 3.7.8.

As for the Error Run on strace, that's exactly how it outputted and I copied it exactly without error so I'm not sure what I can do to help about that. Since it is intermittent it wasn't easy to get the error traced, but I'll create a long running file and then find the time associated with another error run and post the full output again.

**Comment by kdudka** [comment]
> The logrotate version is in the post above (Info -> version) and is 3.7.8.

Sorry, I overlooked this info.  Then you can get the corresponding source code using the following commands:
```
$ mkdir lr && cd lr
$ rpm2cpio http://vault.centos.org/6.9/os/Source/SPackages/logrotate-3.7.8-28.el6.src.rpm | cpio -div
$ rpmbuild -bp logrotate.spec --define "_sourcedir $PWD" --define "_builddir $PWD"
```

The code in question looks like this:
```c
static int writeState(char *stateFilename)
{
	struct logState *p;
	FILE *f;
	char *chptr;
	int i;
	int error = 0;
	int bytes = 0;
	int fdcurr;
	int fdsave;
	struct stat sb;
	char *tmpFilename = NULL;

	tmpFilename = malloc(strlen(stateFilename) + 5 );
	if (tmpFilename == NULL) {
		message(MESS_ERROR, "could not allocate memory for "
			"tmp state filename\n");
		return 1;
	}
	strcpy(tmpFilename, stateFilename);
	strcat(tmpFilename, ".tmp");
	/* Remove possible tmp state file from previous run */
	unlink(tmpFilename);


	if ((fdcurr = open(stateFilename, O_RDONLY)) < 0) {
	    message(MESS_ERROR, "error opening %s: %s\n", stateFilename,
		    strerror(errno));
		free(tmpFilename);
	    return 1;
	}

#ifdef WITH_SELINUX
	if (selinux_enabled) {
	    security_context_t oldContext;
	    if (fgetfilecon_raw(fdcurr, &oldContext) >= 0) {
		if (getfscreatecon_raw(&prev_context) < 0) {
		    message(MESS_ERROR,
			    "getting default context: %s\n",
			    strerror(errno));
		    if (selinux_enforce) {
				freecon(oldContext);
				free(tmpFilename);
                close(fdcurr);
				return 1;
		    }
		}
		if (setfscreatecon_raw(oldContext) < 0) {
		    message(MESS_ERROR,
			    "setting file context %s to %s: %s\n",
			    tmpFilename, oldContext, strerror(errno));
			if (selinux_enforce) {
				freecon(oldContext);
				free(tmpFilename);
                close(fdcurr);
				return 1;
		    }
		}
		message(MESS_DEBUG, "set default create context\n");
		freecon(oldContext);
	    } else {
		    if (errno != ENOTSUP) {
			    message(MESS_ERROR, "getting file context %s: %s\n",
				    tmpFilename, strerror(errno));
			    if (selinux_enforce) {
					free(tmpFilename);
                    close(fdcurr);
				    return 1;
			    }
		    }
	    }
	}
#endif
#ifdef WITH_ACL
	if ((prev_acl = acl_get_fd(fdcurr)) == NULL) {
		if (errno != ENOTSUP) {
			message(MESS_ERROR, "getting file ACL %s: %s\n",
				stateFilename, strerror(errno));
			close(fdcurr);
            free(tmpFilename);
			return 1;
		}
	}
#endif

	close(fdcurr);
	if (stat(stateFilename, &sb)) {
		free(tmpFilename);
		return 1;
	}

	fdsave = createOutputFile(tmpFilename, O_RDWR | O_CREAT | O_TRUNC, &sb, prev_acl, 0);
#ifdef WITH_ACL
	if (prev_acl) {
		acl_free(prev_acl);
		prev_acl = NULL;
	}
#endif
#ifdef WITH_SELINUX
	if (selinux_enabled) {
	    setfscreatecon_raw(prev_context);
		freecon(prev_context);
		prev_context = NULL;
	}
#endif

	if (fdsave < 0) {
	    free(tmpFilename);
	    return 1;
	}

	f = fdopen(fdsave, "w");
	if (!f) {
		message(MESS_ERROR, "error creating temp state file %s: %s\n",
			tmpFilename, strerror(errno));
		free(tmpFilename);
		return 1;
	}

	bytes =  fprintf(f, "logrotate state -- version 2\n");
	if (bytes < 0)
		error = bytes;

	for (i = 0; i < hashSize && error == 0; i++) {
		for (p = states[i]->head.lh_first; p != NULL && error == 0;
				p = p->list.le_next) {
			error = fputc('"', f) == EOF;
			for (chptr = p->fn; *chptr && error == 0; chptr++) {
				switch (*chptr) {
				case '"':
				case '\\':
					error = fputc('\\', f) == EOF;
					break;
				case '\n':
					error = fputc('\\', f) == EOF;
					if (error == 0) {
						error = fputc('n', f) == EOF;
					}
					continue;
				}
				if (error == 0 && fputc(*chptr, f) == EOF) {
					error = 1;
				}
			}

			if (error == 0 && fputc('"', f) == EOF)
				error = 1;
			
			if (error == 0) {
				bytes = fprintf(f, " %d-%d-%d\n",
				p->lastRotated.tm_year + 1900,
				p->lastRotated.tm_mon + 1,
				p->lastRotated.tm_mday);
				if (bytes < 0)
					error = bytes;
			}
		}
	}

	if (error == 0)
		error = fsync(fdsave);

	if (error == 0)
		error = fclose(f);
	else
		fclose(f);

	if (error == 0) {
		if (rename(tmpFilename, stateFilename)) {
			unlink(tmpFilename);
			error = 1;
			message(MESS_ERROR, "error renaming temp state file %s\n",
				tmpFilename);
		}
	}
	else {
		unlink(tmpFilename);
		if (errno)
			message(MESS_ERROR, "error creating temp state file %s: %s\n",
			tmpFilename, strerror(errno));
		else
			message(MESS_ERROR, "error creating temp state file %s%s\n",
				tmpFilename, error == ENOMEM ?
				": Insufficient storage space is available." : "" );
	}
	free(tmpFilename);
	return error;
}
```

**Comment by histamineblkr** [comment]
I was able to get an updated strace that wasn't cutoff
```
14:45:01 unlink("/var/lib/logrotate.status.tmp") = 0
14:45:01 open("/var/lib/logrotate.status", O_RDONLY) = 3
14:45:01 fgetxattr(3, "system.posix_acl_access", 0x7fff5d829970, 132) = -1 EOPNOTSUPP (Operation not supported)
14:45:01 close(3)                       = 0
14:45:01 stat("/var/lib/logrotate.status", {st_mode=S_IFREG|0644, st_size=906, ...}) = 0
14:45:01 umask(0777)                    = 022
14:45:01 getpid()                       = 25749
14:45:01 open("/var/lib/logrotate_temp.FOojNp", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
14:45:01 umask(022)                     = 0777
14:45:01 fstat(3, {st_mode=S_IFREG, st_size=0, ...}) = 0
14:45:01 fchmod(3, 0100644)             = 0
14:45:01 rename("/var/lib/logrotate_temp.FOojNp", "/var/lib/logrotate.status.tmp") = 0
14:45:01 fcntl(3, F_GETFL)              = 0x8002 (flags O_RDWR|O_LARGEFILE)
14:45:01 fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
14:45:01 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f74fa379000
14:45:01 lseek(3, 0, SEEK_CUR)          = 0
14:45:01 fsync(3)                       = 0
14:45:01 write(3, "logrotate state -- version 2\n\"/v"..., 906) = 906
14:45:01 close(3)                       = 0
14:45:01 munmap(0x7f74fa379000, 4096)   = 0
14:45:01 rename("/var/lib/logrotate.status.tmp", "/var/lib/logrotate.status") = 0
14:45:01 exit_group(0)                  = ?
(No such file or directory)
14:45:01 unlink("/var/lib/logrotate.status.tmp") = -1 ENOENT (No such file or directory)
14:45:01 write(2, "error: ", 7)         = 7
14:45:01 write(2, "error renaming temp state file /"..., 61) = 61
14:45:01 exit_group(1)                  = ?
```

Oh, so this is where the code errors at.
```
if (error == 0) {
		if (rename(tmpFilename, stateFilename)) {
			unlink(tmpFilename);
			error = 1;
			message(MESS_ERROR, "error renaming temp state file %s\n",
				tmpFilename);
		}
	}
```

Isn't the bug the unlink? Why would you unlink right after you changed the name? It shouldn't exist anymore.

**Comment by kdudka** [comment]
The `unlink()` in logrotate's code is only invoked if `rename()` returns non-zero value (on failure).  According to strace output, the `rename()` syscall returns 0 but apparently for some reason the `rename()` library call returns non-zero value.  Could you please capture the output of `ltrace`?

**Comment by histamineblkr** [comment]
I will install ltrace today, but it will take some time to be able to have an error run captured since it is intermittent.

**Comment by histamineblkr** [comment]
Here is a seemingly successful run of logrotate with ltrace.
[ltrace-logrotate.log](https://github.com/logrotate/logrotate/files/2006382/ltrace-logrotate.log)

**Comment by kdudka** [comment]
Thanks!  Unfortunately, the ltrace output above does not capture the problematic `unlink()` call, so it cannot explain why it happens.

**Comment by histamineblkr** [comment]
Finally got it with the error.
[ltrace-error-logrotate.log](https://github.com/logrotate/logrotate/files/2009598/ltrace-error-logrotate.log)

**Comment by kdudka** [comment]
So it confirms my hypotheses that `rename()` syscall returns 0 while `rename()` library call returns non-zero value, assuming that both ltrace and strace describe the same scenario (you can run `ltrace -S` to be 100% sure).  This must be some tricky to debug glibc issue I guess...

**Comment by peterjanes** [comment]
Here's an `ltrace -S`.
[ltrace-S-error-logrotate.log](https://github.com/logrotate/logrotate/files/2190167/ltrace-S-error-logrotate.log)

**Comment by kdudka** [comment]
The last `ltrace -S` output captures a different situation because the `rename` syscall returns -2 whereas the `rename` syscall in https://github.com/logrotate/logrotate/issues/197#issuecomment-388199565 returned 0.

**Comment by peterjanes** [comment]
Ah, you're right. Shall I enter a new issue?

**Comment by kdudka** [comment]
I am afraid that you have captured the expected behavior: If logrotate fails to rename the temporary file, then logrotate just unlinks it to end up back in an consistent (although outdated) state.

**Comment by peterjanes** [comment]
Hmm. It's happening every time logrotate runs, which doesn't seem expected. `/var/lib/logrotate/logrotate.status` is being modified, too, as I see that it's recorded new timestamps for any files that were rotated.

**Comment by kdudka** [comment]
Please report it as a separate issue and attach the output of ltrace with unabbreviated file names (use `strace -Ss256 ...` or something like that).
