### ISSUE TITLE
logrotate exit with 0 although errors are present

### ISSUE THREAD

**Issue by PascalBourdier** [logrotate/logrotate#199]
logrotate exit with 0 although errors are present

how-to reproduce :

make a short file with an error in rotate directive
```
# testwithd
/foo/bar/*.log {
    rotate 4	# blahblah
    nocreate	# blahblah
    daily	# blahblah
}
```

try to check this file with '-d' option
```
logrotate -d testwithd
reading config file testwithd
error: testwithd:3 bad rotation count '4	# blahblah'
error: found error in /foo/bar/*.log , skipping
removing last 1 log configs
Allocating hash table for state file, size 15360 B

Handling 0 logs
```

get the exit code
```
echo $?
0
```

**Comment by kdudka** [comment]
Sorry for the delay!  I believe that pull request #204 fixes this.  Could you please try it out?

**Comment by kdudka** [comment]
Thanks for confirmation!  I have added a regression test to cover this.
