### ISSUE TITLE
logrotate maxdepth exclusion problem

### ISSUE THREAD

**Issue by Jason-Gardner-CK** [logrotate/logrotate#201]
I have a fairly straight forward log rotation definition (no regex, only globbing) that is not accepting exception on deeper path rules. 

The line indicated below is where the problem is. If I remove the exclusion of .gz from it then it will run (even with the folder exclusion). But then I will miss files because well intentioned developers sometimes don't adhere to a naming standard like ".log", but that should be ok cause we should have a way to handle that.  

```
/var/log/*/*/*/*[!folder1]/*[!.gz]    ### this is the line ###
/var/log/*/*/*/*[!.gz] .   ### this line I am not sure about... nothing currently at this level ###
/var/log/*/*/*[!.gz] .     ### this line the the rest after are working like a dream ###
/var/log/*[!sar]/*[!.gz]
/var/log/*[!.gz] {
	copytruncate
	hourly
	rotate 4
	missingok
	nomail
	dateext
	dateformat-%Y%m%d-%s
	compress
}
```

Logrotate version 3.7.28 (latest version default supported by Centos6)
OS - centos 6.8 ^^

It works if the exclusion is not on the line. I will be testing this on centos7 over the weekend to see if the pattern persists, but as I find no reference to it I have little hope. 

Any guidance/input would be appreciated.

**Comment by kdudka** [comment]
logrotate uses `glob(3)` to implement the globbing:
https://linux.die.net/man/3/glob

So whatever you are able to do with that function, you can do with logrotate, too.  I do not think that the exact version of logrotate will make any difference here.
