### ISSUE TITLE
Feature request: Add option to never delete old files

### ISSUE THREAD

**Issue by marak8** [logrotate/logrotate#202]
It'd be nice if logrotate had an option to never delete old files. Current workaround is to set `rotate` to really big number which is a bit ugly. Use case: Rotating Irssi chat logs. You want to compress the big ones but never want to delete old ones.

**Comment by kdudka** [comment]
It makes sense to me.  We could probably use `-1` for that?

**Comment by marak8** [comment]
`-1` looks good. :-)

**Comment by kdudka** [comment]
Implemented in pull request #205 - could you please try it out?
