### ISSUE TITLE
Logrotate fails with copytruncate/nodelaycompress set if a foo.log.1 file already exists

### ISSUE THREAD

**Issue by sruggier** [logrotate/logrotate#203]
Imagine we have a logfile `/var/log/foo.log`, which is managed by logrotate. If we set `copytruncate` and `nodelaycompress`, logrotate treats the presence of `/var/log/foo.log.1` as a fatal error.

I'd suggest that the expected behaviour should be to rotate `/var/log/foo.log.1` to `/var/log/foo.log.2.gz`, with at most a warning. Most notably, this situation occurs naturally when switching from `delaycompress` to `nodelaycompress` while `copytruncate` is enabled, so it's kind of a pain right now.

One can work around the problem in a `prerotate` script (this only works with `nosharedscripts`):
```
    prerotate
        [ -e "${1%.1}.1" ] && gzip --best < "${1%.1}.1" > "${1%.1}.2.gz" && rm "${1%.1}.1"
        true
    endscript
```

**Comment by kdudka** [comment]
Which version of logrotate are you using?

Since `logrotate-3.11.0`, this should not be treated as fatal error any more.  See pull request #23 for details.
