### ISSUE TITLE
logrotate salad with XZ compression

### ISSUE THREAD

**Issue by sofar** [logrotate/logrotate#206]
See also:

https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1472834

Check out this wonderful result in /var/log:

```
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.1.xz
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.1.xz.1.xz
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.1.xz.1.xz.1.xz
-rw-r--r-- 1 root root      1640 Jun 27 00:00 minetest.foo-projects.org.access.1.xz.1.xz.1.xz.1.xz
-rw-r--r-- 1 root root      2412 Jun 27 00:00 minetest.foo-projects.org.access.1.xz.1.xz.2.xz
-rw-r--r-- 1 root root      2040 Jun 23 22:34 minetest.foo-projects.org.access.1.xz.1.xz.3.xz
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.1.xz.2.xz
-rw-r--r-- 1 root root        32 Jun 27 00:00 minetest.foo-projects.org.access.1.xz.2.xz.1.xz
-rw-r--r-- 1 root root         0 Jun 27 00:00 minetest.foo-projects.org.access.1.xz.3.xz
-rw-r--r-- 1 root root      1568 Jun 23 22:34 minetest.foo-projects.org.access.1.xz.4.xz
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.2.xz
-rw-r--r-- 1 root root        32 Jun 28 00:00 minetest.foo-projects.org.access.2.xz.1.xz
-rw-r--r-- 1 root root        32 Jun 25 23:16 minetest.foo-projects.org.access.2.xz.2.xz
-rw-r--r-- 1 root root         0 Jun 29 00:00 minetest.foo-projects.org.access.3.xz
-rw-r--r-- 1 root root        32 Jun 25 23:16 minetest.foo-projects.org.access.3.xz.1.xz
-rw-r--r-- 1 root root      1468 Jun 25 23:16 minetest.foo-projects.org.access.4.xz
-rw-r--r-- 1 root root      1384 Jun 23 22:34 minetest.foo-projects.org.access.6.xz
-rw-r--r-- 1 root root    323800 Jun 22 23:59 minetest.foo-projects.org.access.7.xz

```

To enable compression and the xz/unxz commands, I compiled it with the appropriate `configure` flags.

edit: added empty files created as well

**Comment by kdudka** [comment]
Next time please provide self-contained steps to reproduce the issue.  Which version of logrotate are you using?

The automatic setting of file extension based on the compression program was introduced in `3.11.0`: 63401711fc9dfa73f1874cb44cb0f4af3ad9284f

If you use an older version of logrotate, you need to specify the file extension manually via `compressext`.

**Comment by sofar** [comment]
I am using 22892fb94b7da0018802363637928d21b7f00687 (which includes the above linked commit)

**Comment by sofar** [comment]
compile flags I used:

```
--with-compress-command=/usr/bin/xz
--with-uncompress-command=/usr/bin/unxz
--with-compress-extension=xz
```

I'm not doing anything weird. Just using the provided options to the `configure` script.

**Comment by kdudka** [comment]
Please retry it with `--with-compress-extension=.xz` instead.

**Comment by sofar** [comment]
Geezus, I accidentally reverted it back to "gz" and not ".gz" and now my server is 100% CPU pegged.

Let's call this a giant documentation bug.

**Comment by sofar** [comment]
I tried doing `ls` in /var/log/nginx. but after 3 minutes, it has not yet returned.

**Comment by sofar** [comment]
```
  $ ./configure --sysconfdir=/etc --localstatedir=/var --with-compress-command=/usr/bin/xz --with-uncompress-command=/usr/bin/unxz --with-compress-extension=.xz
```

And the result, after a few days:

```
-rw-r--r-- 1 root root     9144 Aug  6 14:51 minetest.foo-projects.org.access
-rw-r--r-- 1 root root        0 Aug  6 00:00 minetest.foo-projects.org.access.1.xz
-rw-r--r-- 1 root root     1652 Aug  4 23:24 minetest.foo-projects.org.access.1.xz.1.xz
-rw-r--r-- 1 root root     1136 Aug  4 23:24 minetest.foo-projects.org.access.2.xz
-rw-r--r-- 1 root root     2068 Aug  3 23:32 minetest.foo-projects.org.access.3.xz
```

**Comment by kdudka** [comment]
The `--with-compress-extension` option of the configure script specifies the default compress extension.  It can be overridden at run time though.  Did you search your config files for the `compressext` directive?

**Comment by kdudka** [comment]
Sorry, I am not able to follow this mess any more.  Please file a new bug report with exact steps to reproduce so that anyone can try it out locally and properly analyze the problem in question.
