### ISSUE TITLE
Feature request: create new log file with same mode and owner and group as the old log file

### ISSUE THREAD

**Issue by zeightnoteight** [logrotate/logrotate#207]
sometimes when using wildcard on the files, like `/var/log/**/*.log` log files by multiple services get matched, in those cases current `create` command doesn't help much, it would be great to have such option

**Comment by kdudka** [comment]
As far as I understand the documentation, it should work already:
> Any  of the log file attributes may be omitted, in which case those attributes for the new file will use the same values as the original log file for the omitted attributes.

Are you saying it does not work as documented?  Which version of logrotate are you using?

**Comment by zeightnoteight** [comment]
sry my mistake
