### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by normancarcamo** [logrotate/logrotate#210]
"logrotate" was a recommended library to me in the current project that I'm working with to rotate some logs of my app but I couldn't find their documentation or some tutorial of it to look into details.
Can anybody tell me what can I do besides of just cloning your repo?

Thanks

**Comment by normancarcamo** [comment]
Oh sorry guys, but I have realized that it's a command line utility and I have to see man for the details I want, but does't it also work for OSX? I'm currently developing and testing so in this case I need to give it a try in my laptop.

thanks.

**Comment by glensc** [comment]
there's raw [man page](https://en.wikipedia.org/wiki/Man_page) in repository:
- https://github.com/logrotate/logrotate/blob/3.14.0/logrotate.8.in

@kdudka perhaps convert it to `.pod` (or some other format) that github is able to render online and can easily converted to troff/groff/nroff?

example: https://github.com/glensc/bacula-backup-mysql/blob/0.8/README.pod

**Comment by normancarcamo** [comment]
@glensc Can I use it on OSX for testing purposes for now?
The app of course is hosted in a server with Linux but for now?

**Comment by kdudka** [comment]
@glensc One can find rendered man pages all over the Internet, for example here:
https://linux.die.net/man/8/logrotate

@normancarcamo If you are able to build logrotate on OS X, why not.  Just give it a try and let us know in case you encounter any portability problems.  Some previous reports (for example #117) suggest that people use logrotate on OS X, too.
