### ISSUE TITLE
Error renaming logrotate.status.tmp file on every execution from cron

### ISSUE THREAD

**Issue by peterjanes** [logrotate/logrotate#211]
On a specific set of hosts, logrotate exits with an error code and reports `error renaming temp state file /var/lib/logrotate/logrotate.status.tmp` every time it runs. There are no errors reported by the files being rotated, the `logrotate.status.tmp` file is removed, and the `logrotate.status` file is updated, so I think the error is spurious.

# Info
version: logrotate-3.14.0-1.fc28.x86_64
os: Fedora 28
error: error renaming temp state file /var/lib/logrotate.status.tmp
use: A cron job invoked every hour

# What I've Tried
Manual execution of `logrotate -v /etc/logrotate.conf` produced no errors.

Specifying an alternative state file that doesn't initially exist, i.e. using `logrotate -s /tmp/logrotate.status /etc/logrotate.conf` in the cron job, reported the error on the second and subsequent executions (pointing to `/tmp/logrotate.status.tmp` instead of the default). Similarly, removing the default status file `/var/lib/logrotate.status` before executing the cron job reported the error on the second and subsequent executions.

I've [attached](https://github.com/logrotate/logrotate/files/2267750/logrotate-ltrace.txt) the output of `ltrace -s 256 -S logrotate -l syslog /etc/logrotate.conf` as suggested in #197, which looked similar but appears to be unrelated.

**Comment by peterjanes** [comment]
This is [an ltrace of a successful (non-cron) run](https://github.com/logrotate/logrotate/files/2268120/logrotate-ltrace-success.txt), invoked using the same cron script run from the command line, in case it shows anything useful. Just browsing a diff between the two, I don't see anything particularly interesting until the `rename@SYS()` succeeds with `0`, where it failed with `-2` in the original.

**Comment by kdudka** [comment]
This looks like there are two processes of logrotate running at the same time.  In the failing case, `/var/lib/logrotate/logrotate.status.tmp` is first unlinked, then created again, the data is written and successfully flushed using the file descriptor.  But, when logrotate wants to rename `/var/lib/logrotate/logrotate.status.tmp` to `/var/lib/logrotate/logrotate.status`, it fails with `ENOENT`.  I think it means that something else (most likely another process of logrotate) must have unlinked `/var/lib/logrotate/logrotate.status.tmp` already.

> I don't see anything particularly interesting until the rename@SYS() succeeds with 0, where it failed with -2 in the original.

There is actually one more difference: In the failing case, `/var/lib/logrotate/logrotate.status.tmp` is successfully unlinked before it is created.  logrotate does it to cleanup in case the previous run of logrotate was interrupted unexpectedly.  But this may also happen when you run two processes of logrotate in parallel.

**Comment by peterjanes** [comment]
Aha, you're right: somehow `run-parts` is being triggered twice every hour, which is triggering the logrotate job. (I usually look at the logs with a journalctl output mode that hides the PIDs, so I didn't see that there were two.) Thanks for identifying the problem, and apologies for the distraction!

**Comment by kdudka** [comment]
No problem.  Thanks for confirmation!

**Comment by YouveGotMeowxy** [comment]
Sorry for the necropost, but what is the actual solution to this? I have the same error.

**Comment by kdudka** [comment]
@YouveGotMeowxy Which version of logrotate are you using?  State file locking was introduced in `logrotate-3.17.0`.

**Comment by YouveGotMeowxy** [comment]
> @YouveGotMeowxy Which version of logrotate are you using? State file locking was introduced in `logrotate-3.17.0`.

oh wow. Looks like I'm way behind. Looks like I'm using 1.3(!) lol. I'm using the `:latest` tag from heer: https://hub.docker.com/r/blacklabelops/logrotate

**Comment by kdudka** [comment]
There is `ARG LOGROTATE_VERSION=latest` in the `Dockerfile`: https://github.com/blacklabelops/logrotate/blob/bb989e5808a610d3c1da9ccbfc638cc07afb1c37/Dockerfile#L4 so just rebuilding the image might help.

**Comment by kdudka** [comment]
In any case, we as logrotate upstream developers do not maintain the images.  Upstream releases of logrotate are available here: https://github.com/logrotate/logrotate/releases
