### ISSUE TITLE
logrotate: race condition when creating new log file

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#216]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=400198:

```
Hi,

when a new log file is created, it is first created, and then chowned
and chmodded to the desired values. There is a small time window where
the file exists, but does not have the correct owner/mode.

If an application decides to access the file within that time window,
it might fail. This is a probable cause for #399930.

While this can be worked around in exim, it probably cannot in other
applications, which makes this a logrotate issue. Logrotate should
make sure that the file does only appear under the target name when it
already has the correct owner/mode, and it should also cater for the
case that the application itself has already taken care of creating
the new file.

Greetings
Marc
```

Is this situation to be considered harmless or is a patch, which creates a temporary file, then sets the correct ownership and permissions and then renames it into place, welcome?

**Comment by kdudka** [comment]
I looked at the Debian bug report and there seem to be more questions than answers.  So does exim create the logfile in case it does not exist or not?

- If yes, then just use `nocreate` and everything will work as expected.

- If no, then the proposed solution is not going to help.  You would just end up with `ENOENT` instead of `EPERM` when exim tried to open the log file during the critical time period.

**Comment by cgzones** [comment]
What I gathered together is, yes, exim does create the logfile if it does not exist. (So in this case `nocreate` should fix it).

My question was more theoretical, if the current behavior might (under rare circumstances) cause issues and if it is worth fixing it.

**Comment by whotwagner** [comment]
I believe that the problem isn't that theoretical. I think it might be worth to make the time window smaller because I was able to win the race condition in my environment. See https://tech.feedyourhead.at/content/abusing-a-race-condition-in-logrotate-to-elevate-privileges

**Comment by kdudka** [comment]
> "when a new log file is created, it is first created, and then chowned
> and chmodded to the desired values. There is a small time window where
> the file exists, but does not have the correct owner/mode"

@whotwagner Could you please explain how one can abuse **this** race condition?

The Debian bug report was about an inverse problem.  The file created by logrotate's `create` directive was first created with too strict permissions and the permissions were relaxed with some delay.  Consequently, the daemon trying to write to that log file in the critical period of time ended up with `EPERM`.

If you look at the code of `createOutputFile()`, it operates on a file descriptor:

https://github.com/logrotate/logrotate/blob/7fae5f2bba0f20893394630d42ea196a4ff6df21/logrotate.c#L477

So it should be resistant to the timed symlink attacks.  Of course, insecure configurations of logrotate exist but I do not think it is related to **this** issue.  If you have any idea on how to improve logrotate to be more secure (reject vulnerable configurations etc.), please open a separate pull request for it.

**Comment by whotwagner** [comment]
True. The debian report specifies a race cond. after the open() in createOutputFile(). The one I have found happens before the open(). I created a pull-request()..
