### ISSUE TITLE
logrotate exits with success even in case of errors

### ISSUE THREAD

**Issue by davide125** [logrotate/logrotate#22]
Logrotate will exit with 0 even when it failed to rotate because of an error (e.g. invalid config file). In this case it should exit with 1 or some more specific exit code, but definitely not success. Repro example:

```
# cat logrotate.conf 
weekly
rotate 4
create
dateext
/var/log/wtmp {
    monthly
    create 0664 root utmp
    minsize 1M
    rotate 1
}
/var/log/wtmp {
    daily
    create 0664 root utmp
    minsize 1M
    rotate 1
}
# /usr/sbin/logrotate logrotate.conf
error: logrotate.conf:22 duplicate log entry for /var/log/wtmp
# echo $?
0
# logrotate --version
logrotate 3.9.2
```

**Comment by hanzz** [comment]
Logrotate should return 1 for most errors. For this particular one, logrotate still tries to rotate the file according to the first rotation defition and therefore it is not considered to be a fatal error, so it just prints error message, but continues with rotation and exits with 0.

The error message could be probably changed to warning or something like that, so it would be clear the rotation still continues.

**Comment by gdubicki** [comment]
It's a good idea to change the message from error to warning. "error" is misleading.

**Comment by kdudka** [comment]
@gdubicki Which version of logrotate are you using?

I believe that the latest release of logrotate includes two fixes, which are closely related:
1. it propagates the error codes while reading the configuration: 6a75cdeab61a29ea99d49a85461f597c1d8d055c
2. it recovers from errors while reading the configuration: 56598fd1e9338b45ba3e1bda1b91522e75b40e06 and 74b788f790990d5958314df5f908a6fc5eaeccdd

**Comment by kdudka** [comment]
The original example now returns non-zero exit code, so I close this as fixed.  Please report separate issues if anything else is needed.
