### ISSUE TITLE
Public helm chart for logrotate

### ISSUE THREAD

**Issue by ahsan-storm** [logrotate/logrotate#231]
Right now I can not find a public helm chart for logrotate. Can you guys please create one? If required I can do that too.

**Comment by ahsan-storm** [comment]
@kdudka @kerolasa @glensc

**Comment by ahsan-storm** [comment]
okay cool, I'll create one. Closing the issue.

**Comment by ahsan-storm** [comment]
I've created a Pull request for logrotate in official helm charts repo. It can be followed here: 
https://github.com/helm/charts/pull/10102
As soon as the PR will be merged, logrotate public helm chart will be available. Anyone interested can follow the PR

**Comment by kdudka** [comment]
Cool.  Thanks for sharing!
