### ISSUE TITLE
logrotate hung_task_timeout_secs issue

### ISSUE THREAD

**Issue by amirkhonov** [logrotate/logrotate#232]
Hello!
I get an error of logrotate 3.8.6 on dmesg periodically:
> Linux 4.16.2-1.el7.elrepo.x86_64 #1 SMP Thu Apr 12 09:08:05 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

> [Wed Dec 19 03:36:07 2018] INFO: task logrotate:17344 blocked for more than 120 seconds.
> [Wed Dec 19 03:36:07 2018]       Not tainted 4.16.2-1.el7.elrepo.x86_64 #1
> [Wed Dec 19 03:36:07 2018] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [Wed Dec 19 03:36:07 2018] logrotate       D    0 17344  17342 0x00000080
> [Wed Dec 19 03:36:07 2018] Call Trace:
> [Wed Dec 19 03:36:07 2018]  __schedule+0x293/0x8a0
> [Wed Dec 19 03:36:07 2018]  schedule+0x36/0x80
> [Wed Dec 19 03:36:07 2018]  jbd2_log_wait_commit+0x98/0x120 [jbd2]
> [Wed Dec 19 03:36:07 2018]  ? remove_wait_queue+0x60/0x60
> [Wed Dec 19 03:36:07 2018]  jbd2_complete_transaction+0x57/0x90 [jbd2]
> [Wed Dec 19 03:36:07 2018]  ext4_sync_file+0x1ef/0x370 [ext4]
> [Wed Dec 19 03:36:07 2018]  vfs_fsync_range+0x43/0xb0
> [Wed Dec 19 03:36:07 2018]  do_fsync+0x3d/0x70
> [Wed Dec 19 03:36:07 2018]  SyS_fsync+0x10/0x20
> [Wed Dec 19 03:36:07 2018]  do_syscall_64+0x79/0x1b0
> [Wed Dec 19 03:36:07 2018]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
> [Wed Dec 19 03:36:07 2018] RIP: 0033:0x7fb78036ee00
> [Wed Dec 19 03:36:07 2018] RSP: 002b:00007ffe7e85e088 EFLAGS: 00000246 ORIG_RAX: 000000000000004a
> [Wed Dec 19 03:36:07 2018] RAX: ffffffffffffffda RBX: 000000000195a000 RCX: 00007fb78036ee00
> [Wed Dec 19 03:36:07 2018] RDX: 0000000000000000 RSI: 00007ffe7e85e104 RDI: 0000000000000004
> [Wed Dec 19 03:36:07 2018] RBP: 00007ffe7e85e160 R08: 0000000000000000 R09: 00000000000043c0
> [Wed Dec 19 03:36:07 2018] R10: 0000000000000000 R11: 0000000000000246 R12: 00007ffe7e85e090
> [Wed Dec 19 03:36:07 2018] R13: 0000000000000003 R14: 0000000001957920 R15: 0000000000000004

Please help resolve this problem.

**Comment by kdudka** [comment]
This could hardly be a bug of logrotate.  It is just kernel telling you that an I/O operation takes longer than 120 seconds.  It could be caused by a buggy driver loaded into kernel, corrupted file system, dying hard drive, etc.

**Comment by kdudka** [comment]
Forgot to mention, excessive I/O load on the system (or the host system in case of VM) as a possible cause.
