### ISSUE TITLE
Not working option compressext

### ISSUE THREAD

**Issue by click0** [logrotate/logrotate#233]
My system:
`FreeBSD 12.0-STABLE r342185 `

```
# logrotate --version
logrotate 3.13.0

    Default mail command:       /usr/bin/mailx
    Default compress command:   /usr/bin/bzip2
    Default uncompress command: /usr/bin/bunzip2
    Default compress extension: .gz
    Default state file path:    /var/run/logrotate.status
    ACL support:                no
    SELinux support:            no

```

Overriding the option compressext (compress_ext) through the logrotate.conf config does not work. Create archives with the .gz extension. 

```
# file domain.com.access.log.2.gz
domain.com.access.log.2.gz: bzip2 compressed data, block size = 900k
```

```
# cat /usr/local/etc/logrotate.conf
...
compresscmd /usr/bin/bzip2
uncompresscmd /usr/bin/bunzip2
compressoptions -9
#compressext .bz2
compressext .kjgfhds2
```
```
# logrotate -dv /usr/local/etc/logrotate.conf
reading config file /usr/local/etc/logrotate.conf
including /usr/local/etc/logrotate.d
reading config file nginx.conf
reading config file php-fpm.conf
compress_prog is now /usr/bin/bzip2
compress_ext was changed to .bz2
uncompress_prog is now /usr/bin/bunzip2
compress_options is now  -9
compress_ext is now .kjgfhds2
Reading state from file: /var/run/logrotate.status
Allocating hash table for state file, size 64 entries
...
```

**Comment by kdudka** [comment]
I am not able to reproduce the bug with upstream `logrotate-3.13.0`.  Please provide self-contained steps to reproduce and full verbose output of logrotate.  Note that logrotate will not change extension on the files that have already been compressed.

**Comment by click0** [comment]
It is a pity that your testing is so poorly organized.
You have to fork for FreeBSD and place it in the official repository (ports).

**Comment by kdudka** [comment]
This is an upstream bug tracker.  logrotate's upstream is independent of any BSD distribution.  I am not sure what you mean by poorly organized testing.  We use, for example, continuous integration on the Travis CI service: https://travis-ci.org/logrotate/logrotate and it is all green.  We are open to improvement proposals though...
