### ISSUE TITLE
Exit code 1, no errors in -d 

### ISSUE THREAD

**Issue by goldencut** [logrotate/logrotate#238]
Was updating Logrotate configs with Ansible on multiple servers and noticed exit codes >0 on some when task ran 'logrotate -f /etc/logrotate.conf':
`TASK [logrotate : Reload conf] ****************************************************************************************
fatal: [myserver.com]: FAILED! => {"changed": true, "cmd": ["logrotate", "-f", "/etc/logrotate.conf"], "delta": "0:00:06.372079", "end": "2019-02-06 15:55:18.817965", "msg": "non-zero return code", "rc": 1, "start": "2019-02-06 15:55:12.445886", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}`

When I run on server: 
`root@myserver.com:~# logrotate -f /etc/logrotate.conf || echo "notOK"`
`notOK`
`root@myserver.com:~# logrotate -f /etc/logrotate.conf ; echo $?`
`1`

But I get no errors when I run:
`logrotate -d /etc/logrotate.conf 2> out.txt && grep -i error out.txt`

Is this by design somehow, am I missing something?

BR,
G.

**Comment by kdudka** [comment]
`logrotate -d` does nothing, only debug messages are printed.  You need to use `logrotate -v` to get verbose output of logrotate that actually does something.

**Comment by goldencut** [comment]
Thanks. 
I ran: 
`logrotate -v -f /etc/logrotate.conf 2> out.txt; grep -i error out.txt` 
No errors.
On what conditions does logrotate set exit code to 1? I assumed 'already exists, skipping rotation' shouldn't cause that.

**Comment by kdudka** [comment]
It is not clear which version of logrotate you are using, neither how logrotate's configuration looks like.  Nevertheless, the general answer is yes, this may happen.  See the source code:

https://github.com/logrotate/logrotate/blob/7fae5f2bba0f20893394630d42ea196a4ff6df21/logrotate.c#L1833

**Comment by goldencut** [comment]
I got my answers, IIUC there were improvements made to code... who closes the ticket? 

PS. very minimal logrotate conf, v.3.8.7 (latest for Debian 8)

**Comment by kdudka** [comment]
Glad to see it resolved, closing...

Note that `logrotate-3.8.7` was released more than 5 years ago.  Unless Debian provides support for the very old release, you will need to upgrade it to a more recent version (`logrotate-3.15.0` was released in December 2018).
