### ISSUE TITLE
docs request - nested config example

### ISSUE THREAD

**Issue by bby-bishopclark** [logrotate/logrotate#243]
at http://lists.linuxfromscratch.org/pipermail/blfs-dev/2014-August/027906.html , user akhiezer teases

> Note that logrotate can have nested, hierarchical definitions/contexts
in the cfg file, with deeper-nested definitions taking precedence: so you
can use e.g. 'nomail' globally, but override it for a sub-section.

.. and if it's true, I'd love to see some examples.  While I could normally interpret akhiezer's remarks as being the base/default rules and a single deeper level based on a /log/file{} stanza, he does talk about 'deeper-nested' definitions.

I dug through the config.c parser code for a bit, but couldn't pick out what I'm sure must be straight-forward code to show whether (deeper) nesting is allowed.  

This, though, didn't work:

````
/var/log/boot*g
{
  /var/log/boot.log
  {
    something
  }
}
````

Is that the nail in the coffin?  Did akhiezer mis-speak?

**Comment by kdudka** [comment]
logrotate does not support this kind of nesting.  Each configuration file can set global options and local (per log specific) options.  Local options override global ones, and later options override earlier ones.  All local options are at the same level.  I believe that the documentation (including the examples) is pretty clear in this.

**Comment by bby-bishopclark** [comment]
Great!  The docs I have must have been old, and weren't clear on this at all.

Thanks!
