### ISSUE TITLE
Scripts don't get log paths passed to them

### ISSUE THREAD

**Issue by he32** [logrotate/logrotate#244]
Yes, this is apparently a duplicate of issue #7.

However, I disagree with the conclusion in that issue, the issue is real.
There are actually two bugs in the `runScript()` function:

 * "sh -c ./script a b c" does *not* cause the "a b c" arguments to be passed
   to the script(!)
 * once that is fixed, it turns out the "logrotate_script" argument in `execl()`
   ends up as arg1 (not arg0!) of the script, and that behaviour is not documented
   anywhere I can see.

The following session demonstrates the issue:
```
$ cat t.c
#include <unistd.h>

int
main(int argc, char **argv)
{
        execl("/bin/sh", "sh", "-c",
                "./echoargs", "testscript", "a", "b", (char*)NULL);
}
$ cat echoargs
#! /bin/sh

echo "$@"

for arg; do
        echo $arg
done

echo "$1"
$ cc t.c
$ ./a.out


$ ed t.c
142
/exec/
        execl("/bin/sh", "sh", "-c", 
s/ "-c",//p
        execl("/bin/sh", "sh", 
w
136
q
$ cc t.c
$ ./a.out
testscript a b
testscript
a
b
testscript
$
```

I have a pull request lined up which will fix this issue, and I'll refer to this from there.

**Comment by kdudka** [comment]
Sorry but this is really misunderstanding on your side.  `sh -c` expects shell **commands** to be executed, not a name of the file script.  `./echoargs` is an external command in shell's syntax.  It is your responsibility to pass any arguments to the external command, e.g. by using `./echoargs "$@"` instead.
