### ISSUE TITLE
Why logrotate deletes my old archive created with dateext + gzip

### ISSUE THREAD

**Issue by icy** [logrotate/logrotate#246]
Hello everyone,

I have a logrotate.conf as seen in https://gist.github.com/icy/ab980e683ef61a790bf1a8fbd7b09789 . There are two files, `/etc/logrotate.conf` and the nginx configuration `/etc/logrotate.d/nginx`. The purpose of the `nginx` script is to create date-based archive of logs in `/var/log/nginx/`.

I notice that all `*.gz` files in `/var/log/nginx` are deleted if they are older than **4 days**. This is weird, am I missing something? Which configuration flags to disable this feature?

Thanks a lot.

**Comment by icy** [comment]
I post here `nginx` configuration for quick reference

```
/var/log/nginx/*log {
        daily
        dateext
        missingok
        notifempty
        create 640 http log
        sharedscripts
        compress
        delaycompress
        postrotate
                # mv /var/log/nginx/*.gz /var/log/nginx/archives/ -iv || true
                test ! -r /run/nginx.pid || kill -USR1 `cat /run/nginx.pid`
        endscript
}
```

**Comment by icy** [comment]
Today is 22, and all archives before 19 are gone. This is what I have now

```
-rw-r----- 1 http log       118101 Mar 19 06:59 error.log-20190319.gz
-rw-r----- 1 http log      1108386 Mar 19 06:59 acces.log-20190319.gz
-rw-r----- 1 http log       143078 Mar 20 06:59 error.log-20190320.gz
-rw-r----- 1 http log      1577308 Mar 20 06:59 acces.log-20190320.gz
-rw-r----- 1 http log       126511 Mar 21 00:00 error.log-20190321.gz
-rw-r----- 1 http log      1269990 Mar 21 00:00 acces.log-20190321.gz
```

**Comment by icy** [comment]
I guess that's because the option `rotate 4` in the global configuration file https://gist.github.com/icy/ab980e683ef61a790bf1a8fbd7b09789#file-gistfile1-txt-L25 .

**Comment by icy** [comment]
The weird thing is that for the same configuration, we lost logs from 27/11/2018 . All logs before 27/11/2018  are still remained. :)

**Comment by kdudka** [comment]
Yes, when using `daily` together with `rotate 4`, the rotated logs are kept for the last 4 days only.
