### ISSUE TITLE
Fails to rotate if a date is in the future in status file.

### ISSUE THREAD

**Issue by vgat** [logrotate/logrotate#247]
Running 3.11.0, but I didn't see any fixes to this in the later versions. 

Getting this error:
 error: bad year 2108 for file /var/log/nginx/error.log in state file /var/lib/logrotate/status

A single typo and now we're unable to force rotate logs automatically without intervention.

**Comment by kdudka** [comment]
I believe that the mentioned behavior of logrotate was improved by commit b9d82003002c98370e4131a7e43c76afcd23306a which landed after the 3.11.0 release.  Could you please upgrade logrotate to 3.12.0 (or newer) and retest?
