### ISSUE TITLE
Logrotate doesn't seem to support multiple wildcard anymore

### ISSUE THREAD

**Issue by cjeanner** [logrotate/logrotate#251]
Hello,

We're using logrotate on Red Hat Enterprise Linux 8, with the following configuration file:
```
/var/log/containers/*/*log {
  daily
  rotate 14
  maxage 14
  # minsize 1 is required for GDPR compliance, all files in
  # /var/log/containers not managed with logrotate will be purged!
  minsize 1
  # Do not use size as it's not compatible with time-based rotation rules
  # required for GDPR compliance.
  maxsize 10M
  missingok
  notifempty
  copytruncate
  delaycompress
  compress
}
```

We run logrotate from a cron job, with the following command:
```
/usr/sbin/logrotate -s /var/lib/logrotate/logrotate-crond.status /etc/logrotate-crond.conf
```
Here's the result of a "-v" run:
```
reading config file /etc/logrotate-crond.conf
Reading state from file: /var/lib/logrotate/logrotate-crond.status
Allocating hash table for state file, size 64 entries

Handling 1 logs

rotating pattern: /var/log/containers/*/*.log  after 1 days (14 rotations)
empty log files are not rotated, only log files >= 1 bytes are rotated, log files >= 10485760 are rotated earlier, old logs are removed
No logs found. Rotation not needed.
```

We do have a file matching the criteria, located in /var/log/containers/nova/ directory:
-rw-r--r--. 1 nova nova 275M Jun 20 11:43 nova-placement-api-test.log
Its size is good for a rotation due to the "maxsize 10M".

The status file doesn't list any file, meaning it didn't find anything:
```
cat /var/lib/logrotate/logrotate-crond.status
logrotate state -- version 2
```

If we replace the path set in the configuration file with a single-level wildcard, for instance
```/var/log/containers/nova/*log```
it does find the logs and does the rotation as expected, meaning the configuration itself is apparently working - there's "just" the wildcard issue...

Here are the information about logrotate version:
```
logrotate 3.14.0

    Default mail command:       /bin/mail
    Default compress command:   /bin/gzip
    Default uncompress command: /bin/gunzip
    Default compress extension: .gz
    Default state file path:    /var/lib/logrotate/logrotate.status
    ACL support:                yes
    SELinux support:            yes
```

Care to investigate a bit and provide some help?

Thank you!

Cheers,

C.

**Comment by kdudka** [comment]
I tried multiple wildcard match with logrotate on Red Hat Enterprise Linux 8 and it worked just fine:
```
root@el8 ~ # rpm -q logrotate                         
logrotate-3.14.0-3.el8.x86_64
root@el8 ~ # mkdir -p /var/log/containers/nova        
root@el8 ~ # touch /var/log/containers/nova/xxx.log
root@el8 ~ # cat > lr.conf
/var/log/containers/*/*.log {
    rotate 14
}
root@el8 ~ # logrotate -vf lr.conf -s lr.stat
reading config file lr.conf
Reading state from file: lr.stat
Allocating hash table for state file, size 64 entries

Handling 1 logs

rotating pattern: /var/log/containers/*/*.log  forced from command line (14 rotations)
empty log files are rotated, old logs are removed
considering log /var/log/containers/nova/xxx.log
Creating new state
  Now: 2019-06-20 15:46
  Last rotated at 2019-06-20 15:00
  log needs rotating
rotating log /var/log/containers/nova/xxx.log, log->rotateCount is 14
dateext suffix '-20190620'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
set default create context to unconfined_u:object_r:var_log_t:s0
renaming /var/log/containers/nova/xxx.log.14 to /var/log/containers/nova/xxx.log.15 (rotatecount 14, logstart 1, i 14), 
old log /var/log/containers/nova/xxx.log.14 does not exist
renaming /var/log/containers/nova/xxx.log.13 to /var/log/containers/nova/xxx.log.14 (rotatecount 14, logstart 1, i 13), 
old log /var/log/containers/nova/xxx.log.13 does not exist
renaming /var/log/containers/nova/xxx.log.12 to /var/log/containers/nova/xxx.log.13 (rotatecount 14, logstart 1, i 12), 
old log /var/log/containers/nova/xxx.log.12 does not exist
renaming /var/log/containers/nova/xxx.log.11 to /var/log/containers/nova/xxx.log.12 (rotatecount 14, logstart 1, i 11), 
old log /var/log/containers/nova/xxx.log.11 does not exist
renaming /var/log/containers/nova/xxx.log.10 to /var/log/containers/nova/xxx.log.11 (rotatecount 14, logstart 1, i 10), 
old log /var/log/containers/nova/xxx.log.10 does not exist
renaming /var/log/containers/nova/xxx.log.9 to /var/log/containers/nova/xxx.log.10 (rotatecount 14, logstart 1, i 9), 
old log /var/log/containers/nova/xxx.log.9 does not exist
renaming /var/log/containers/nova/xxx.log.8 to /var/log/containers/nova/xxx.log.9 (rotatecount 14, logstart 1, i 8), 
old log /var/log/containers/nova/xxx.log.8 does not exist
renaming /var/log/containers/nova/xxx.log.7 to /var/log/containers/nova/xxx.log.8 (rotatecount 14, logstart 1, i 7), 
old log /var/log/containers/nova/xxx.log.7 does not exist
renaming /var/log/containers/nova/xxx.log.6 to /var/log/containers/nova/xxx.log.7 (rotatecount 14, logstart 1, i 6), 
old log /var/log/containers/nova/xxx.log.6 does not exist
renaming /var/log/containers/nova/xxx.log.5 to /var/log/containers/nova/xxx.log.6 (rotatecount 14, logstart 1, i 5), 
old log /var/log/containers/nova/xxx.log.5 does not exist
renaming /var/log/containers/nova/xxx.log.4 to /var/log/containers/nova/xxx.log.5 (rotatecount 14, logstart 1, i 4), 
old log /var/log/containers/nova/xxx.log.4 does not exist
renaming /var/log/containers/nova/xxx.log.3 to /var/log/containers/nova/xxx.log.4 (rotatecount 14, logstart 1, i 3), 
old log /var/log/containers/nova/xxx.log.3 does not exist
renaming /var/log/containers/nova/xxx.log.2 to /var/log/containers/nova/xxx.log.3 (rotatecount 14, logstart 1, i 2), 
old log /var/log/containers/nova/xxx.log.2 does not exist
renaming /var/log/containers/nova/xxx.log.1 to /var/log/containers/nova/xxx.log.2 (rotatecount 14, logstart 1, i 1), 
old log /var/log/containers/nova/xxx.log.1 does not exist
renaming /var/log/containers/nova/xxx.log.0 to /var/log/containers/nova/xxx.log.1 (rotatecount 14, logstart 1, i 0), 
old log /var/log/containers/nova/xxx.log.0 does not exist
log /var/log/containers/nova/xxx.log.15 doesn't exist -- won't try to dispose of it
set default create context to unconfined_u:object_r:var_log_t:s0
renaming /var/log/containers/nova/xxx.log to /var/log/containers/nova/xxx.log.1
set default create context to unconfined_u:object_r:admin_home_t:s0
```

Please provide self-contained steps to reproduce the issue.

**Comment by cjeanner** [comment]
Hello @kdudka 

Thank you for your answer. Here are some more information:
logrotate is running within a container (podman engine) and the /var/log/containers base is a bind-mount from the host.
I didn't test directly from the host, but indeed, there's apparently a difference in the way logrotate lists files when launched from within a container :/.

Unfortunately I can't point you directly to the RHEL8 container, since it's private :(. Basically, taking a RHEL8 container image and running it with the following should do:
```Bash
$container_cli run -ti -v /var/log/containers:/var/log/containers:rw,z CONTAINER_IMAGE bash
```
Just copy the logrotate config and you should be good.

Lemme know if you can manage to test that, else I might provide a tmate on my env so that you can run tests directly.

Cheers,

C.

**Comment by kdudka** [comment]
Sorry, it is not my job to debug some containers.  If it is a problem of logrotate, it will manifest without using any containers.  If a bind mount is necessary to trigger the problem, you can try to create a bind mount using `mount --bind src dst`.  The burden is on you to show us that logrotate does something wrong.

**Comment by cjeanner** [comment]
Hello,
Small update:
bind-mount does work on the host.

This means the issue is located in the container. Is there any way to get some debug?
The ```-d``` and ```-v``` flags don't really help understanding why logrotate fails to see files while ```ls /var/log/containers/*/*.log``` does work, since they are apparently using the same glob() method :/. I'll try with some strace and other friends in order to get more info about that behaviour.

Cheers,

C.

**Comment by kdudka** [comment]
logrotate does not implement the file globbing by itself.  It dynamically links the `libpopt` library that implements it.  You could try to preload your own build of `libpopt` to debug it.

**Comment by cjeanner** [comment]
Me again,
a colleague found the issue: a broken symlink is present in /var/log/containers, and it seems to break the recursive look-up for some reason.

This can be tested as well from outside of a container:

- create a symlink pointing to non-existing location
- run logrotate against the parent directory with said patterns

I can update the issue title to reflect that, but I think I've seen such an issue already open.. ?

Cheers,

C.

**Comment by kdudka** [comment]
I have not tested it yet but what you describe could hardly be an issue of logrotate itself.  This needs to be debugged and fixed in `libpopt`.

**Comment by cjeanner** [comment]
do you know where I can report it against libpopt? apparently it's a "common" name for other things, even for maths stuff :/.

**Comment by kdudka** [comment]
It used to be popt-devel@rpm5.org and http://rpm5.org/files/popt but the domain does not seem to exist any more:
```
% curl http://rpm5.org/files/popt
curl: (6) Could not resolve host: rpm5.org
```

**Comment by cjeanner** [comment]
erf... is it still maintained then? Apparently rpm5.org is dead for good, no NS record... 

Anyway, on our side we have a workaround for that nasty issue (drop the symlink) - might be good to point that in a FAQ associated with logrotate project, just to point this limitation.

In any cases, you can probably close this issue.

Thank you for your support!

**Comment by glensc** [comment]
I think it's better you report the popt bug to your distribution bugtracker (and link here for others to follow).

**Comment by cjeanner** [comment]
Hello,
Just opened a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1723265) at Red Hat, we'll see how it comes.
I therefore close this issue since it's not a logrotate failure.

Thank you!

**Comment by pmatilai** [comment]
> logrotate does not implement the file globbing by itself. It dynamically links the `libpopt` library that implements it. You could try to preload your own build of `libpopt` to debug it.

Um. popt is an option parser and the only globbing it does is to find its own config files, and does not export any globbing functionality to others AFAIK. What exactly are you referring to here?

**Comment by pmatilai** [comment]
Oh and FWIW, some 15+ years ago *glibc* introduced a controversial change where glob() no longer matched on broken symlinks, breaking various software (think 'rm *' for example, and rpm was also affected). That change was finally reverted couple of years ago (see https://sourceware.org/bugzilla/show_bug.cgi?id=866), maybe that's what logrotate is running into?

**Comment by kdudka** [comment]
As pointed out by @pmatilai this is indeed a bug of logrotate.  Reopening...
