### ISSUE TITLE
Potential issue with copytruncate when file descriptor is in use

### ISSUE THREAD

**Issue by Nessworthy** [logrotate/logrotate#252]
logrotate v3.7.8 (via. AWS package mirror)

I have to preface this by saying I've not been able to directly replicate this issue, just that it's occasionally occurring across multiple separate applications. These applications exist on AWS as elastic beanstalk environments using docker as the platform. I'm not sure if logrotate may not be at fault, but I'm just trying to eliminate possibilities.

These instances use a service which streams docker logs to log files named after their container ID. e.g. `/var/log/eb-docker/containers/eb-current-app/abcdef123456-stdouterr.log`
The service does this by literally just running the command `docker logs -f [container ID] >> /var/log/eb-docker/containers/eb-current-app/[container ID]-stdouterr.log 2>&1`

These logs have a logrotate script ran hourly on them via. cron:

```
/var/log/eb-docker/containers/eb-current-app/* {
size 10M
rotate 5
missingok
compress
notifempty
copytruncate
dateext
dateformat %s
olddir /var/log/eb-docker/containers/eb-current-app/rotated
}
```

This is the only configuration set to affect the log files in this folder. The script is executed from a one liner in `/etc/cron.hourly` which is simply a `logrotate` call followed by the direct path to that specific configuration file. Nothing else is included. Are there any defaults that I may not know about?

Rarely, I'm seeing an issue where this log has been rotated oddly and deleted. The docker log service knows nothing different, because it still holds on to the file descriptor of the deleted file (which is causing issues downstream).

`lsof ` yields this:

```
docker    23784     root    1w      REG              202,1   2729599     397555 /var/log/eb-docker/containers/eb-current-app/abcdef123456-stdouterr.log.1 (deleted)
docker    23784     root    2w      REG              202,1   2729599     397555 /var/log/eb-docker/containers/eb-current-app/abcdef123456-stdouterr.log.1 (deleted)
```

Note the `.1` at the end of the file, and how it isn't in the `rotated` directory like the config would suggest. Also note that the size of the file is less than the 10M in the configured script.

The only link that I have that logrotate is causing this, is that the date in logrotate's status file for the log is consistently the same as when the downstream issues start occuring - I'm 3 for 3 so far on instances I've been investigating.

Trying to skim through the source code showed nothing weird, but I don't know enough conclusively rule out or narrow it down to logrotate. For example, I see the copyTruncate function literally opens a new file and copies the content over, but that's not what I'm seeing when this issue occurs. Does it do anything prior to copytruncate that involves renaming, then naming it back? I saw there were issues resolved in later versions involving different devices, but all of this happens on the same machine in the same mount. There's also plenty of space.

I've tested after just by creating a 20Mb file and rotating that using the script, and that has worked without issue each time. Even forcing with a lower size is fine. Verbose / debug modes show nothing out of the ordinary either. I'm leaning towards a very specific set of conditions causes this, but I have no actual logs of when it happens (yet), nor what exactly is causing it.

I appreciate that it isn't a lot to go off, but I hope this might spark something that someone has dealt with before.

**Comment by kdudka** [comment]
As far as I know, `copytruncate` never renames or unlinks the original log files.  It only renames or unlinks the already rotated (copies of) the log files.  Looking at your configuration, those two sets of files should be well isolated from each other thanks to `dateext` and `olddir`.

**Comment by Nessworthy** [comment]
Thanks for the reply!

Yeah, I've been going out of my mind trying to figure out what's going on here.
I spent yesterday going out of my mind trying to figure this out, but I think I might have found the root cause. There's a misconfigured rotate file pointing at the same location, with the same settings, except the size is "50m" instead of "10M".

On the off chance, I've just ran the same tests, but using this file. I'd previously ignored this file because full logrotate tests were telling me that it was erroring, so I presumed that logrotate would just ignore the block.

However, this is the output I got:

```
reading config file /etc/logrotate.elasticbeanstalk.hourly/logrotate.elasticbeanstalk.containers.conf
reading config info for /var/log/eb-docker/containers/eb-current-app/*
error: /etc/logrotate.elasticbeanstalk.hourly/logrotate.elasticbeanstalk.containers.conf:2 unknown unit 'm'
error: found error in /var/log/eb-docker/containers/eb-current-app/* , skipping
removing last 1 log configs

Handling 1 logs

rotating pattern: /var/log/eb-docker/containers/eb-current-app/*  1048576 bytes (no old logs will be kept)
empty log files are rotated, old logs are removed
*** (a lot of "log does not need rotating" from other logs) ***
considering log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log
  log needs rotating
rotating log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log, log->rotateCount is 0
dateext suffix '-20190620'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
renaming /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1 to /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.2 (rotatecount 1, logstart 1, i 1),
old log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1 does not exist
renaming /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.0 to /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1 (rotatecount 1, logstart 1, i 0),
old log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.0 does not exist
log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.2 doesn't exist -- won't try to dispose of it
renaming /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log to /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1
disposeName will be /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1
removing old log /var/log/eb-docker/containers/eb-current-app/eb-foo-stdouterr.log.1
```

Which is exactly what is happening with the affected files.
I think a facedesk is in order. Would you be able to explain why it would act this way? Naturally this is my fault for missing a misconfigured near-duplicate file, but I'm still a bit confused as to why it continues to process the rotation!

**Comment by kdudka** [comment]
It has been requested many times that logrotate should continue with rotatation even if there is a non-fatal error in its configuration, because people often ended up in the "no space left on device" state after logrotate's configuration was silently broken by an automatic update of something.

Anyway, it is cool that you were able to find the root cause in the end!

**Comment by Nessworthy** [comment]
No worries, thanks for clearing that up for me! :)
