### ISSUE TITLE
Clashing log entries cause inconsistent rotating behaviour

### ISSUE THREAD

**Issue by the-allanc** [logrotate/logrotate#259]
Took me a while to debug what was going on here. The issue I'm having can be described as this:

1. Define one rule which uses a more specific wildcard.
1. Define another rule which uses a general wildcard.
1. logrotate behaves inconsistently when processing the general wildcard rule.

Here's an example of the problem I'm seeing:

Logs to rotate:
```
allanc@ng-stage:~$ ls logs/
a.log  b.log  c1.log  c2.log  d.log  e.log
```

Configuration:
```
allanc@ng-stage:~$ cat /etc/logrotate.conf 
weekly
rotate 4
create

/home/allanc/logs/c*.log {
   rotate 8
   missingok
   daily
}

/home/allanc/logs/*.log {
   rotate 8
   missingok
   daily
}
```

Invocation:
```
allanc@ng-stage:~$ ./logrotate-3.15.0/logrotate -d /etc/logrotate.conf 
WARNING: logrotate in debug mode does nothing except printing debug messages!  Consider using verbose mode (-v) instead if this is not what you want.

reading config file /etc/logrotate.conf
warning: 'daily' overrides previously specified 'weekly'
error: /etc/logrotate.conf:11 duplicate log entry for /home/allanc/logs/c1.log
Reading state from file: /var/lib/logrotate.status
Allocating hash table for state file, size 64 entries

Handling 2 logs

rotating pattern: /home/allanc/logs/c*.log  after 1 days (8 rotations)
empty log files are rotated, old logs are removed
considering log /home/allanc/logs/c1.log
Creating new state
  Now: 2019-08-29 16:23
  Last rotated at 2019-08-29 16:00
  log does not need rotating (log has been already rotated)
considering log /home/allanc/logs/c2.log
Creating new state
  Now: 2019-08-29 16:23
  Last rotated at 2019-08-29 16:00
  log does not need rotating (log has been already rotated)

rotating pattern: /home/allanc/logs/*.log  after 1 days (8 rotations)
empty log files are rotated, old logs are removed
considering log /home/allanc/logs/a.log
Creating new state
  Now: 2019-08-29 16:23
  Last rotated at 2019-08-29 16:00
  log does not need rotating (log has been already rotated)
considering log /home/allanc/logs/b.log
Creating new state
  Now: 2019-08-29 16:23
  Last rotated at 2019-08-29 16:00
  log does not need rotating (log has been already rotated)
```

Logs that are named `c*.log` are processed by the first rule.
Logs that are named alphabetically earlier than `c1.log` **are** rotated by the second rule.
Logs that are named alphabetically after `c2.log` **are not** rotated by the second rule.

The confusion here is that the second rule is applied inconsistently - it seems logrotate starts processing files in named order, starts with the first two files (`a.log`, `b.log`) and when it reaches the first file that clashes (`c1.log`), it stops processing the remaining files.

Ideally, logrotate would ignore the log files it had already processed, and continue to consider rotating the remaining files (`d.log` and `e.log`) - something like that has already been suggested in #38.

But if that can't be done, then it would be more useful for logrotate to not apply the second rule _at all_ to any log file (because of the clashes) - so it at least behaves consistently. I spent quite a bit of time trying to work out why some files were being ignored when my glob string seemed perfectly valid.

At the very least, the error message given because of a file matching more than one rule should indicate that the conflicting rule has aborted processing and that no further log files will be considered by it.

**Comment by kdudka** [comment]
I agree that the outcome could be unexpected.  But logrotate does report an error (even without `--debug` or `--verbose`), doesn't it?  So the first step to take by the user should be to eliminate the error and then possibly debug further.

The original behavior of logrotate in this situation was to bail out immediately and rotate nothing.  Now logrotate tries to recover from the error and rotate at least something (most importantly the logs that are completely unrelated to the conflicting globs).

As you say, it is still not perfect.  There is definitely room for improvements.

**Comment by kdudka** [comment]
I believe this has been further improved via #473.
