### ISSUE TITLE
Ambiguous manpage about postrotate/lastaction

### ISSUE THREAD

**Issue by hadmut** [logrotate/logrotate#260]
Hi,
the manpage does not tell about what's the difference between a postrotate script with sharedscript option (=run once after all rotations have been done) and the lastaction script (which again =run once after all rotations have been done), or in other words what the sharedscripts option is good for if there's two script sections, one intended to be run for each single log file and one for all logfiles. 

(My problem: I need to run both, a script for each single file and one for all to have the daemon reopen the logs, thus need to rewrite the postrotate config that came with the distribution using postrotate+sharedscripts, and I am not sure whether I can change this into a lastaction script in order to get the postrotate free for nonsharedscript use. man page does not really help.
if both do the same job, then imho the sharedscript option should be removed.)

**Comment by kdudka** [comment]
I believe that `prerotate`/`postrotate` with `sharedscripts` enabled should be more or less equivalent to `firstaction`/`lastaction`.  Some corner cases may exist though.  I would suggest to try it out on some test bed and report any unexpected side effects, so that we can document them.

> if both do the same job, then imho the sharedscript option should be removed.

Removal of such widely used configuration directive is just impossible.  It would badly break backward compatibility.

**Comment by hadmut** [comment]
There's, btw., some logical error:

If you want to send, e.g., every log file to some backup repository after rotating, you run into a particular problem. You could put the job to deal with every single log file into postrotate (with nosharedscripts option) in order to have it run with every single log file to be sent to the repository, but the big kill -HUP would then be done in lastaction to have the daemon reopen the log files only once. 

But then, logentries are lost since the daemon would still write to the old log files after sending. 

The only solution would be to use postrotate+sharedscripts or lastaction, send the HUP or USR1 signal or whatever, and use the *.log pattern given as an argument to try to find all log files. But then, you don't know whether the daemon already has recreated all logfiles and you need to do nasty things like sleep. 


BTW: „should be more or less equivalent” means: Write the difference between „more” and „less” into the manpage!

**Comment by kdudka** [comment]
> Write the difference between „more” and „less” into the manpage!

Sorry for the confusion.  I meant exactly this.  Please feel free to suggest how to improve the man page.
