### ISSUE TITLE
race condition in file name

### ISSUE THREAD

**Issue by hadmut** [logrotate/logrotate#261]
Hi,
when rotating files with date extension, logrotate does still pass the file name of the un-rotated log file name to postprocessing scripts. So technically the script does not now how the rotated file is named. The script can easily guess it by just adding a date suffix to the file name, but if for some reason midnight happens between the rotation and the script execution, the file name would be different and thus things fail. 

Would be good to pass the dateextension to the script, either as a parameter or as an env setting, in order to make sure both, logrotate and the script, use the same.

regards

**Comment by kdudka** [comment]
Which version of logrotate are you using?  I believe this was addressed in `3.15.0` via f8356d6f719613d65a36f4b3779ae956adbc48a7.
