### ISSUE TITLE
logrotate bomb

### ISSUE THREAD

**Issue by craigaiken** [logrotate/logrotate#266]
Had an interesting issue come up recently where a developer on one of our teams had deployed a config file into /etc/logrotate.d with a matching path like this:
```
/path/to/logs/* {
  daily
  copytruncate
  rotate 4
}
```
Now what happened was that because the matching pattern was * instead of something like *.log or *.txt, logrotate would also end up logrotating the already logrotated files.  This leads to a situation where there is an exponential increase in the number of files in this path.  In just a couple of months, we ended up exhuasting the filesystem inode limit.

It seems there is some "taboo" extension checking:
https://github.com/logrotate/logrotate/blob/master/config.c#L134
https://github.com/logrotate/logrotate/blob/master/config.c#L1391

I'm not so sure if we can add a blank to the taboo patterns though to get it working.  I'm open to creating a PR, but could use a bit of guidance on the right solution.

**Comment by kdudka** [comment]
See the logrotate(8) man page:
> Please use wildcards with caution.  If you specify *, logrotate will rotate all files, including previously rotated ones.  A way around this is to use the olddir directive or a more exact wildcard (such as *.log).

The `taboo*` directives specify exclusion of **configuration** files, not log files.
