### ISSUE TITLE
fsync in copyTruncate will block all device I/O

### ISSUE THREAD

**Issue by axot** [logrotate/logrotate#269]
We observed high disk latency when using `copyTruncate` option,
if using `rotate 0` the latency issue will be solved.
in our test, we found it may caused by [`fsync`](https://github.com/logrotate/logrotate/blob/master/logrotate.c#L1120) function.

Any ideas?

**Comment by kdudka** [comment]
`fsync()` is called intentionally.  See 2e804e710a789dc3ac8d70f4e58a9d8e6f34f4e6 and af01c0e7f05eeb911c651b5cc7d3248622b8acae.  While it is not my work, I agree with the design choice: degraded performance is better than risk of data loss.

**Comment by axot** [comment]
Hi @kdudka, I also agreed with to avoid the risk of data loss. So there is one thing I want to make clear, does `fsync(fd)` will block whole filesystem, or it just block the access to `fd`? It was interesting `fsync(fdsave);` will add large latency to the access of `fdcurr`.

**Comment by kdudka** [comment]
This highly depends on OS kernel and its implementation of the particular file system that the file resides on (and possibly on the underlying stack of block devices).  You can try to improve the performance by tweaking mount options, kernel tunables, or using a different file system type.

**Comment by cappaberra** [comment]
@kdudka, in my situation, I would gladly trade the risk of data loss for optimal performance.  It would be preferable IMHO to let that choice be made by the system administrator.

**Comment by kdudka** [comment]
@cappaberra Did you try to set tunables of the file system (and/or the underlying I/O stack) in this regard?  I do not think that the problem is specific to logrotate.

**Comment by cappaberra** [comment]
@kdudka, what tunables are you thinking of trying?

**Comment by kdudka** [comment]
@cappaberra It highly depends on the file system in use.  For example, if you use ext4, you can try to mount the file system with flags `data=writeback barrier=0`.
