### ISSUE TITLE
Docs for "rotate"

### ISSUE THREAD

**Issue by guettli** [logrotate/logrotate#27]
Current man page

>rotate count
>   Log files are rotated count times before being removed or mailed to the address specified in a mail 
> directive. If count is 0, old versions are removed rather than rotated. 

What happens, if you don't specify this value? I have guess, but I don't like guessing :-)

**Comment by rvealokin** [comment]
The default seems to be `0`

**Comment by guettli** [comment]
@rvealokin you think 0 is the default. How did you discover this?

**Comment by rvealokin** [comment]
I ran it with and without `rotate` directive and looked through the code. You can also add `-d` key on the command line and it will print some details about number of rotations.

**Comment by guettli** [comment]
ok, now I know it. Should this be in the docs? What do you think?

**Comment by rvealokin** [comment]
I created a pull request with some changes including this addition to the docs.

**Comment by guettli** [comment]
You already created it? Where? I could not find it.

**Comment by rvealokin** [comment]
https://github.com/logrotate/logrotate/pull/36/commits/2e464b76e125a149a87bd3ac0741faee72870083

**Comment by guettli** [comment]
thank you very much
