### ISSUE TITLE
Error when using the shred option

### ISSUE THREAD

**Issue by joshua-schnabel** [logrotate/logrotate#275]
If the option shred is enabled, an error occurs under Alpine with logrotate 3.15.0:

```
/media/data/logs # logrotate --force  /etc/logrotate.d/nginx
shred: can't open '-': No such file or directory
error: Failed to shred /media/data/logs/access.1.log
, trying unlink
```
configuration: 

```
/media/data/logs/access.log {
        rotate 7
        maxage 8
        daily
        ifempty
        nocreate
        missingok
        compress
        delaycompress
        shred
        shredcycles 2
        sharedscripts
        copy
        copytruncate
        extension .log
        postrotate
          nginx -s reload
        endscript
}
```

**Comment by kdudka** [comment]
Which implementation of `shred` are you using?

Please provide the output of the following commands:
```
$ command -v shred
$ shred --version
$ t=$(mktemp); { echo data && shred -uv -;} >$t; ls -l $t
```

**Comment by kdudka** [comment]
So you are using `shred` from BusyBox, which does not provide a compatible interface.  It takes file names but it does not take dash as an operand to denote standard output.  In theory, logrotate could invoke shred with a file name but it would be a step backwards -- see commit 4ff07fd2edbabbf3d0af0efb2e4605dcc95ccb93.

I would suggest to request implementation of the missing interface in BusyBox.  Meanwhile you can use another implementation of `shred` with compatible interface.

Any better idea?

**Comment by glensc** [comment]
On Linux `/proc/self/fd/N` could work, but I would not say it's a better idea, just more like a workaround.

**Comment by joshua-schnabel** [comment]
My solution is to switch back from Alpine to Debian. Thanks for the work.

**Comment by glensc** [comment]
@joshua-schnabel you can install `coreutils` package on alpine and then you have the functional variant:

```
$ docker run --rm -it alpine sh
/ # which shred
/usr/bin/shred
/ # shred --version
shred: unrecognized option: version
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: shred FILE...

Overwrite/delete FILEs

	-f	Chmod to ensure writability
	-n N	Overwrite N times (default 3)
	-z	Final overwrite with zeros
	-u	Remove file
/ # apk add coreutils
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libattr (2.4.47-r7)
(2/3) Installing libacl (2.2.52-r5)
(3/3) Installing coreutils (8.30-r0)
Executing busybox-1.29.3-r10.trigger
OK: 7 MiB in 17 packages
/ # which shred
/usr/bin/shred
/ # shred --version
shred (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Colin Plumb.
/ #
```

**Comment by glensc** [comment]
btw, busybox bugtracker is here, if someone wants to file a feature request:
- https://bugs.busybox.net/buglist.cgi?quicksearch=shred

**Comment by joshua-schnabel** [comment]
@glensc thanks for help, that's the answer. Sorry, I didn't realize I could install it. I didn't expect alpine to provide multiple shred variants.
