### ISSUE TITLE
Add a "minage" feature

### ISSUE THREAD

**Issue by sastorsl** [logrotate/logrotate#28]
I would like to see a "minage" feature (vs maxage) - where you can specify the time in seconds, minutes, hours or days where any file newer that the minage will be ignored/not rotated.
Seems similar to https://bugzilla.redhat.com/show_bug.cgi?id=731371

My specific use case is that I'm managing log files in several locations, and some of them are date stamped. Using the same log rotation routine / program is important.

The date stamped files are automatically created by the logger, so a new file appears at midnight.
Since I can't specify a "minage", and logrotate is run by cron.daily at about 03:15, todays logs will be spread over two files.

Moving cron.daily could fix the actual use case, but in some systems you are not able to or cron.daily should not be moved due to other considerations.

Having the possibility to ignore a file until it is old enough is a valid feature IMHO.

**Comment by rvealokin** [comment]
+1 for this feature. 

In my use case I want to rotate Apache Tomcat logs. The log file names a somewhat tricky to match as some of them __always__ contain a timestamp. I would rather use a more reliable way by checking when was the last time file was modified.

**Comment by rvealokin** [comment]
I have created a patch in my fork if you want to give it a try (https://github.com/rvealokin/logrotate/commit/504885b2e025928caff6dbb241f91cbe60bb7ef8).
It adds a `minage` directive where you can specify age in days.

**Comment by glensc** [comment]
seems submitted as #36
