### ISSUE TITLE
Logrotate fails to remove old logs

### ISSUE THREAD

**Issue by cschuber** [logrotate/logrotate#284]
We had a situation where on Jan 27 the server possibly crashed or logrotate was killed or terminated (I haven't investigated the root cause). However with "rotate 52" specified, there were in fact 53 files. Running logrotate -v indicated that there were too many files; terminating log rotation for the particular file. (In our case multiple files were affected.)

**Comment by kdudka** [comment]
I would suggest to create a reproducer for this.  It should be similar with `rotate 2` and 3 files in log dir while much easier to debug.

**Comment by cschuber** [comment]
On November 28, 2019 7:15:32 AM PST, Kamil Dudka <notifications@github.com> wrote:
>I would suggest to create a reproducer for this.  It should be similar
>with `rotate 2` and 3 files in log dir while much easier to debug.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/logrotate/logrotate/issues/284#issuecomment-559530247

Sure. I'll try to do that next week. The original problem was on RHEL (cc'd my work email and boss). I can reproduce on FreeBSD. 


-- 
Pardon the typos and autocorrect, small keyboard in use. 
Cy Schubert <Cy.Schubert@cschubert.com>
FreeBSD UNIX: <cy@FreeBSD.org> Web: https://www.FreeBSD.org

The need of the many outweighs the greed of the few.

Sent from my Android device with K-9 Mail. Please excuse my brevity.
