### ISSUE TITLE
Clarify why logrotate checks permissions when not run as root

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [logrotate/logrotate#285]
from: https://github.com/logrotate/logrotate/pull/237
> If one uses su in logrotate's configuration, logrotate drops privileges while rotating logs.
> Consequently, non-privileged attackers using timed symlink attacks can only cause damage to
> files they have access to. This could hardly be called an attack ;-)

I just wanted to make sure that I understand this fully:
1. When logrotate is run by root, which is the majority of the time, it is insecure for logrotate to write files into directories that are `world writable or writable by group which is not "root"`
2. When logrotate is run by a user other than root, it checks directory permissions as if it was run by root. That is it does not call getuid and then change it's behavior based on the result.
3. The `su` command can be used to disable the check for directories  `world writable or writable by group which is not "root"`

Given 3, why not also call and use getuid?

**Comment by kdudka** [comment]
>  1. When logrotate is run by root, which is the majority of the time, it is insecure for logrotate to write files into directories that are `world writable or writable by group which is not "root"`

Yes.

>  2. When logrotate is run by a user other than root, it checks directory permissions as if it was run by root.

It does not.  The check is only effective if `su` is not used _and_ `getuid()` returns 0 -- see the code:

https://github.com/logrotate/logrotate/blob/44a097a2/logrotate.c#L1241

>  3. The `su` command can be used to disable the check for directories  `world writable or writable by group which is not "root"`

Yes.

> Given 3, why not also call and use getuid?

I am not sure I understand the question.  Could you please show us an example?

**Comment by drjasonharrison-vp-eio** [comment]
I was using a much more complex configuration file. However this simple test does work:
```
date > $HOME/test.log;\
 echo "$HOME/test.log {}" > $HOME/config.conf;\
 logrotate -v $HOME/config.conf -s $HOME/status
```

Drat, I'm sure that something similar to that was failing. If I reencounter it I will let you know.

**Comment by kdudka** [comment]
Note that logrotate checks for strict enough permissions in two cases:
1. on the configuration files it reads
2. on the directories that it rotates log files in
It should be clear from the error message which of the checks triggered it.
