### ISSUE TITLE
null values after copytruncate

### ISSUE THREAD

**Issue by jmreymond** [logrotate/logrotate#286]
Hi,
I have a little script to listen a socket:

`nc -k -l 51401 > /appli/elk-netcat/data/elk-netcat-51401.log 2>>/appli/elk-netcat/data/elk-netcat-err.log`

and a logrotate 3.8.6 configuration as follows:
```
/appli/elk-netcat/data/elk-netcat-*.log {
        daily
        rotate 7
        copytruncate
        compress
        delaycompress
        missingok
        notifempty
        su root root
}


```
I have some troubles after a rotation since my file is truncated but starts with leading NULL values

$ od -cx elk-netcat-51401.log | head -6
0000000  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
           0000    0000    0000    0000    0000    0000    0000    0000
*
124355340  \0  \0  \0  \0   <   1   3   5   >   D   e   c       1   7
           0000    0000    313c    3533    443e    6365    3120    2037
124355360   0   5   :   1   9   :   0   7       n   x   u   i   w   a   s

How to solve this issue ?
Thanks for your tips,

**Comment by kdudka** [comment]
My guess is that the NULL values were written to the file after the rotation.  It is probably not logrotate what writes them.

**Comment by jmreymond** [comment]
sure that nc is writing during the logrotate process

**Comment by kdudka** [comment]
It is unclear what logrotate could do better in this case.
