### ISSUE TITLE
Inconsistency between code and comment

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#287]
https://github.com/logrotate/logrotate/blob/44a097a227eb28252424fe0f2281b4e97d06169d/logrotate.c#L110-L111

From [glob(3)](https://manpages.debian.org/buster/manpages-dev/glob.3.en.html):
> If errfunc returns nonzero, or if GLOB_ERR is set, glob() will terminate after the call to errfunc.

**Comment by kdudka** [comment]
I think that the code was copy/pasted from `config.c`, where it was later fixed with commit 38b5e0244129bc8d45051943888758c1d34f886a.  So I would fix the comment in `logrotate.c`, too, and keep the behavior unchanged.
