### ISSUE TITLE
Undeclared identifier logInfoHead

### ISSUE THREAD

**Issue by ayappanec** [logrotate/logrotate#29]
While trying to build logrotate in AIX machine , i encounter the following error message.

"config.c", line 389.49: 1506-045 (S) Undeclared identifier logInfoHead.
gmake: **\* [config.o] Error 1

I am seeing logInfoHead only in two places in the entire source code of logrotate.
grep -r "logInfoHead" *
config.c:               removeLogInfo(TAILQ_LAST(&logs, logInfoHead));
logrotate.h:TAILQ_HEAD(logInfoHead, logInfo) logs;

Any idea from which package this identifier comes from ?

**Comment by rvealokin** [comment]
Looking at the source it looks like this line

```
logrotate.h:TAILQ_HEAD(logInfoHead, logInfo) logs;
```

defines a struct which turns into something like this:

```
struct logInfoHead {
    logInfo *tqh_first;      /* first element */
    logInfo **tqh_last;      /* addr of last next element */
} logs;
```

Hope this helps

**Comment by kdudka** [comment]
I believe the question has been answered.  If the problem persists, please open a new issue and attach the full output of your build.

**Comment by ayappanec** [comment]
I forgot about this issue. Actually the sys header queue.h is not updated in AIX. So the TAILQ_LAST entry is not defined there and that was behind this error. I fixed it by manually defining it in config.c file . Thanks for the response Guys.

**Comment by kdudka** [comment]
Glad to see it resolved.  Thank you for clarifying it!
