### ISSUE TITLE
Feature Request: Logrotate should provide a config option to trigger rotation solely base on size limit

### ISSUE THREAD

**Issue by madhumita25** [logrotate/logrotate#292]
If I understand correctly, there is currently no way to configure logrotate to trigger rotation based purely on size limit - without switching logrotate to a different cron interval.

This, I find, is very limiting; because this cron frequency is common/global, AFAIK and it may not always be feasible to tweak it so that all modules are in agreement. More importantly,  you may not even be able to correctly anticipate what the ideal logrotate frequency should be in advance.
 
The very reason log rotation is extremely useful is because it lets you control the log footprint. IMO, The extreme flood scenarios for events cannot be foreseen. 

There has been some clatter around this -
https://stackoverflow.com/search?q=logrotate+size+limit
https://serverfault.com/search?q=logrotate+size+limit

Have not dug very deep -- but seems like it may not be that hard to do this with inotify event callback?
https://unix.stackexchange.com/questions/132054/automatically-detect-when-a-file-has-reached-a-size-limit

Disclaimer: I have not extensively tried to explore if there is prior history/context to this feature. (did not find anything relevant in issues).. So I apologize in advance if there is a solid reason this has been ruled out before.

**Comment by kdudka** [comment]
So what would be the downside of running logrotate periodically and rotate logs if their size exceeds the limit?  Are you concerned about performance impact or about logs growing too large in between the checks?

logrotate is not a daemon so it cannot rally wait for an inotify event on its own.  Maybe you could use inotify in a shell script that invokes logrotate, similarly as in the referred inotify example?

**Comment by madhumita25** [comment]
Are you concerned about performance impact or about logs growing too large in between the checks?
>> The latter. Have seen scenarios where logs grow too large too fast.

logrotate is not a daemon so it cannot rally wait for an inotify event on its own. Maybe you could use inotify in a shell script that invokes logrotate, similarly as in the referred inotify example? 
>> Okay, got it. Would have been nicer though - if there was a configuration based utility to do this.

This is something that we are seeing on customer systems, not a personal system. So needed something more generic and flexible. Let's see.

Anyway, thanks @kdudka . Please feel free to close this since it feels like this is technically infeasible..

**Comment by kdudka** [comment]
Then it should help (to some extent) to run logrotate more often.  As for the global frequency settings, you can have more than one cron jobs triggering logrotate.  Each of them can use its own config file and status file, as long as they operate on disjoint sets of log files.
