### ISSUE TITLE
Support locking / prevent concurrent compress jobs of the same log file

### ISSUE THREAD

**Issue by raoulbhatia** [logrotate/logrotate#295]
Hi,

I am encountering duplicate runs of gzip related to big log files that need rotating when calling `logrotate` i.e. hourly.

My use case:
* I am receiving 100-500GB of logs via `rsyslog` (daily) that I save to a local logfile.
* To ensure that logs are rotated in i.e. sizeable junks, I run `logrotate` hourly.
* To save on disk space, i enabled `delaycompress`.
* When the system is under load (CPU and/or IO), compression might take >1hr.  Thus, logrotate is started again and ends up `delaycompress`-ing the same file again, contributing to the overload of the system.  In this way, I sometimes see 4-5 concurrent instances of `logrotate` & `gzip`.

Is there a way to handle this (w/o implementing a locking mechanism myself), or would this require new functionality in logrotate?

Thanks,
Raoul

**Comment by kdudka** [comment]
If it happens that more processes of logrotate run in parallel on the same status file and log files, there will be much more issues than running the compressor in parallel.  In general, logrotate does not support parallel invocation unless it operates on separate status file and disjoint set of log files.

So it would be necessary to lock the whole run of logrotate.  What should be the expected action when logrotate is triggered while the previous process is still running?  Should it be skipped or queued indefinitely?

**Comment by raoulbhatia** [comment]
Thanks for getting back to me quickly.  I can think of the following locking solutions:

* Per **logfile** that is currently processed.
  * There is already some logic for compress that handles situations where `logfile.1` exists?  Perhaps this can be extended?
  * Perhaps introduce a .lck suffix for the file that is processed?
* Per **logrotate section**, i.e. `/var/log/news/* { [...] }`
* Per **logrotate config file**, i.e. `/usr/sbin/logrotate /opt/logrotate1.conf` will not lock `/usr/sbin/logrotate logrotate2.conf`.
  * However, I could think of potential issues for `/usr/sbin/logrotate /etc/logrotate.conf` vs. `/usr/sbin/logrotate /etc/logrotate.d/myconf`.
* Per **state file** (least preferred, because one specific config/logfile could lock everything else)

I also see a potential challenge when logrotate might be killed, either manually or perhaps by the system itself.  Then the locking will prevent further runs.  Perhaps there is a solution to specify "locking is only valid for 1 day", or "check if another logrotate pid has this file open"?

**Comment by kdudka** [comment]
Thanks for the analysis!  I think that exclusive access to state file is really necessary.  logrotate reads the state file before it starts rotating anything and writes the state file before exit.  This simple cannot work concurrently because one of the processes would overwrite the already updated state file in the end.
