### ISSUE TITLE
-l option missing from man page

### ISSUE THREAD

**Issue by mccarthyp-snet** [logrotate/logrotate#300]
Seems like a useful thing to document in case someone's looking to log to a file or syslog... I didn't know it was an option until I started digging through `logrotate.c`.

**Comment by cgzones** [comment]
What version of the man-page are you using?

Commit f53e9ddfe12d27516301eef8b61b5e571b9d51ea (version 3.9.0) introduced the documentation.
It is shown for example on https://manpages.debian.org/buster/logrotate/logrotate.8.en.html

**Comment by mccarthyp-snet** [comment]
Hmm.
man page says 8.
logrotate is 3.8.6.

**Comment by cgzones** [comment]
The log option was added in version [3.9.0](https://github.com/logrotate/logrotate/blob/master/ChangeLog.md#390---2015-04-03), that's why it's not available for you.

**Comment by mccarthyp-snet** [comment]
Should the man page version have been changed since new functionality was added? Or is that not how man page versioning works?

**Comment by kdudka** [comment]
The version string is embedded into the man page at build time.  So either the option is not supported by your installation of logrotate, or there is a mismatch between logrotate's executable and its man page on your system.  In any case there is not much logrotate upstream can do for you regarding this issue.  Note that `logrotate-3.16.0` is going to be released this Friday.
