### ISSUE TITLE
Maxage doesn't delete old logs without using dateext

### ISSUE THREAD

**Issue by swoopdk** [logrotate/logrotate#301]
I seem to have run into an issue. 
When using something like this example the `maxage` option doesn't delete the older logfiles (regardless of how old the mtime on them are) unless we also use the `dateext` option. 

Shouldn't it be working regardless if `dateext` is being used or not ? 

I should note i'm using the `rotate -1` option to only have older files be deleted on age and irregardless of number of logs.

Example of rotate.conf that does not seem to remove older logs ever. 

```
/home/swoopdk/logtest/logs/*.log {
  daily
  rotate -1
  ifempty
  maxage 2
}
```

However this one seems to work from my initial testing. 

```
/home/swoopdk/logtest/logs/*.log {
  dateext
  daily
  rotate -1
  ifempty
  maxage 2
}
```

I have not looked into the code yet and might be fixed in upcomming releaese this friday, but from what i gather its a bug. Unless i'm misreading the documentation and the `rotate -1` doesn't do what i think it does.

**Comment by cgzones** [comment]
I can confirm that there is a diverging behavior.

The question is: what should happen when using `rotate -1` and `maxage`?
  * no removal
       man-page says: *If count is -1, old logs are not removed at all*
  * removal

Things to do:
  * unify behavior whether using `dateext` or not
  * document in the man-page which configuration takes precedence: `rotate -1` or `maxage`
  * add test-case

**Comment by swoopdk** [comment]
From what me and colleagues read in documentation we were expecting the following behavior

`rotate -1` should say no removal at all **unless** something else like maxage wants to remove log files

This would allow logrotate the very dynamic settings og allowing logs to be removed solely based on age and not number of logs. 

Regarding the `rotate 100000`case it's not applicaple for my specific use case atm for example. I need to keep all logs for X years BUT i also need to cover that case that logs might be rotated many times a day. So the rotate count would skyrocket. 

From my initial impression of https://github.com/logrotate/logrotate/issues/202 i would support our way of thinking that `rotate -1` disabled deletion but still would allow example `maxage` to remove. 

Of course our workaround is to run a find command in post-rotate but i think as a tool logrotate would benefit from having each option work independently. After all when they are both enabled they work together that either maxage **OR** rotate is the trigger for deletion right ?

But super happy to hear it's not just me going nuts here and hope we can support my own usecase as it would make managing our logs greatly more elegant than using pre and post rotate scripts to do most of the labor :)

**Comment by cgzones** [comment]
An alternative would be to create a new special value for `rotate`:
  - `-1` never remove
  - `-2` do not remove by count, only by additional conditions like `maxage`, ...

**Comment by swoopdk** [comment]
So now we're talking my language though on my initial thought i feels redundant to have both options as i think (perhaps wrongly) that both can be done with just `-1`. 

Scenario 1 - never remove anything at all 
Solution:
`rotate -1` 
and then don't use anything else. If you never want to delete it doesn't make sense to add any other options pertaining to deletion right ? 

Scenario 2 - You want to delete only on e.g maxage
solution: 
`rotate -1` as well as `maxage <days>` 
This assuming that `rotate -1` is explained as simply turning off rotation count based deletes but logically retaining a age based deletion here. 

Scenario 3 - count only 
solution: 
As we pr default would be just set any `rotate X` being not equal to `-1` and avoid setting anything else related to deletion. 

So don't we cover all the scenarios/options simply with `-1` without the need for `-2` ?

**Comment by kdudka** [comment]
@swoopdk I agree.  Let's not over-engineer it.  I do not think that anyone uses `rotate -1` and `maxage` together while expecting `maxage` to be silently ignored.
