### ISSUE TITLE
logrotate file different extension name not same

### ISSUE THREAD

**Issue by zffocussss** [logrotate/logrotate#303]
hi team:
    I am using logrotate to take care of my application logs which will be sent by rsync.
but it has two format file exension.can you help me ?

log-20200301
log-20200302
log-20200303
log.10
log.9
log.8
log.7
log-20200304
log.6
log.5
log.4
log-20200305

configuration
```
{
daily
rotate 15
missingok
notifempty
nocompress
copytruncate
dateext
}
```

**Comment by kdudka** [comment]
`dateext` does not create the files with `.[0-9]` extension.  How are you confirming that those files were created by logrotate running with the above configuration?

**Comment by zffocussss** [comment]
> `dateext` does not create the files with `.[0-9]` extension. How are you confirming that those files were created by logrotate running with the above configuration?

these files are produced by application.I just put the log directory here.

**Comment by zffocussss** [comment]
> > `dateext` does not create the files with `.[0-9]` extension. How are you confirming that those files were created by logrotate running with the above configuration?
> 
> these files are produced by application.I just put the log directory here.

the strange point is some are suffix with date format,other is number(1,2,3)

**Comment by kdudka** [comment]
I am confused now.  What creates the files `log.4`, `log.5`, `log.6`, `log.7`, `log.8`, `log.9`, and `log.10`  -- logrotate or the application?
