### ISSUE TITLE
Suspicious condition

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#317]
Follow-up of #313 

https://github.com/logrotate/logrotate/blob/77e77576fa03d293d886c6537ade44ad31ab0bf7/config.c#L1001-L1009

```
sb.st_uid != ROOT_UID && (sb.st_uid != pw->pw_uid || pw->pw_uid != ROOT_UID)
```

If the first `&&` argument evaluates to `true` (i.e. `sb.st_uid` differs from `ROOT_UID`), the second argument can not be `false`: `pw->pw_uid` can not be equal to `sb.st_uid` and simultaneously be equal to `ROOT_UID` (by the first `&&` argument)

So basically the current check collapses to `sb.st_uid != ROOT_UID`, should it be `sb.st_uid != ROOT_UID && sb.st_uid != pw->pw_uid`?

I think commit f9c1689 was not quite accurate.

**Comment by kdudka** [comment]
Assuming that `getpwuid(ROOT_UID)->pw_uid == ROOT_UID` is always true, the whole condition can be simplified as `(sb.st_uid != ROOT_UID)` and the call of `getpwuid(ROOT_UID)` can be optimized out completely.
