### ISSUE TITLE
regexp processing of a log during first rotation

### ISSUE THREAD

**Issue by Zugschlus** [logrotate/logrotate#320]
Hi,

this is an enhancement proposal and I apologize for not being able to write the code.

It would be nice to have the possibility to pipe a log through a set of regular expression replacements when logrotate touches it for the first time, e.g. wenn rotating from foo to foo.1

This would, for example, be vastly useful to anonymize IP adresses from a log for data protection purposes.

Greetings
Marc

**Comment by swoopdk** [comment]
While i see your point it's already an option as you can run a post-rotate script quite easily and anonymising logs is not as such the point of the tool. I mean you could much more easily just write some simple 'sed' statements or similar to run as post-rotate script to accomplish what you're asking.
