### ISSUE TITLE
Wildcards/sharedscripts/dateext and forced rotation issue ?

### ISSUE THREAD

**Issue by th-hummel** [logrotate/logrotate#327]
Hello,

using logrotate- 3.16.0-3 on Debian 4.9.6-3 (but also 3.14.0 on CentOS 8.1), with a similar setup log don't rotate when using --force (but do naturally):

witth the following included config:
```
# cat /etc/logrotate.d/test-log 
/var/log/foobar/*/*.log {

    dateext
    compress
    rotate 10
    sharedscripts
    postrotate
        /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
```
starting with log files and dir laid out like this:

```
# ls -l /var/log/foobar/test
total 0
-rw-r--r-- 1 root root 0 mai   18 17:08 test.log
# ls -l /var/log/foobar/test2/
total 0
-rw-r--r-- 1 root root 0 mai   18 17:08 test2.log
```
1) running
```
# logrotate --force /etc/logrotate.conf
```
results, as expected in:
```
# find /var/log/foobar/
/var/log/foobar/
/var/log/foobar/test2
/var/log/foobar/test2/test2.log-20200518.gz
/var/log/foobar/test2/test2.log
/var/log/foobar/test
/var/log/foobar/test/test.log
/var/log/foobar/test/test.log-20200518.gz
```
2) removing one rotated logfile:

```
# rm /var/log/foobar/test/test.log-20200518.gz 
```

and re-running the forced rotate command result in:

a) the expected message about the already rotated logfile
```
# logrotate --force /etc/logrotate.conf 
error: destination /var/log/foobar/test2/test2.log-20200518.gz already exists, skipping rotation
```
b) the (unexpected?) non rotation of the non-already rotated file:

```
# find /var/log/foobar/
/var/log/foobar/
/var/log/foobar/test2
/var/log/foobar/test2/test2.log-20200518.gz
/var/log/foobar/test2/test2.log
/var/log/foobar/test
/var/log/foobar/test/test.log
```

Is it legit, as I would have expected `/var/log/foobar/test/test.log` to have been rotated

Besides EITHER

- commenting sharedscripts

```
# cat /etc/logrotate.d/test-log 
/var/log/foobar/*/*.log {

    dateext
    compress
    rotate 10
#    sharedscripts
    postrotate
        /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
```

OR

- using nodateext

```
# cat /etc/logrotate.d/test-log 
/var/log/foobar/*/*.log {

    nodateext
    compress
    rotate 10
    sharedscripts
    postrotate
        /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
```
works as expected, i.e. the both files end up beeing rotated (one already was, the other gets)

Thanks for your help

--
Thomas HUMMEL

**Comment by kdudka** [comment]
It looks like combination of multiple independent problems to me:
1. The `dateext` directive will use the `-%Y%m%d` suffix unless you override it with `dateformat` format directive.  So you cannot have more than one rotation a day without collisions.
2. The error **"... already exists, skipping rotation"** occurs even when you do not remove one of the rotated files (in case you rotate more than once a day).
3. The `sharedscripts` directive just makes it fail for the whole pattern rather than for the log files that have some collisions.
4. The fact that commenting out `dateext` makes the problem go away is not surprising because numbered suffixes can be incremented any time, regardless of the time the rotation is triggered.

You might consider using `dateformat -%Y%m%d%H%M%S` to make this work.

**Comment by th-hummel** [comment]
Hello, thanks for your answer.

>     1. The `dateext` directive will use the `-%Y%m%d` suffix unless you override it with `dateformat` format directive.  So you cannot have more than one rotation a day without collisions.

Of course. That's why I spoke about  an "expected" message in a)

>     2. The error **"... already exists, skipping rotation"** occurs even when you do not remove one of the rotated files (in case you rotate more than once a day).

Not sure to get what you mean here : simply that it will eventually end up with a collision if rotated more than once a day no matter what the starting conditions ? I agree.

>     3. The `sharedscripts` directive just makes it fail for the whole pattern rather than for the log files that have some collisions.

I guess THIS is what I missed: I indeed wrongfully thought that script was still run for the not collided log.
However should test/test.log (no collision) have been evaluated (thus rotated) before (wildcard extansion order) test2/test2.log (collision) ?

>     4. The fact that commenting out `dateext` makes the problem go away is not surprising because numbered suffixes can be incremented any time, regardless of the time the rotation is triggered.

Of course. I indeed mixed that up with the sharedscripts above.
  
Thanks again for your help

--
TH

**Comment by kdudka** [comment]
So your concern is about the side effect of `sharedscripts` rather then about limitation of `dateext` with the default `dateformat` suffix, as I understand it.  I do not think there is a good (generic enough) solution to this.

If you use `sharedscripts`, then `prerotate/postrotate` scripts operate on the whole pattern rather then on individual log files.  Consequently, if some of the logs fail to rotate, it is difficult to continue the rotation process in a consistent way.

**Comment by th-hummel** [comment]
> So your concern is about the side effect of `sharedscripts` rather than about limitation of `dateext` 

Yes.

> If you use `sharedscripts`, then `prerotate/postrotate` scripts operate on the whole pattern rather then on individual log files.

That's what I didn't know. Got it now.

>  Consequently, if some of the logs fail to rotate, it is difficult to continue the rotation process in a consistent way.

No problem.

Thanks again.

--
TH

**Comment by kdudka** [comment]
Should we somehow improve the documentation in this regard?

**Comment by th-hummel** [comment]
> Should we somehow improve the documentation in this regard?

Well, documentation is correct as it states "If  the  scripts exit  with error, the remaining actions will not be executed for  any logs.". However the following points might be considered non intuitive: 

1) `error: destination /var/log/foobar/test2/test2.log-20200518.gz already exists, skipping rotation`

I'm guilty of not have read the 'error' part but it may be natural to take the whole message as just a warning and not an 'exit with error' ?

2) Besides, as stated in a post above, it may be surprising to not even rotate the first log expanded from the wildcard as the error "occurs afterwards" if we take for granted that expansion will yield test before test2
 
So nothing wrong with the doc but it was my experience. 
Maybe add something like "indenpendently of wildcard expansion order" and/or "skipping already existing files will cause the script to exit with an error" ?

Thanks for your concern.

--
TH

**Comment by kdudka** [comment]
Thanks for feedback!  A documentation improvement has been proposed in #329.

**Comment by th-hummel** [comment]
> Thanks for feedback! A documentation improvement has been proposed in #329.

Thanks a lot.

--
Thomas HUMMEL
