### ISSUE TITLE
I found the psad log file, even though I had uninstalled the package

### ISSUE THREAD

**Issue by ZerooCool** [logrotate/logrotate#330]
Hello, I installed psad in the following way, I did not know.

https://wiki.visionduweb.fr/index.php?title=Analyser_les_logs_de_Iptables_programmes_non_maintenus#Afterglow

Then I uninstalled psad.

I was then working on logrotate, and, I discovered this command.
cat /var/lib/logrotate/status

I was surprised because, I found the psad log file there, even though I had uninstalled the package.
I checked the files in the logrotate configuration folder, but I did not find anything on psad.

I manually deleted the line in this file.
sudo nano /var/lib/logrotate/status

Is it normal to find lines concerning log files belonging to deleted packages, in the logrotate status?

**Comment by kdudka** [comment]
Yes, the entry in state file should be removed when it becomes unused for more than one year.  See commit 72fe334c9d0bd90e86e1a4092be6edd4b3468fc2.

**Comment by ZerooCool** [comment]
Ok ! Thank you.
