### ISSUE TITLE
Don't have any mail, with exim, how to

### ISSUE THREAD

**Issue by ZerooCool** [logrotate/logrotate#331]
Don't have any mail, with exim, how to

I can send an email from the terminal.
My emails from my CMS are sent.
Fail2ban manages to send me alerts.
PHP mail manages to send the alerts.

Currently, I don't have DenyHosts emails.
Currently, I don't have Logrotate emails.

I don't know what to check, to move on.
If someone has the courage to try.

I have only partially configured Exim, I have indeed not created a certificate, nor advanced on DKIM and DMARC ...

This is really what prevents Logrotate emails from leaving, I do not believe, I am not convinced.

Logrotate :
https://wiki.visionduweb.fr/index.php?title=Rotation_des_logs_avec_logrotate#Envoyer_un_mail_.C3.A0_chaque_rotation 

Exim : 
https://wiki.visionduweb.fr/index.php?title=Installer_un_serveur_mail#Exim

**Comment by kdudka** [comment]
You have reached logrotate upstream project.  Please provide a minimal example that demonstrates the problem with logrotate, independently of the other software.  I am not going to debug Exim and I do not speak French.

**Comment by ZerooCool** [comment]
Use a translator, i don't speak english.

I ask in fact, if someone has already used Exim with logrotate, and, if it is my configuration which would be bad.
Me neither, I will not debug, if in the end, it does not interest many people to have functional tools, and, easy to install.

Let's do nothing.

**Comment by kdudka** [comment]
> I ask in fact, if someone has already used Exim with logrotate

I think so.  See #110 or #216.

However questions related to exim do not belong to logrotate's issue tracker (unless you are able to clearly describe the underlying issue with logrotate).

**Comment by ZerooCool** [comment]
If I was able to define the problem, I would not have come for help in identifying the problem.

But, if I base myself on the situation with Fail2ban, or, Logwatch, or, FWannalog, the emails are sent.

On the other hand, with Logrotate, emails are not sent.
In debug mode, it says that the email is sent.

Excuse me, but, I think there is already enough to leave the issue open. Logrotate is supposed to be able to easily use email sending, just like Fail2ban does perfectly well.

Even if on my side, I did not complete the configuration of EXIM (with DMarc and DKIM) the mails come out correctly in normal times.

I therefore start from the premise that logrotate is not tolerant or functional enough, regarding the sending of emails (with Exim).

I could PERFECTLY work around this, by adding an email send, at the end of the rotation, in the scripts executed after the rotation, but, this would amount to not using the options offered by logrotate by default, ie, use "mail".

From my observation, there is a problem, and, it is not necessarily a problem related only to EXIM.

I think you were in too much of a hurry to close the issue.

**Comment by kdudka** [comment]
> I could PERFECTLY work around this, by adding an email send, at the end of the rotation, in the scripts executed after the rotation.

Which command would you use to send the e-mail?

You can make logrotate use the same command via the `--mail` command-line option.

> I think you were in too much of a hurry to close the issue.

I will reopen it if you provide the minimal example as requested.

**Comment by ZerooCool** [comment]
Can you look here ? https://termbin.com/2gquz
With this configuration, prerotate and postrotate send a mail with 
`echo "Debut de la rotation Iptables : $(date)" | mail -s "Debut de la rotation Iptables depuis $HOST" mail@visionduweb.com`
But, command "mail" directive , command in the configuration logrotate, sent 0 mail !
Then it's not the good way for me, if I want use logrotate with mail directive.

Strange, if i test this command in prerotate : 
```
mail -s "Début Logrotate" mail@visionduweb.com <<< 'Début Logrotate'
# logrotate_script: 3: Syntax error: redirection unexpected
# error: error running non-shared prerotate script for /var/log/iptables.log of '/var/log/iptables.log '
```
Then the prerotate mail is not send !
But, the mail directive from logrotate send the mail !
And, postrotate send the last mail with echo :
`echo "Debut de la rotation Iptables : $(date)" | mail -s "Debut de la rotation Iptables depuis $HOST" mail@visionduweb.com`

For me, this is a logrotate problem.
I could be wrong, but, you can see that my emails are out.
In addition, I miraculously succeeded in obtaining the email, at the address of the directive (it was not the same email, therefore, I could have noticed this phenomenon)!

I can't say more about what is going on, but something is going on! Saying that this is an Exim problem is not necessarily the real situation.

**Comment by ZerooCool** [comment]
Annoying, I can't reproduce the behavior.
I can get emails with echo,
I can no longer cause the email to be sent with the logrotate mail directive. For the moment, she remains silent.

**Comment by ZerooCool** [comment]
I can no longer reproduce the operation of the mail directive.
The only solution for me is to use "echo" and "mail" from pre and postrotate.
Note that by displaying the version of logrotate, it clearly tells me /bin/usr/mail for send mail.
I do not know more.

**Comment by kdudka** [comment]
logrotate runs the scripts as `/bin/sh -c ...`, so I guess that `<<<` is not a valid syntax for your `/bin/sh` interpreter.  I am able to reproduce the failure locally with dash:
```
/bin/dash -c "cat <<< 'hello'" logrotate_script
logrotate_script: 1: logrotate_script: Syntax error: redirection unexpected
```

Your configuration file contains `rotate 7`, so logrotate will not send any e-mail until you rotate 7 times whereas the `postrotate` script runs on each rotation.

**Comment by ZerooCool** [comment]
_logrotate runs the scripts as /bin/sh -c ..., so I guess that <<< is not a valid syntax for your /bin/sh interpreter. I am able to reproduce the failure locally with dash:_

```
/bin/dash -c "cat <<< 'hello'" logrotate_script
logrotate_script: 1: logrotate_script: Syntax error: redirection unexpected
```
For that, i don't, but, if i use the same command to my terminal, the mail is send.

_Your configuration file contains rotate 7, so logrotate will not send any e-mail until you rotate 7 times whereas the postrotate script runs on each rotation._

Ohhh ! Really ?!!! 
Thank you for your answer ! I look that ASAP !

**Comment by ZerooCool** [comment]
@kdudka 

You got it right !!!

```
# Logs will be kept for up to 7 rotations.
# A rotation of 0 deletes the logs immediately after their rotation.
# The mail directive will send an email after the first x rotations. <<<<<<<<<<<<
rotate 3
```

```
# Add the administrator's email to contact:
# The operation of the mail directive depends on the value of the rotate directive ! <<<<<<<<<<<<
# The last existing log that will be deleted is sent by email.
mail my@adress.ext
```

Please,
Maybe you can integrate this in the configuration comments ?

Resolved for me.
