### ISSUE TITLE
Does the "sharedscripts" option really imply the "create" option?

### ISSUE THREAD

**Issue by mkauf** [logrotate/logrotate#336]
From the man page:
> ``sharedscripts``: ... This option overrides the ``nosharedscripts`` option and implies ``create`` option.

I think that this makes no sense, so I have tested this and had a quick glance at the source code. If I tested correctly, then "sharedscripts" does not imply the "create" option.

Also, I found this logrotate configuration for chrony on Fedora, which uses both "sharedscripts" and "nocreate":
```
/var/log/chrony/*.log {
    missingok
    nocreate
    sharedscripts
    postrotate
        /usr/bin/chronyc cyclelogs > /dev/null 2>&1 || true
    endscript
}
```

Please verify this, and fix the man page if necessary.

**Comment by kdudka** [comment]
The statement appeared in the man page 15 years ago in commit 62b4a6fe1ac52ca88a52b75fb6578b689a2bb54e without any explanation.  I fail to see any reason why `sharedscripts` would imply `create`.  So I propose to just remove the statement from the man page.

**Comment by mkauf** [comment]
Thanks!
