### ISSUE TITLE
How to handle data loss during Logrotation?

### ISSUE THREAD

**Issue by Ravikiran7161** [logrotate/logrotate#338]
Suppose the rsyslog writing logs continuously to a log file, when we run log rotation job at the time of writing, don't we miss any data? How to handle this situation? Please explain in brief. Thank you

**Comment by cgzones** [comment]
- rsyslog open e.g. */var/log/syslog*, gets a file descriptor and writes to this file.
- logrotate rotates/renames old and not in use logfiles */var/log/syslog.X* -> */var/log/syslog.X+1*
- logrotate renames (see [rename(**2**)](https://manpages.debian.org/unstable/manpages-dev/rename.2.en.html)) */var/log/syslog* to */var/log/syslog.1* and creates an empty file */var/log/syslog*
  rsyslog still has the renamed file open and continues writing to it via the file descriptor (**not** via the path)
- logrotate runs the postrotate command (in case of rsyslog e.g. `systemctl kill -s HUP rsyslog.service`), so rsyslog closes the old file descriptor and opens a new one with the path of */var/log/syslog*, which is now an empty file

**Comment by Ravikiran7161** [comment]
1. So, In the transition of closing the old file descriptor and start writing to new empty file--> won't be any data loss? not even a single message? 

2. systemctl kill -s HUP rsyslog.service --> will this command reloads the rsyslog.conf file also?

**Comment by Ravikiran7161** [comment]
/var/log/hostname/*.log {
rotate 20
copytruncate
sharedscripts
missingok
size 5k
postrotate
       /bin/kill -HUP rsyslogd.pid
endscript
}

This is what i am using

**Comment by kdudka** [comment]
There should be no data lost caused by logrotate itself (except for old logs rotated out of their existence).  What exactly happens in rsyslog when it receives SIGHUP is not really a question for logrotate developers.  You will get a more accurate answer on rsyslog discussion channels.
