### ISSUE TITLE
delaycompress with rotate 0

### ISSUE THREAD

**Issue by bes-internal** [logrotate/logrotate#341]
There is some problem with combination delaycompress and rotate 0 when removed old files.
`error: error unlinking log file /var/log/atop/dummy_after.1.gz: No such file or directory`

/etc/logrotate.d/psaccu_atop:
```
# Logrotate file to take action after psacct is rotated
/var/log/atop/dummy_after {
  compress
  delaycompress
    missingok
    daily
    rotate 0
    ifempty
    create 0600 root root
    postrotate
        if [ -e /etc/logrotate.d/psacct ]
        then
            # if the atop daemon does not run, restart it after
            # accounting file is rotated
            PIDFILE=/var/run/atop.pid

            if [ -e $PIDFILE ] && \
                        ps -p `cat $PIDFILE` | grep 'atop$' > /dev/null
            then
                :
            else
                /usr/share/atop/atop.daily&
            fi
        fi
    endscript
}
```

Output `logrotate -f -v /etc/logrotate.d/psaccu_atop`:
```

rotating pattern: /var/log/atop/dummy_after  forced from command line (no old logs will be kept)
empty log files are rotated, old logs are removed
considering log /var/log/atop/dummy_after
  Now: 2020-07-07 15:14
  Last rotated at 2020-07-07 15:09
  log needs rotating
rotating log /var/log/atop/dummy_after, log->rotateCount is 0
dateext suffix '-20200707'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
previous log /var/log/atop/dummy_after.1 does not exist
renaming /var/log/atop/dummy_after.1.gz to /var/log/atop/dummy_after.2.gz (rotatecount 1, logstart 1, i 1), 
old log /var/log/atop/dummy_after.1.gz does not exist
renaming /var/log/atop/dummy_after.0.gz to /var/log/atop/dummy_after.1.gz (rotatecount 1, logstart 1, i 0), 
old log /var/log/atop/dummy_after.0.gz does not exist
log /var/log/atop/dummy_after.2.gz doesn't exist -- won't try to dispose of it
renaming /var/log/atop/dummy_after to /var/log/atop/dummy_after.1
disposeName will be /var/log/atop/dummy_after.1.gz
creating new /var/log/atop/dummy_after mode = 0600 uid = 0 gid = 0
running postrotate script
removing old log /var/log/atop/dummy_after.1.gz
error: error unlinking log file /var/log/atop/dummy_after.1.gz: No such file or directory
```

https://bugs.gentoo.org/689558

**Comment by kdudka** [comment]
`rotate 0` means remove the log file as soon as its "rotation" is triggered.  So it makes no sense to use it together with `delaycompress`.  Obviously, if you remove the log file, there is nothing to compress later on, which is exactly what the error message says.

The problem in https://bugs.gentoo.org/689558 was that `delaycompress` was added to the top-level configuration file while `rotate 0` was used by a package-provided configuration file.  So the combination of them was not obvious at all.

We should tweak logrotate to handle the configuration in question gracefully, which most likely means to just ignore the `delaycompress` directive in this specific case.

**Comment by bes-internal** [comment]
I believe that the combination of options should not cause any errors at all and this should be decided on the side of the program, not the configuration. And of course, the program should give a warning about an invalid combination of options or explain the behavior if it is ambiguous

**Comment by kdudka** [comment]
On Wednesday, July 8, 2020 3:38:32 PM CEST Vladimir Varlamov wrote:
> I believe that the combination of options should not cause any errors at all

So you suggest to ignore the `delaycompress` directive in this specific case?

> and this should be decided on the side of the program, not the
> configuration.

I do not understand this part.

> And of course, the program should give a warning about an
> invalid combination of options or explain the behavior if it is ambiguous

Or just error out as many similar programs do in such cases, for example:

$ cp --backup --no-clobber --verbose a b
cp: options --backup and --no-clobber are mutually exclusive
Try 'cp --help' for more information.

**Comment by bes-internal** [comment]
> Or just error out as many similar programs do in such cases, for example: $ cp --backup --no-clobber --verbose a b cp: options --backup and --no-clobber are mutually exclusive Try 'cp --help' for more information.

I'm talking about this. If combination of options is "impossible", then you need to stop the program and explain what is happening and (at best) what you need to do to solve this problem. The above error in logrotate makes nothing clear what happens without source code or your personal explain. 

> So you suggest to ignore the `delaycompress` directive in this specific case?

As you said yourself:
> if you remove the log file, there is nothing to compress later on

so yes, it needs to be resolved inside the program, do not disturb the user about this

**Comment by kdudka** [comment]
On Thursday, July 9, 2020 1:54:10 AM CEST Vladimir Varlamov wrote:
> so yes, it needs to be resolved inside the program, do not disturb the user
> about this

I proposed to just ignore `delaycompress` in this specific case in my initial 
reply.  Are you proposing something else?  I do not understand your comments.

Printing an error or warning in case a new package installs a configuration 
file into /etc/logrotate.d does not sound strictly better to me.

**Comment by bes-internal** [comment]
> I proposed to just ignore `delaycompress` in this specific case in my initial reply.  I do not understand your comments.

I do not understand why you do not understand

> I proposed to

I'm not a developer, you yourself must decide what needs to be done to solve this problem. I don’t care. If this is some kind of politeness, then I do not need it too. 

> I proposed to just ignore `delaycompress`

Yes. Do it.
