### ISSUE TITLE
3.14 does not create new files

### ISSUE THREAD

**Issue by haussli** [logrotate/logrotate#349]
with the config:

/var/log/auth.debug
/var/log/authpriv.debug
/var/log/cron.debug
/var/log/daemon.debug
/var/log/ftp.debug
/var/log/kern.debug
/var/log/lpr.debug
/var/log/mail.debug
/var/log/news.debug
/var/log/security.debug
/var/log/syslog.debug
/var/log/user.debug
/var/log/uucp.denug
/var/log/local0.debug
/var/log/local1.debug
/var/log/local2.debug
/var/log/local3.debug
/var/log/local4.debug
/var/log/local5.debug
/var/log/local6.debug
/var/log/local7.debug
{
        rotate 7
        daily
        create 644 root root
        ifempty
        missingok
        # compress
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}

logrotate does not create these files, which do not exist. eg:
# logrotate -f -v /etc/logrotate.d/test
reading config file /etc/logrotate.d/test
Reading state from file: /var/lib/logrotate/status
Allocating hash table for state file, size 64 entries
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state
Creating new state

Handling 1 logs

rotating pattern: /var/log/auth.debug
/var/log/authpriv.debug
/var/log/cron.debug
/var/log/daemon.debug
/var/log/ftp.debug
/var/log/kern.debug
/var/log/lpr.debug
/var/log/mail.debug
/var/log/news.debug
/var/log/security.debug
/var/log/syslog.debug
/var/log/user.debug
/var/log/uucp.denug
/var/log/local0.debug
/var/log/local1.debug
/var/log/local2.debug
/var/log/local3.debug
/var/log/local4.debug
/var/log/local5.debug
/var/log/local6.debug
/var/log/local7.debug
 forced from command line (7 rotations)
empty log files are rotated, old logs are removed
considering log /var/log/auth.debug
  log /var/log/auth.debug does not exist -- skipping
considering log /var/log/authpriv.debug
  log /var/log/authpriv.debug does not exist -- skipping
considering log /var/log/cron.debug
  log /var/log/cron.debug does not exist -- skipping
considering log /var/log/daemon.debug
  log /var/log/daemon.debug does not exist -- skipping
considering log /var/log/ftp.debug
  log /var/log/ftp.debug does not exist -- skipping
considering log /var/log/kern.debug
  log /var/log/kern.debug does not exist -- skipping
considering log /var/log/lpr.debug
  log /var/log/lpr.debug does not exist -- skipping
considering log /var/log/mail.debug
  log /var/log/mail.debug does not exist -- skipping
considering log /var/log/news.debug
  log /var/log/news.debug does not exist -- skipping
considering log /var/log/security.debug
  log /var/log/security.debug does not exist -- skipping
considering log /var/log/syslog.debug
  log /var/log/syslog.debug does not exist -- skipping
considering log /var/log/user.debug
  log /var/log/user.debug does not exist -- skipping
considering log /var/log/uucp.denug
  log /var/log/uucp.denug does not exist -- skipping
considering log /var/log/local0.debug
  log /var/log/local0.debug does not exist -- skipping
considering log /var/log/local1.debug
  log /var/log/local1.debug does not exist -- skipping
considering log /var/log/local2.debug
  log /var/log/local2.debug does not exist -- skipping
considering log /var/log/local3.debug
  log /var/log/local3.debug does not exist -- skipping
considering log /var/log/local4.debug
  log /var/log/local4.debug does not exist -- skipping
considering log /var/log/local5.debug
  log /var/log/local5.debug does not exist -- skipping
considering log /var/log/local6.debug
  log /var/log/local6.debug does not exist -- skipping
considering log /var/log/local7.debug
  log /var/log/local7.debug does not exist -- skipping
not running postrotate script, since no logs were rotated

**Comment by cgzones** [comment]
The `create` directive says

> Immediately after rotation (before the postrotate script is run) the log file is created ...

But since the log files do not exist in the first place, logrotate does not rotate them, so the create step is not performed.

You may create all the log files once and then logrotate should behave as you expected.
