### ISSUE TITLE
Error "duplicate log entry" with duplicate comment

### ISSUE THREAD

**Issue by ardelis-creech** [logrotate/logrotate#350]
Hi,

the same Problem as in #109 occurs with 3.14.0 Debian Buster.
It rotates the log but annoys me with that error message.

Feature Request: "shut up" and "force" option

Greetings

**Comment by kdudka** [comment]
The problem described in #109 was fixed in `logrotate-3.12.0`.  It is unlikely that you are observing the **same** problem with `logrotate-3.14.0`.
