### ISSUE TITLE
3.17 failing to compile on centos6

### ISSUE THREAD

**Issue by twk3** [logrotate/logrotate#351]
During build on centos6 I am seeing the following error:

```
config.c:(.text+0x40b0): undefined reference to `secure_getenv'
```

It looks like the use of `secure_getenv` was added in https://github.com/logrotate/logrotate/pull/326

**Comment by kdudka** [comment]
Thank you for reporting it!  I believe this is already fixed with commit c73c0d7cbc081e59b88fee4079eb3a3a3ee7639d.

**Comment by twk3** [comment]
Ahh, missed that. Great, will confirm with the next release

**Comment by kdudka** [comment]
OK, closing for now.  Please feel free to reopen if the problem persists.
