### ISSUE TITLE
create new log file at each system startup

### ISSUE THREAD

**Issue by dkwo** [logrotate/logrotate#352]
I'm using logrotate with rsyslog on Void Linux.
I have a line in my rsyslog.conf that looks like
`*.err /var/log/errorfile`
Is there a way to have logrotate create one such file at each system (re)boot, renaming previous ones as errorfile1.log etc, and keep say the most recent 5 of them?

**Comment by kdudka** [comment]
You can create a system service that runs `logrotate -f ...` on boot (instead of triggering logrotate periodically while system is running).  You can also combine both the approach (on boot and periodical).  Just make sure that they use separate configuration file and state file.

**Comment by dkwo** [comment]
Thank you.
Perhaps just as a reference for myself, I created a file /etc/logrotate.d/errorfile.conf
```
/var/log/errorfile {
        missingok
        rotate 5
        notifempty
}
```
and then run it via logrotate -f /etc/logrotate.d/errorfile.conf as a runit service.
