### ISSUE TITLE
`minsize` does not seem to take any effect

### ISSUE THREAD

**Issue by sjc2870** [logrotate/logrotate#353]
`rotating pattern: /opt/maxscale/var/log/maxscale/maxscale.log  1048576 bytes (20 rotations)
empty log files are not rotated, only log files >= 524288000 bytes are rotated, old logs are removed
switching euid to 1000 and egid to 1000
considering log /opt/maxscale/var/log/maxscale/maxscale.log
  log needs rotating
rotating log /opt/maxscale/var/log/maxscale/maxscale.log, log->rotateCount is 20`
But ”only log files >= 524288000 bytes are rotated“ is conflict with "maxscale.log  1048576 bytes" and " log needs rotating"
Here is my logrotate version :`logrotate 3.8.6 - Copyright (C) 1995-2001 Red Hat, Inc.`

**Comment by sjc2870** [comment]
And this is my rotate config
maxscale.log {
rotate 20
missingok
nocompress
notifempty
copytruncate
sharedscripts
postrotate
endscript
minsize 500M
su maxscale maxscale
nocreate
}

**Comment by kdudka** [comment]
Are you sure there is no `-f` or `--force` command-line option used while invoking logrotate?

**Comment by sjc2870** [comment]
> Are you sure there is no `-f` or `--force` command-line option used while invoking logrotate?

No,but I add daily in config file and everything be OK.
