### ISSUE TITLE
Group logrotate configs based on postrotate script

### ISSUE THREAD

**Issue by mphilipps** [logrotate/logrotate#354]
hi,
It would be nice if multiple logrotate configs could be grouped so that the postrotate script may only run once.
Currently if a service has multiple log files, I need to use the same settings rotate/maxsize/compress ... or sharedscripts won't work and logrotate is going to restart the service multiple times.

```
/logs/a {
    rotate 60
   daily
   maxsize 268435456
   missingok
   notifempty
   compress
   sharedscripts
   postrotate
      /bin/systemctl restart test.service
   endscript
}
/logs/b {
    rotate 10
   daily
   maxsize 268435456
   missingok
   notifempty
   compress
   sharedscripts
   postrotate
      /bin/systemctl restart test.service
   endscript
}
```

Should restart test.service only once.

**Comment by mphilipps** [comment]
I have tried to work around this by having logrotate do a touch /some/marker/file in the /logs/a /logs/b section and having a third logrotate snipped in a zz_* file with rotate 0 and the actual postrate command. However it appears that while the logrotates are triggered in alphabetic order, they are actually executed in parallel. So if /log/a takes a few minutes to rotate, /some/marker/file has already finished.

**Comment by kdudka** [comment]
I think this is usually not needed because logs produced by a single service are usually rotated based on a single configuration.  Cannot you just use the same `rotate` count for both the logs?  Alternatively, cannot you use `systemctl reload` instead of `restart` to make it less disruptive?

**Comment by mphilipps** [comment]
Sometimes you want to keep error longs longer than access logs and unfortunately not all services support reopening logs on receiving a signal. My current workaround is to write restart scripts in the postrotate section which then get called  by a separate script that runs after logrotate.

**Comment by cgzones** [comment]
E.g. the default rsyslog configuration on Debian is
```
/var/log/syslog
{ 
        rotate 7
        daily
        missingok
        notifempty
        delaycompress
        compress
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}

/var/log/mail.info
/var/log/mail.warn
/var/log/mail.err
/var/log/mail.log
/var/log/daemon.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/lpr.log
/var/log/cron.log
/var/log/debug
/var/log/messages
{
        rotate 4
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}
```
and there is a potential [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=720096) caused by this.

However it is not a trivial change as logrotate currently processes one configuration completely interdependently after the other.

**Comment by kdudka** [comment]
> My current workaround is to write restart scripts in the postrotate section., which then get called by a separate script that runs after logrotate.

I do not understand this part.  Either the restart/reload action is safe, in which case it does not matter how many times you invoke it, or it is unsafe, in which case you have a problem anyway, just less likely to occur.  You might consider using the `copytruncate` directive instead of restarting the service.  Each approach has its pros and cons.

**Comment by mphilipps** [comment]
>  Either the restart/reload action is safe, in which case it does not matter how many times you invoke it,

This isn't the case. Systemd limits how often a given service can be restarted in a short interval. So restarting a service 5 times might be ok, but 6 times isn't. In that case systemd refuses to start the service with the following message:
`
service start request repeated too quickly, refusing to start`

Having repeated restarts from logrotate killing services is not to my liking.

**Comment by kdudka** [comment]
This can be easily configured if systemd rate limiting is the only problem here.  See the documentation of `StartLimitBurst`:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval

**Comment by mphilipps** [comment]
I am aware of that, but I would prefer a generic solution that doesn't require meddling around with sensible default values.  

The idea that if restarting once is fine, so is restarting a dozen times is just false.

**Comment by kdudka** [comment]
> The idea that if restarting once is fine

The problem is that restarting once is usually not fine either.  It is a poor solution to begin with.

**Comment by mphilipps** [comment]
I agree, if I could I would rewrite every program to do their own log handling and there would be no need for logrotate anymore.
