### ISSUE TITLE
Does it work for journal logs?

### ISSUE THREAD

**Issue by guoyunhe** [logrotate/logrotate#358]
I have openSUSE Tumbleweed. logrotate works perfectly for Apache logs. But my `/var/log/journal` still grows to 4.1GB. I wonder if logrotate can be used for journal logs. If so, how could the configuration be?

**Comment by kdudka** [comment]
In theory yes, but `systemd-journald` has its own setting to limit disk usage, e.g. `SystemMaxFileSize`:

https://www.freedesktop.org/software/systemd/man/journald.conf.html

**Comment by cgzones** [comment]
I wouldn't recommend using logrotate for systemd journal files.

These journal files are not raw text files and I'd rather not intefere with journald. (They also have some default compression, see https://www.freedesktop.org/software/systemd/man/journald.conf.html#Compress=)

Probably you want to use `journalctl --vacuum-size=, --vacuum-time=, --vacuum-files=`, see https://www.freedesktop.org/software/systemd/man/journalctl.html#--vacuum-size=
