### ISSUE TITLE
[alpine] [3.16.0-r0] tabooext doesn't work?

### ISSUE THREAD

**Issue by dstryzhov** [logrotate/logrotate#362]
Hello.
I'm using Alpine docker image with installed logrotate, and it seems like the 'tabooext' directive has no effect.

Dockerfile:
```
FROM alpine

RUN apk add logrotate
RUN rm -rf /var/cache/apk/*
RUN ln -s /etc/periodic/daily/logrotate /etc/periodic/hourly/logrotate

COPY conf /etc/logrotate.d/vcrlogs
RUN chmod 644 /etc/logrotate.d/vcrlogs

CMD crond -f
```
Conf file
```
tabooext + .gz
/var/log/* /var/log/*/*  {
  copytruncate
  daily
  rotate 15
  compress
  compressoptions -9
  dateext
  dateformat -%Y%m%d-%H-%M
  missingok
  maxsize 250M
}
```

Logrotate version:
```
/ # apk info logrotate
logrotate-3.16.0-r0 description:
Tool to rotate logfiles

logrotate-3.16.0-r0 webpage:
https://github.com/logrotate/logrotate

logrotate-3.16.0-r0 installed size:
110592

```

I end up with following:

```
-rw-r-----. 1 vcr vcr 5.3K Oct 26 15:22 catalina.log-20201027.gz-20201030-00-00.gz-20201031-00-00.gz-20201101-00-00.gz-20201102-00-00.gz-20201103-00-00.gz
-rw-r-----. 1 vcr vcr  431 Oct 26 15:22 localhost.log-20201027.gz-20201030-00-00.gz-20201031-00-00.gz-20201101-00-00.gz-20201102-00-00.gz-20201103-00-00.gz
-rw-r-----. 1 vcr vcr 369K Oct 26 13:56 localhost.log-20201026.gz-20201030-00-00.gz-20201031-00-00.gz-20201101-00-00.gz-20201102-00-00.gz-20201103-00-00.gz
-rw-r-----. 1 vcr vcr  64M Oct 26 10:50 localhost_access_log.txt.1.gz-20201030-00-00.gz-20201031-00-00.gz-20201101-00-00.gz-20201102-00-00.gz-20201103-00-00.gz
```

Note: the log files are created by different docker services that use non-root user. The target directories with logs are then mounted as a `/var/log/*` into logrotate container.

Any insights are appreciated & apologies if the issue wasn't created properly

**Comment by kdudka** [comment]
The `tabooext` configuration directive affects only inclusion of configuration files that would otherwise be picked by the `include` directive.  `tabooext` does not affect globbing of log files.

**Comment by dstryzhov** [comment]
> The `tabooext` configuration directive affects only inclusion of configuration files that would otherwise be picked by the `include` directive. `tabooext` does not affect globbing of log files.

I see. The reason I tried to use tabooext is that I wanted my configuration to apply to **all** files under /var/log/, including `/var/log/messages` that I kept getting errors about (due to non-existence).
But I just noticed that the default `/etc/logrotate.conf` file contains an entry for `/var/log/messages` which is probably why I am getting the error in the first place. So since I'm using docker, I can just replace the default conf file with my own version (that doesn't expect `/var/log/messages`) and instead of wildcarding `/var/log/*` I can have something more specific like `/var/log/*.log /var/log/*.txt`

thank you for your time
