### ISSUE TITLE
Null in the beginning of file after rotating log using copytruncate option

### ISSUE THREAD

**Issue by pranjaldoshi96** [logrotate/logrotate#363]
I was using copytruncate option for logrotation. After logrotation I found bunch of binary characters before my log file starts. logs are continuously generating. 
```
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```
I am using the following configuration
```
/log/typeA*.log
/log/typeB*.log
/log/typeC*.log{
        daily
        rotate 7
        copytruncate
        size 1M
        compress
        su root root
        create 0644 root root
        missingok
}
```
I checked on google and https://serverfault.com/a/221343 explained the problem. And https://serverfault.com/a/221650 suggested that there might not be a solution for this.

**Comment by kdudka** [comment]
Actually this might be a use case for the recently proposed `copyreduce` feature, which is currently under review.  See pull request #361 for details.
