### ISSUE TITLE
Fast forward to the end of 2020. I have noticed a re-occurrence of this problem.

### ISSUE THREAD

**Issue by marXtevens** [logrotate/logrotate#364]
Fast forward to the end of 2020. Forgive me if I am doing this incorrectly, but it seemed a good idea to tie the two issues together.

I have noticed a re-occurrence of this problem. 
It does not happen every rotation. I am guessing it is a timing concern, and still generates an error, rather than a warning?
The result is that logrotated does not restart automatically.

I am running Fedora 32 Server, and updating weekly. 
I am attaching output from journalctl for logrotate for the beginning of November, through December 3 (today). 
[journalctl_logrotate.zip](https://github.com/logrotate/logrotate/files/5637313/journalctl_logrotate.zip)

_Originally posted by @marXtevens in https://github.com/logrotate/logrotate/issues/144#issuecomment-738109294_

**Comment by kdudka** [comment]
Why are you reporting a single issue at two places at a time?  See my reply at: https://github.com/logrotate/logrotate/issues/144#issuecomment-738109294

**Comment by marXtevens** [comment]
Sorry for cross posting. It seems there are multiple entry points for this concern and I overdid it. 
From the supplied log file ...Dec 03 00:00:01 reindeer.marXtevens.strangled.net systemd[1]: Starting Rotate log files...
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: destination /var/log/sssd/sssd_implicit_files.log-20201126.gz already exists, renaming to /var/log/sssd/sssd_implicit_files.log-20201126.gz-2020120300.backup
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: error unlinking log file /var/log/sssd/sssd_implicit_files.log-20201126: No such file or directory
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: destination /var/log/sssd/sssd_nss.log-20201126.gz already exists, renaming to /var/log/sssd/sssd_nss.log-20201126.gz-2020120300.backup
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: error unlinking log file /var/log/sssd/sssd_nss.log-20201126: No such file or directory
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: error unlinking log file /var/log/sssd/sssd_implicit_files.log-20201122.gz: No such file or directory
Dec 03 00:00:01 reindeer.marXtevens.strangled.net logrotate[368186]: error: error renaming temp state file /var/lib/logrotate/logrotate.status.tmp
Dec 03 00:00:01 reindeer.marXtevens.strangled.net systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 00:00:01 reindeer.marXtevens.strangled.net systemd[1]: logrotate.service: Failed with result 'exit-code'.

Any suggestions as to how I determine which of the above errors (as stated in the output line) is the real culprit causing logrotate to fail (rc=1)?
My concern is that if logrotate fails, I'd like to know if *I* did something wrong, or the tool is not functioning correctly, as when it fails, the restart fails, and I have missed the failure, and may not restart on the same day, to ensure it finished processing correctly.
Thank you!
 
-----Original Message-----

**Comment by kdudka** [comment]
It looks like there were multiple processes of logrotate running in parallel.  `logrotate-3.17.0` introduces a locking mechanism to avoid it.
