### ISSUE TITLE
Release 3.18.0?

### ISSUE THREAD

**Issue by lollipopman** [logrotate/logrotate#366]
Any chance we could see I new release? I would love to use the new gid/uid, https://github.com/logrotate/logrotate/commit/d457d2b13c21e01725886478aa95dc2f518b8d2e, functionality in our infrastructure.

**Comment by kdudka** [comment]
I was hoping for pull request #361 to be merged before the next release of logrotate but it seems to be staled.

@cgzones Is there anything else in your queue for the upcoming release of logrotate?

**Comment by cgzones** [comment]
No, I have nothing on my list.
(A new release would also fit in for the upcoming freeze of the next Debian release).

**Comment by kdudka** [comment]
I am afraid that we are entering a common vacation season shortly, which is going to delay feedback on the release and, more importantly, our response to that feedback in case something breaks.  Would January 8th work for you?

**Comment by lollipopman** [comment]
of course, thanks for all your work on logrotate!
