### ISSUE TITLE
Global options in drop-in files in /etc/logrotate.d possibly confusing

### ISSUE THREAD

**Issue by mgerstner** [logrotate/logrotate#370]
It seems that for packages shipping drop-in config snippets for `/etc/logrotate.d` it is possibly unintuitive that global options there influence other packages' config files that are parsed afterwards.

A real life example is FreeRADIUS/freeradius-server#3829. This drop-in config file causes other packages' logfile configurations to seemingly arbitrarily break, because radiusd globally drops privileges to another user.

Maybe logrotate could change its behaviour in this context by rejecting global settings in drop-in config files or by requiring an explicit opt-in syntax in the drop-in snippet to make global options effective.

**Comment by kdudka** [comment]
I can see how this is not user-friendly but changing the behavior is just impossible.  We can improve the documentation or, for example, make logrotate print a warning with `--verbose` though.

**Comment by mgerstner** [comment]
Improved documentation would be a start. A warning, too, although I don't know how many people run `logrotate --verbose`.

Maybe instead of changing existing behaviour you could introduce a new keyword like `include_safe` or `include_local` that doesn't affect global options. This would allow integrators to make explicit decisions about this like maintaing two separate drop-in directories something like `/etc/logrotate.global.d` and `/etc/logrotate.local.d`.

**Comment by kdudka** [comment]
Honestly, I do not think this is the way to go.  `#include` in C/C++ and `source` in shell scripts work in the same way as logrotate works today.  There is no `#include_safe` in C/C++ and there is exactly the same problem in `/etc/profile.d/*` sourced scripts. I do not think that logrotate is any different.  This is just how raw file inclusion works.

**Comment by mgerstner** [comment]
That is correct. I can follow that from an implemention point of view.

However, C/C++ and shells are in a programming/shell language domain, while a logrotate configuration file is not perceived as a programming language by most people, I suppose. I'm actually surprised that only freeradius-server fell into this trap (as far as I know), because people that ship a drop-in config file for logrotate don't even see this `include` statement, they just see their isolated snippet.

As I see it from the distribution point of view it makes nearly no sense at all to put any global configuration setting into /etc/logrotate.d, except maybe as something like /etc/logrotate.d/000-global, where it is made sure that the global settings are performed before any other files are parsed. Otherwise nobody can tell what exactly happens, which logfiles are affected by global settings and which not. It depends upon which packages are installed and in which place of the alphanumerical sorting they end up when /etc/logrotate.d is processed. SUSE Linux ships over a hundred drop-in config files for /etc/logrotate.d from different packages, all of them only care about their package-specific logfiles as far as I can see.

As a Linux distribution we can also catch errors like in freeradius-server on packaging level but it seemed a good idea to me to allow to make this safer in the upstream package where it originates.
