### ISSUE TITLE
Issue with Tomcat9 file catalina.out

### ISSUE THREAD

**Issue by Dhamma-valence** [logrotate/logrotate#371]
So this is an issue with tomcat9, specifically the file catalina.out.
The error is:

```
error: skipping "/var/log/tomcat9/catalina.out" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```
and  /etc/logrotate.d/tomcat9 is the default which is

```
 /var/log/tomcat9/catalina.out {                                
   copytruncate                                                 
   weekly                                                       
   rotate 52                                                    
   compress                                                     
   delaycompress                                                
   missingok                                                    
   create 640 tomcat adm                                        
 }
```
changing `create 640 tomcat adm` to `create 640 tomcat root`, which is my actual admin account, does nothing.

However, when I completely purge tomcat9 (Debian Bullseye), it fixes this completely.

I saw another difficult-to-understand issue with very little information as the only related issue, but this is probably just a simple misconfiguration of default permissions if I had to guess?

**Comment by kdudka** [comment]
I would suggest to solve this by using the `su` directive of logrotate.  I do not know the full context but something like `su tomcat adm` could help?
