### ISSUE TITLE
'datelastrotation' like 'dateyesterday'

### ISSUE THREAD

**Issue by Benjipede** [logrotate/logrotate#373]
In a certain project, we would like to rotate logs not only daily, but also at certain events. As far as I can tell, this can be done with 'logrotate -f <config-file>'. However, we would also like to date the log files after their creation time. I imagine a config parameter like `dateyesterday` which instead uses last rotation time, preferably down to the second.

It seems like last rotation time is tracked in the code, however, I saw a comment about it only being correct down to the hour. Is it doable?

**Comment by kdudka** [comment]
Cannot you just use `dateext`/`dateformat` for this?  It provides second accuracy already.

**Comment by Benjipede** [comment]
Sure, but that gives me the current time, not time of last rotation.

**Comment by kdudka** [comment]
If you run `logrotate -f`, then current time is also time of the last rotation, isn't?

**Comment by Benjipede** [comment]
Well, when I write last rotation, I mean the previous one. The one being executed is not done, so it is not the last one, right? The following is what I would like to happen.

Time: 2021/01/27 - 00:00:00
```
> ls
a.log
```

Time: 2021/01/27 - 10:04:22
```
> logrotate -f /etc/logrotate.conf
> ls
a.log
a.log-2021027_000000.xz
```

Time: 2021/01/28 - 00:00:00
```
> logrotate -f /etc/logrotate.conf
> ls
a.log
a.log-2021027_000000.xz
a.log-2021027_100422.xz
```

**Comment by kdudka** [comment]
I do not understand what you are trying to achieve.  Are you expecting the first invocation of `logrotate -f` to guess the time of your `ls` invocation and use it as the `dateext` suffix?  It does not make any sense to me.

If your concern is about timestamps stored in file system metadata, those should be preserved across renames while rotating in the basic scenario (without `compress`, `copytruncate`, etc.).
