### ISSUE TITLE
logrotate(8) man page: incorrect /var/log/news/* example and missing warning against multiple "kill -HUP"

### ISSUE THREAD

**Issue by vinc17fr** [logrotate/logrotate#374]
The logrotate(8) man page has an example
```
/var/log/news/* {
    monthly
    rotate 2
    olddir /var/log/news/old
    missingok
    postrotate
        kill -HUP $(cat /var/run/inn.pid)
    endscript
    nocompress
}
```
without `sharedscripts`. This means that the `kill -HUP` will be run for each rotated file of the same daemon, yielding a race condition. See [Debian bug 720096](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=720096) as an example concerning rsyslog. This should be fixed in some way (if done by adding `sharedscripts`, don't forget to update the `sharedscripts` description, which assumes that `sharedscripts` is not present for this example).

Moreover, the man page should warn against using `kill -HUP` multiple times for a same daemon, as this yields a race condition. This may imply that the same rule should be used for all log files of such a daemon (as now done for rsyslog in Debian, see above).

And I don't understand "_This is considered a single rotation directive and if errors occur for more than one file, the log files are not compressed._" Since the `nocompress` option is used, the log files should not be compressed at all, whether there are errors or not.

**Comment by kdudka** [comment]
I agree that the example looks inconsistent.  Thank you for pointing it out!  So we should use `sharedscripts` in this example and remove the statement about not compressed log files, as I understand it.  I am not sure with the warning about signal handling in daemons though.  That is probably out of scope for logrotate's man page.

Are you going to create a pull request to get this fixed or should I apply the changes on your behalf?

**Comment by vinc17fr** [comment]
Please apply the changes on my behalf. Thanks.
