### ISSUE TITLE
error: /etc/logrotate.conf:19 unknown user 'nginx'

### ISSUE THREAD

**Issue by asarubbo** [logrotate/logrotate#375]
Hello,

we have one logrotate.conf that we propagate on all machines we manage.
This file includes a rule for nginx logs but do not have nginx on all machine, so with 3.14.0 while /var/log/nginx/*log were not present on the disk we didn't receive errors but with 3.17.0, we do.

Is there a way to circumvent this issue?

```
# logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf -f ; echo $?
error: /etc/logrotate.conf:19 unknown user 'nginx'
error: found error in /var/log/nginx/*log
, skipping
error: /etc/logrotate.conf:47 unknown user 'mysql'
error: found error in /var/log/mariadb/mariadb.log
, skipping
1
```

**Comment by asarubbo** [comment]
e547b942ebdf58026f0b28a74b3d02a7674e38dc is the commit that introduced the issue for us. Note that we are using missingok, so why it is processing the block inside a missing log?

**Comment by kdudka** [comment]
Assuming the user names map to the same UIDs on all machines, which is very often the case, you can use specify the users by their UIDs in your `logrotate.conf`.  This possibility was introduced in `logrotate-3.18.0`.  See issues #217 for details.

**Comment by asarubbo** [comment]
Sorry, I don't understand the correlation between my 'question' and your answer.

I don't need to specify UID. What I would like to achieve is to not hit any errors when a user ( in a block related to a non existing file) does not exist.
TIA

**Comment by kdudka** [comment]
With `logrotate-3.18.0`, you can specify the users numerically in your configuration and the mentioned error will disappear.

**Comment by asarubbo** [comment]
Unfortunately nginx user is not mapped with the same UID across all machines. What's the trick in cases like this?

**Comment by kdudka** [comment]
The following approach has worked for Linux distributions since forever:
1. `/etc/logrotate.conf` contains only system-wide global options and the line: `include /etc/logrotate.d`
2. Each service that needs its log files rotated installs its own drop-in into `/etc/logrotate.d`.

I am afraid that delaying the error till a rotation triggers would not please admins in general.  Any other proposal?

**Comment by asarubbo** [comment]
> The following approach has worked for Linux distributions since forever:
> 
> 1. `/etc/logrotate.conf` contains only system-wide global options and the line: `include /etc/logrotate.d`
> 2. Each service that needs its log files rotated installs its own drop-in into `/etc/logrotate.d`.
> 
> I am afraid that delaying the error till a rotation triggers would not please admins in general. Any other proposal?

You are completely right, but with the ansible approach and hundreds of machines, we found more comfortable have just one file with all rules instead of including from subdirectory.

After all is right that the exit status is 1 instead of 0 especially for syntax errors.

In cases like this, the syntax is right but there is something missing on the system side. How sounds an option like 'ignoremissingusers' to ignore errors that comes from missing users on the systems?

**Comment by kdudka** [comment]
What would be the fallback e.g. for the `su` directive?  Running the rotations as root?  Users would  shoot themselves in the foot.

**Comment by asarubbo** [comment]
Whatever solution is fine for me if I can skip error for non existing users.

**Comment by kdudka** [comment]
Which configuration directive actually triggers the error in your case?  As far as I can see, the information is missing in your report.

**Comment by asarubbo** [comment]
```
/var/log/nginx/*log
{
        create 0644 nginx nginx
        sharedscripts
        postrotate
                /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
        endscript
}
```

**Comment by asarubbo** [comment]
Any news on this?

thanks

**Comment by kdudka** [comment]
Honestly, I am not sure how to fix this in logrotate.  Delaying the check till the first rotation is IMO not going to please everybody.  As I understand it, this would be better to solve at the Ansible level.

**Comment by asarubbo** [comment]
Hi,

I hit this issue on 2021 on Gentoo, because as a rolling distro, it pulled an updated logrotate at that time. Now I noticed I have the same issue with the recent redhat derivates like rocky-9 or almalinux-9

Yes, the problem can be solved at ansible level by using the `package_facts` module that checks if a program (like nginx in this case) is installed or not and then insert or not the configuration block.

For approaches likes this, it will work only if nginx is installed before ansible configurates logrotate.conf, and there is no warranty that programs will be installed before ansible configuration.

That said, I think that the best to fix this issue is to have a logrotate configuration option that completely ignores unexisting files and their blocks (like `ignoremissingfile`/`ignoremissinglog`). So if there aren't `/var/log/nginx/*log` on the filesystem it should not go into its configuration block.

What do you think?

**Comment by kdudka** [comment]
In my view, it is still a problem that happens at the ansible level and it should be fixed there.  The proposed extension in logrotate could hide real problems and complicate the debugging in certain situations.

**Comment by saper** [comment]
What if you have no nginx installed and no `nginx` user, and for some reason somebody created /var/log/nginx/nginx.log owned by some other user, what should `logrotate` do? Start failing only then trying to rotate it for a first time?

Numeric UID/GID are not a perfect solution, [either](https://github.com/logrotate/logrotate/pull/561).

Ansible has a feature like inventory and roles, which can let you tell "do nginx stuff on some machines, but not on others". The worst problem with Ansible is that it is deceitfully simple at the very beginning, and later.... :scream:
