### ISSUE TITLE
Feature request: perform rotation only if files have changed

### ISSUE THREAD

**Issue by Lucas-C** [logrotate/logrotate#384]
Hi !

First: thank you very much for maintaining this great, robust tool!

This is a much a feature request as a question to find if `logrotate` already support the use case I have in mind.

**Use case: context**
I'm using `logrotate` to keep backups of small SQLite database files,
that change in average once every month (with sometimes burst of several changes over a few hours).

Currently I run `logrotate` on a daily basis, with a retention period of a few months,
meaning that many "rotated" `.db` files are identical.

**Use case: what I'd like**
Could it be possible that `logrotate` only performs rotation **if the target file is different from the last rotated `.1` file**?

**Alternate solution**
Could `logrotate` keep rotated files over varying period of times? _E.g._:
* one rotated file per day of the week
* plus one rotated file from 1 month ago
* plus one rotated file from 1 year ago

I have checked both the logrotate configuration man page & the currently opened issues,
and neither seem to include any mention of the kind of configuration I'm looking for.

**Is this something that `logrotate` support or could support?**

Any pointer to other existing tools providing this kind of feature is also welcome 😊

**Comment by cgzones** [comment]
logrotate is designed to rotate log files. Normally log files differ each iteration and it is preferred to keep the last x iterations than several non-consecutive ones with different time scales.

I think your use case is more a kind of backup and I am not sure such features would fit logrotate.

**Comment by kdudka** [comment]
I agree with @cgzones that a backup tool would do much better job here.  Unfortunately, I do not have first-hand experience with any backup tool myself.

**Comment by Lucas-C** [comment]
Alright. Thank you for your answers.
I am a bit disappointed but I understand that this is not a use case you wish to support.
AFAIC, this issue can be closed.
