### ISSUE TITLE
[Feature Request] Print location of state file

### ISSUE THREAD

**Issue by lonix1** [logrotate/logrotate#392]
On different distributions (ubuntu, rhel, etc.) the state file exists in different locations, e.g. `/var/lib/logrotate/status`, `/var/lib/logrotate/logrotate.status`, etc.

Please consider adding a switch that simply prints the location of the state file. This would be very useful in automated environments like ansible/puppet, so we can easily determine the location and use it in scripts.

e.g.
````
logrotate --state
````

prints:
````
/var/lib/logrotate/status
````

**Comment by kdudka** [comment]
`logrotate --version` already prints the default state file path:
```
$ logrotate --version
logrotate 3.18.1

    Default mail command:       /bin/mail
    Default compress command:   /bin/gzip
    Default uncompress command: /bin/gunzip
    Default compress extension: .gz
    Default state file path:    /var/lib/logrotate/logrotate.status
    ACL support:                yes
    SELinux support:            yes
```

Could the script parse it out from there so that we do not need to introduce a separate option for each line in the above output?

**Comment by lonix1** [comment]
Yes! That is very useful, thanks for letting me know.

**Comment by lonix1** [comment]
````shell
logrotate --version | grep 'state file' | tr -s ' ' | sed 's/.*path: //'
````
