### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#405]
Since June 15th travis-ci.org is down and it has been replaced by travis-ci.com.
With this transition the quota/credit system has been changed with quite some limitations.
logrotate should fit their category of open-source projects, but there still might be obstacles, see for example https://daniel.haxx.se/blog/2021/06/14/bye-bye-travis-ci/.

Option I is to move to travis-ci.com and see how the services is continuing.
Option II is to move to a new CI service, e.g. GitHub Actions.

**Comment by kdudka** [comment]
I am fine with both.  We definitely need some CI that works.

**Comment by cgzones** [comment]
I tried to activate logrotate on travis-ci.com, but (maybe because I lack some permissions) it did not work.
Can you try to activate or move from travis-ci.org?

**Comment by kdudka** [comment]
Done.  I was able to trigger a build: https://www.travis-ci.com/github/logrotate/logrotate/builds/230427318

I chose the Free plan, which consists of 10000 credits, which is going to be spent quickly I am afraid.  Then we will probably need to apply for some OSS approval to get additional credits.

**Comment by kdudka** [comment]
Closing per https://github.com/logrotate/logrotate/pull/406#issuecomment-1084625776
