### ISSUE TITLE
Request: Attach release download file logrotate-3.9.2.tar.gz

### ISSUE THREAD

**Issue by abelbeck** [logrotate/logrotate#41]
It would be convenient for distros using your releases to have a download file attached to your release using the same naming convention as you have in the past, ie. ```logrotate-3.9.2.tar.gz```

Also attaching a SHA1 logrotate-3.9.2.tar.gz.sha1 (or such) would be useful as well.

**Comment by glensc** [comment]
seems you forgot to mention what download page are you even speaking of!?

**Comment by abelbeck** [comment]
@glensc Not sure what you are asking but I was referring to the past downloads:
https://fedorahosted.org/logrotate/

versus the Releases page here:
https://github.com/logrotate/logrotate/releases

**Comment by glensc** [comment]
i was just pointing out that bugreport may be considered incomplete if you don't say which page you used for downloads.

otherwise (to maintainer), if https://fedorahosted.org/logrotate/ is no longer used to upload generated tarballs, they should be attached to github releases page. seems currently neither of the pages contain generated tarballs (containing auto* scripts, configure, etc).
- https://fedorahosted.org/logrotate/
- https://github.com/logrotate/logrotate/releases

just relying on github tags on source tree is not sufficient for autoconf/automake projects.

**Comment by michaelkeuter** [comment]
@glensc: I think the thread opener means the source download file name on GitHub is now "3.9.2.tar.gz" versus "logrotate-3.9.2.tar.gz" on Fedorahosted. I would also prefer "logrotate-3.9.2.tar.gz" as file name (including the projectname).

**Comment by glensc** [comment]
@michaelkeuter i just said the initial report is incomplete because he did not mention *which* download page he has in mind. see my followup post as well: https://github.com/logrotate/logrotate/issues/41#issuecomment-226509928

**Comment by michaelkeuter** [comment]
Since version 3.9.2 is only available on github, its clear, I think

**Comment by kdudka** [comment]
Sorry for replying late to this!  As logrotate is currently hosted on GitHub, the release tarballs should be available on GitHub.  I will take care of making them available.

**Comment by kdudka** [comment]
The build system of logrotate is not in a good condition. ```make dist``` does not produce a usable tarball.  I will attach a file named ```logrotate-3.9.2.tar.gz``` containing just the git snapshot.  Then I will try to fix all the build system issues and release ```logrotate-3.10.0.tar.gz```, which can be built on a machine where auto* tools are not available.  Any objections?

**Comment by abelbeck** [comment]
Sounds good to me, Thanks !

**Comment by glensc** [comment]
uploading logrotate-3.9.2.tar.gz containing just the git snapshot is useless. such tarball already provided by github automatically from git tags.

so i suggest to rather fix build system and forget 3.9.2 release

**Comment by glensc** [comment]
also i suggest to add `make dist` command to `.travis.yml`

**Comment by kdudka** [comment]
On Monday, August 01, 2016 05:13:53 Elan Ruusam�e wrote:
> uploading logrotate-3.9.2.tar.gz containing just the git snapshot is
> useless.

True.  Nobody will use it now when next release is already on the way.

> such tarball already provided by github automatically from git tags.

The problem (already mentioned in this thread) is that GitHub provides
it under an unexpected file name (3.9.2.tar.gz).  I want all releases
of logrotate to be available as logrotate-X.Y.Z.tar.gz for consistency,
either on fedorahosted.org (up to 3.9.1), or GitHub (since 3.9.2).

As for the release tags, they are also inconsistent.  Most common format
is rX-Y-Z with recent exceptions r3.8.2 and 3.9.2.  Which release tag
should we use for the upcoming release?

r3-10-0 ?

r3.10.0 ?

3.10.0 ?

logrotate-3.10.0 ?

something else?

**Comment by glensc** [comment]
forget the automatic git export that github provides. you need to UPLOAD your own tarball. there is no way to disable automatic git tag export.

and when you upload your own tarball, you have full control of the filename and file contents. i suggest just upload the tarball and not change the scheme you tag releases (git tags).

if still confused, then here's project which has uploaded tarball (uploaded by maintainer) and the sourcecode downloads (provided by github automatically):
https://github.com/eventum/eventum/releases

**Comment by kdudka** [comment]
On Monday, August 01, 2016 07:39:25 Elan Ruusam�e wrote:
> forget the automatic git export that github provides. you need to UPLOAD
> your own tarball. there is no way to disable automatic git tag export.

Sure.  I already agreed to upload release tarballs produced by 'make dist'.
However, it is impossible to do that for the 3.9.2 release, which is already 
out with broken build system.  For 3.9.2, I will only upload correctly named 
tarball produced by git-archive.

> and when you upload your own tarball, you have full control of the filename
> and file contents. i suggest just upload the tarball and not change the
> scheme you tag releases (git tags).

Which scheme?

There is currently no unified scheme for the existing git tags.  That is why
I asked about your preference on tagging the upcoming 3.10.0 release.

> if still confused, then here's project which has uploaded tarball (uploaded
> by maintainer) and the sourcecode downloads (provided by github
> automatically): https://github.com/eventum/eventum/releases

No problem with that.  I wrote a script for uploading custom release tarballs 
to GitHub for another project recently:

https://github.com/kdudka/nss-pem/blob/master/upload-release.sh

It should be easy to reuse once we have something to upload :-)

**Comment by glensc** [comment]
On 01.08.2016 18:30, Kamil Dudka wrote:
> Sure. I already agreed to upload release tarballs produced by 'make dist'.
> However, it is impossible to do that for the 3.9.2 release, which is 
> already
> out with broken build system. For 3.9.2, I will only upload correctly 
> named
> tarball produced by git-archive.

and i'm trying to say that there is no point of that, github already 
provides archive for each tag produced by git-archive, unless i'm 
missing something.

anyway. looking forward for "3.10.0" tag and attached tarball :)
my preference is to use "3.10.0" or "v3.10.0" as git tag.

-- 
glen

**Comment by kdudka** [comment]
On Tuesday, August 02, 2016 00:37:33 Elan Ruusam�e wrote:
> and i'm trying to say that there is no point of that, github already
> provides archive for each tag produced by git-archive, unless i'm
> missing something.

Yes, GitHub already provides it but the file name of the archive is different.  
So I will just upload the same contents using a "correct" file name.  In any 
case, it is harmless.  The 3.9.2 release will be available under both names.

> anyway. looking forward for "3.10.0" tag and attached tarball :)
> my preference is to use "3.10.0" or "v3.10.0" as git tag.

Let it be "3.10.0" then to stay consistent with the "3.9.2" tag.  If there is 
any issue with that, we can change the scheme later on.

**Comment by glensc** [comment]
minor errors from make test:

```
./test: line 65: journalctl: command not found
logrotate_script: /usr/bin/printf: not found
```

full log:
http://sprunge.us/eDiA

**Comment by glensc** [comment]
also added: #46 but somewhy travis is not invoked in that PR...

**Comment by kdudka** [comment]
I have pushed 4 commits on top of that:
+ fab472c806d46accc25ce4fc319526ee8ab535b2 test: avoid printing misleading error messages
+ 5fb0ae45e786ec879ecf3cd411130f9dbeab6e3c run make distcheck on travis
+ 87c733f8ebd9cf2269ff07047371302c96ae60c7 README.md: drop nbsp
+ 43406edc96aa83f346afcb47fc9b39476db4b3e8 fixup! test: let tests run on 'make distcheck'

Could you please retest?

**Comment by glensc** [comment]
btw, the dash tests also fail:
```
test: 221: test: -m: not found
```
https://travis-ci.org/logrotate/logrotate/jobs/149169778

**Comment by glensc** [comment]
also few more printf abs paths:

```
[~/rpm/packages/logrotate/logrotate(3.9.2) (kdudka)⚡] ➔ rgrep -r /usr/bin/printf .
./test/test-config.44.in:9:             IFS=$(/usr/bin/printf "\n\b")
./test/test-config.44.in:19:            IFS=$(/usr/bin/printf "\n\b")
./test/test-config.42.in:19:            IFS=$(/usr/bin/printf "\n\b")
```

also you probably want to move `logrotate.spec` -> `logrotate.spec.in` and replace version with `@VERSION@` autoconf macro.

**Comment by kdudka** [comment]
On Tuesday, August 02, 2016 06:16:53 Elan Ruusam�e wrote:
> btw, the dash tests also fail:
> ```
> test: 221: test: -m: not found
> ```
> https://travis-ci.org/logrotate/logrotate/jobs/149169778

Yes, that is what https://github.com/logrotate/logrotate/commit/43406edc
was supposed to fix.  Once we are done with the review, I will squash it
into the commit that broke it (dc19b231).

**Comment by kdudka** [comment]
On Tuesday, August 02, 2016 06:20:48 Elan Ruusamäe wrote:
> also few more printf abs paths:
> 
> ```
> [~/rpm/packages/logrotate/logrotate(3.9.2) (kdudka)⚡] ➔ rgrep -r
> /usr/bin/printf . ./test/test-config.44.in:9:            
> IFS=$(/usr/bin/printf "\n\b") ./test/test-config.44.in:19:           
> IFS=$(/usr/bin/printf "\n\b") ./test/test-config.42.in:19:           
> IFS=$(/usr/bin/printf "\n\b") ```

Thanks for spotting!  Fixed via 009bf86 for now.

> also you probably want to move `logrotate.spec` -> `logrotate.spec.in` and
> replace version with `@VERSION@` autoconf macro.

Sounds feasible.  But what will we do with the %changelog section then?

What is actually the purpose of logrotate.spec in the upstream git repository?  
Is it still up2date?

**Comment by glensc** [comment]
`logrotate.spec` in upstream git... probably as reference point for someone wishing to add their own `.spec`...

but it's also possible to build rpm from tarball:
`$ rpmbuild -ta logrotate-3.10.0.tar.gz`

it doesn't work in my distro (anymore) due custom `~/rpmbuild` layout, but may work in RHEL/Fedora-like systems.

`%changelog` ... seems pointless, that section is optional. who wishes to track file changes should use git

**Comment by glensc** [comment]
make test looks ok now. full log: http://sprunge.us/bhJj

**Comment by kdudka** [comment]
+ 4c9e3c2307a67cb27e226b3261d08c316e7e6039 logrotate.spec: now generated by ./configure

**Comment by kdudka** [comment]
```logrotate-3.9.2.tar.gz``` is now available at:
https://github.com/logrotate/logrotate/releases/download/3.9.2/logrotate-3.9.2.tar.gz

```logrotate-3.10.0.tar.gz``` will be released later today.

**Comment by glensc** [comment]
congrats on the 3.10.0 release!

however few remarks:
- add `README.md` to automake generated tarball
- avoid distributing empty files (afaik `AM_INIT_AUTOMAKE([foreign])` does the job):
```
-rw-r--r-- 1 glen users    0 Aug  3 13:26 AUTHORS
-rw-r--r-- 1 glen users    0 Aug  3 13:26 ChangeLog
-rw-r--r-- 1 glen users    0 Aug  3 13:26 NEWS
-rw-r--r-- 1 glen users    0 Aug  3 13:26 README
```

**Comment by kdudka** [comment]
Thanks for the feedback!  Your proposal has been pushed as 77399ea5.
