### ISSUE TITLE
"keyword 'size' not properly separated, found 0x3d" warning

### ISSUE THREAD

**Issue by GimmeHardware** [logrotate/logrotate#410]
The man page states values are separated from directives by whitespace and/or an optional =.

But this change:
[https://github.com/logrotate/logrotate/commit/2b588b5ec2e5c27bee857c4abeddafa6a9602ebc](https://github.com/logrotate/logrotate/commit/2b588b5ec2e5c27bee857c4abeddafa6a9602ebc)
does not accept the optional =.

For example "size=+2048k" in the mcelog logrotate file works with logrotate 3.18.0 but triggers this warning with 3.18.1.
[https://git.kernel.org/pub/scm/utils/cpu/mce/mcelog.git/tree/mcelog.logrotate](https://git.kernel.org/pub/scm/utils/cpu/mce/mcelog.git/tree/mcelog.logrotate)
[https://www.linuxquestions.org/questions/showthread.php?s=cb29de3ab1aa6aa6407d395d3c9d07d4&p=6253331#post6253331](https://www.linuxquestions.org/questions/showthread.php?s=cb29de3ab1aa6aa6407d395d3c9d07d4&p=6253331#post6253331)

**Comment by cgzones** [comment]
Thanks for reporting.
#411 should silence this unintended warning.
