### ISSUE TITLE
Reducing rotate counter doesn't have effect without triggering rotation

### ISSUE THREAD

**Issue by Loki087** [logrotate/logrotate#413]
Hi, I found that logrotate doesn't remove rotated files after reducing value for 'rotate' parameter in config. Only in case of 'rotation' conditions are met(or force flag is used), then amount of rotated files is reduced. 

Here is simple config example which I used in test:
```
/home/kovtuv/lrotate/cloud-init.log {
  rotate 4
  size 242880
  maxage 60
  missingok
  copytruncate
  nocreate
  nosharedscripts
  compress
  dateext
  dateformat .%Y%m%d-%H%M%S
  compresscmd /bin/gzip
  delaycompress
}
```
ver: logrotate 3.14.0

Can this behavior be fixed?

**Comment by kdudka** [comment]
I am afraid this is the expected behavior.  How often do you change the configuration?

I would suggest to just run `logrotate --force ...` after changing the configuration if you expect it to take effect immediately.
