### ISSUE TITLE
logrotate-3.14/CentOS 8.3 gzip: stdin: file size changed while zipping

### ISSUE THREAD

**Issue by th-hummel** [logrotate/logrotate#417]
Hello,

I'm using `logrotate-3.14.0-4.el8.x86_64` on `CentOS 8.3 x86_64`. I recently changed an included config file for one logfile only in the following manner:
```
/var/log/cluster/foo.log
{
    hourly
    dateformat -%Y%m%d%H%M%S
    maxsize 15G
    create 0644 root root
    rotate 30
    missingok
    compress
    dateext
    postrotate
        /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
```
I first got confused by this version manual which uncompletely described the `size` semantic (and described the mutual exclusiveness in the `[max|min]size` sections only but saw it was patched here in the repo for the latest version. So I think the configuration above correctly implements and `OR` between a **size** and a **date** rotation criteria. 

My understanding was that, for it to make sense, I'd still have to schedule `logrotate` actual run at a frequency less than `hourly`. So what I did was:

- add an `jobs.deny` to prevent `anacon` to `run-parts` `/etc/cron.daily/logrotate`
- create an `/etc/cron.d/logrotate` `crontab` running `/etc/cron.daily/logrotate` every minute

Since this change I regularily (but not always) have the following error message:
```
error: Compressing program wrote following message to stderr when compressing log /var/log/cluster/foo.log-20210818040001:
gzip: stdin: file size changed while zipping
```
I cannot figure out why since:

- only rsyslog and logrotate handle the log files (no process is writing directly to it)
- I don't think (or see how) multiple logrotate processes run concurrently

So, I may use `delaycompress` but in my understanding I should not have to. Or is it possible for the `SIGHUP` handler to come a little too late thus leading to some race condition between fd closing and `gzip` ?
Can `delaycompress` be needed in a traditionnal `syslog` `SIGHUP` setup ?

Or maybe I'm just missing something obvious.

What do you think and what do you think I could do to catch what exactly happens ?

Thanks for your help

--
Thomas HUMMEL

**Comment by th-hummel** [comment]
Sorry, to be precise it happened (for now at least) while I stated incorrectly a count of 20 (thus making logrotate have to drop some files after 20 rotations). I can't see why this would matter for this issue though.

**Comment by cgzones** [comment]
Without `delaycompress` the compression takes place before the execution of the `postrotate` block.
Thus during compression rsyslog still logs to `/var/log/cluster/foo.log` and if the log is quite big and thus the compression takes some time, new log messages might get emitted.
