### ISSUE TITLE
removeLogFile not working

### ISSUE THREAD

**Issue by jjproe** [logrotate/logrotate#42]
I dont found a 'unlink' in this Function..
logrotate debugging say's 'removing /var/log/messages-20160201.bz2' but really not delete the File.
I insert in removeLogFile -> unlink(name) and works fine..

**Comment by kdudka** [comment]
> I dont found a 'unlink' in this Function..

Sure, this is expected.  The actual ```unlink()``` call is in the ```shred_file()``` function.  It should be called if you are not in a debug mode and did not use the ```shred``` option in your configuration.
