### ISSUE TITLE
behavior of maxage setting

### ISSUE THREAD

**Issue by mat-m** [logrotate/logrotate#421]
Hello

I have this config
```
/opt/oracle/app/db/19.3.0.0.0/rdbms/audit/*.aud {
  daily
  rotate 1
  maxage 7
  missingok
  firstaction
     find /opt/oracle/app/db/19.3.0.0.0/rdbms/audit -type f -empty -print -delete
  endscript
}
```

The `firstaction` is used to remove empty files because there are many and it's slow the operations in the directory.

The audit folder contents is currently:
```
ls -lrth
total 580M
-rw-r----- 1 oracle users   894 Aug 17 10:50 ORATST70_ora_10000_20210817105017474350644340.aud-20210827
-rw-r----- 1 oracle users   894 Aug 17 10:50 ORATST70_ora_10133_20210817105040602809344684.aud-20210827
-rw-r----- 1 oracle users   894 Aug 17 10:50 ORATST70_ora_10158_20210817105042683659607966.aud-20210827
-rw-r----- 1 oracle users   894 Aug 17 10:51 ORATST70_ora_10776_20210817105116801591503539.aud-20210827
-rw-r----- 1 oracle users   894 Aug 17 10:51 ORATST70_ora_10796_20210817105117875156125236.aud-20210827
[...]
-rw-r----- 1 oracle users   894 Sep  7 03:06 ORATST70_ora_20828_20210907030635183415105529.aud-20210908
-rw-r----- 1 oracle users   894 Sep  7 03:06 ORATST70_ora_20846_20210907030635308260537807.aud-20210908
-rw-r----- 1 oracle users   894 Sep  7 03:06 ORATST70_ora_20853_20210907030636190594465621.aud-20210908
-rw-r----- 1 oracle users   894 Sep  7 03:06 ORATST70_ora_20887_20210907030646390088543270.aud-20210908
-rw-r----- 1 oracle users   894 Sep  7 03:08 ORATST70_ora_22062_20210907030830718391296673.aud
-rw-r----- 1 oracle users   894 Sep  7 03:10 ORATST70_ora_23469_20210907031008848807730816.aud
-rw-r----- 1 oracle users   894 Sep  7 03:10 ORATST70_ora_23515_20210907031009926737784636.aud
[...]
-rw-r----- 1 oracle users   892 Sep  8 14:36 ORATST70_ora_9545_20210908143635292233288664.aud
-rw-r----- 1 oracle users   892 Sep  8 14:36 ORATST70_ora_9551_20210908143635334819412432.aud
-rw-r----- 1 oracle users   892 Sep  8 14:36 ORATST70_ora_9560_20210908143636354937617713.aud
```

I extracted some lines from `/var/lib/logrotate/logrotate.status`

```
"/opt/oracle/app/db/19.3.0.0.0/rdbms/audit/ORATST70_ora_10000_20210817105017474350644340.aud" 2021-8-28-3:20:22
[...]
"/opt/oracle/app/db/19.3.0.0.0/rdbms/audit/ORATST70_ora_20887_20210907030646390088543270.aud" 2021-9-8-3:42:9
[...]
"/opt/oracle/app/db/19.3.0.0.0/rdbms/audit/ORATST70_ora_22062_20210907030830718391296673.aud" 2021-9-8-3:0:0
```

My view is:
- About **rotate** : it seems to work well but I was surprised to see the non-rotated file in the `logrotate.status` file. I guess that the date limit is the start of logrotate, which may explain why 3:06 file is rotated and not 3:08 file. but I would not have expected the file to be in the status file.
- About **maxage**: First file in ls output is timestamped as 20210827, and marked in status file as 2021-8-28, so I would expect `maxage 7` to remove it

My questions are:
- rotate: Can you confirm that the file being in logrotate.status has no impact on its further management by logrotate ?
- maxage: Didi I miss something in the config or in the purpose of this parameter ? I have a doubt in my understanding of the sentence ` The age is only checked if the logfile is to be rotated.` in the man page.

**Comment by kdudka** [comment]
Which version of logrotate are you using?

Issue #301 was fixed in `logrotate-3.17.0`.  I cannot see `dateext` in the configuration you pasted but I am not completely sure whether you are using it or not.

**Comment by mat-m** [comment]
`logrotate 3.8.6` per RH 7.9
`dateext` defined in default config. You can also see in the `ls` output that logrotate suffixes are date-based.

**Comment by kdudka** [comment]
Could you please check whether `logrotate-3.18.1` works any better?

**Comment by mat-m** [comment]
@kdudka I could setup a fedora 35 vm for this, to test further. I will try to do it before end of year.

My production systems RH7.7+ will stay with logrotate 3.8.
Do you have a working config in 3.8 to delete files older than 7 days ?

**Comment by kdudka** [comment]
As far as I know, the only config files we maintain upstream are the `test-config.*.in` files in the `test` directory.  `test-config.86.in` was added specifically to test `maxage` in combination with `dateext`.
