### ISSUE TITLE
State file is updated even when log rotate fails

### ISSUE THREAD

**Issue by phuzz** [logrotate/logrotate#422]
(This issue is triggered by the way the systemd service file for logrotate is written. Because `ProtectSystem=full` is set, logrotate cannot alter any files in /usr. I'm guessing this is by design, and it can be worked around by adding the line `ReadWritePaths=/path/to/log` in the logrotate.service file. I do question that design, but that's not the bug I've run into.
(If you run logrotate manually then it rotates the logs normally with no errors, which you can imagine made tracking this down _particularly fun_))

I'm trying to rotate the logs of a program which are stored in `/usr/local/till/till_logs/`, as noted above, logrotate will fail, writing an error into the systemd journal:
```
Sep 01 00:00:01 lewes02 systemd[1]: Starting Rotate log files...
Sep 01 00:00:01 lewes02 logrotate[1001656]: error: error renaming /usr/local/till/till_logs/till_output.txt.12.gz to /usr/local/till/till_logs/till_output.txt.13.gz: Read-only file system
Sep 01 00:00:01 lewes02 systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Sep 01 00:00:01 lewes02 systemd[1]: logrotate.service: Failed with result 'exit-code'.
Sep 01 00:00:01 lewes02 systemd[1]: Failed to start Rotate log files.
```
However, the state file marks the log as having been rotated:
```"/usr/local/till/till_logs/till_output.txt" 2021-9-1-0:0:1```
Even though the file(s) have not been rotated.
I'd expect that if logrotate failed, that it would not update the state file.

**Comment by cgzones** [comment]
The timestamp in the statefile represents the time of the last rotation attempt, not the last successful rotation.

> Yes, it is the time when the last rotation was triggered (assuming logrotate was able to write the state).

_Originally posted by @kdudka in https://github.com/logrotate/logrotate/issues/223#issuecomment-415571750_

**Comment by phuzz** [comment]
So it's by design then, ok.
It might be worth adding something to the documentation to explain that the state file shows when logrotate last _attempted_ to run, not when it was last successful.
Also, that for users running systemd, logrotate is limited in what directories it can run.

**Comment by kdudka** [comment]
@phuzz Sounds like a good idea.  Could you please open a pull request for that?

**Comment by phuzz** [comment]
I guess I asked for that :/
OK, just to be clear, the documentation is all in the `man` page in `logrotate.8.in` yes? I'll have a read through and find a good place to add the information.

**Comment by phuzz** [comment]
I've created a pull request, I hope it's acceptable.
https://github.com/logrotate/logrotate/pull/423
