### ISSUE TITLE
Error in logrotate: free(): invalid next size (fast)

### ISSUE THREAD

**Issue by viktornonov** [logrotate/logrotate#43]
logrotate 3.8.7 crashes with Error in `logrotate': free(): invalid next size (fast): 0x00000000013f3450

config:

```sh
/var/www/log/*log {
  su root root
  copy
  rotate 5
  dateext
  dateformat -%Y-%m-%d-%s-server01
  daily
  compress
  lastaction
    scp /var/www/log/*.log-* remoter@12.34.56.789:archives/
    rm /var/www/log/*.log-*.gz
  endscript
}
```

Running it through:

```sh
logrotate -d -f config
```

Output:
```sh
rotating log /var/www/log/random.log, log->rotateCount is 5
Converted ' -%Y-%m-%d-%s-server01' -> '-%Y-%m-%d-%s-server01'
dateext suffix '-2016-06-27-1467068778-server01'
glob pattern '-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-server01'
glob finding old rotated logs failed
copying /var/www/log/random.log to /var/www/log/random.log-2016-06-27-1467068778-web002
Not truncating /var/www/log/random.log
compressing log with: /bin/gzip
*** Error in `logrotate': free(): invalid next size (fast): 0x00000000013f3450 ***
```

The random.log file is opened by a ruby process in the following way:
```ruby
      logfile = File.open('./log/random.log', 'a')
      logfile.sync = true
      _logger = Logger.new(logfile)
      _logger::info("\nAdding some junk")
```

Disabling the compress option in the config gives no errors in 3.8.7.

__I built 3.9.2 from source and it seems that the problem is fixed__. I'm posting this because Ubuntu 14.04 LTS has logrotate 3.8.7 in its repos by default.
 
Feel free to close this if the problem is known.

**Comment by kdudka** [comment]
This could have been fixed by 768b23c0bd94f973abf108f6e2cf4138c426f140.  Please verify.

**Comment by viktornonov** [comment]
@kdudka Verified. Fails with https://github.com/logrotate/logrotate/commit/0db4223f20d33e219eed27ddec2839f82775f73f, works with https://github.com/logrotate/logrotate/commit/768b23c0bd94f973abf108f6e2cf4138c426f140

Thanks.

**Comment by kdudka** [comment]
Perfect.  Thanks for confirmation!
