### ISSUE TITLE
Tabooext and vim .swp files

### ISSUE THREAD

**Issue by th-hummel** [logrotate/logrotate#434]
Hello,

I'm using `logrotate-3.14.0-3.el8.x86_64` on `RHEL 8.2 x86_64` running it every minute which let the following issue more likely to occur:

when `vim`-editing a configuration file in the included `logrotate.d/` directory, the file was considered instead of being ignored as I would have expected since `.swp` is a default member of the `tabooext` list.

My guess is this is because the `.swp` file itself starts with a dot (ex: `.config-file.swp`). As a matter of fact, using ```tabbopat + .*``` before the include directive worked.

Am I correct ? If so this an expected behavior ?

Thanks for your help

--
Thomas HUMMEL

**Comment by kdudka** [comment]
Yes, we might consider adding it to the default configuration file upstream.  This is a common problem I think.

For example,  Gentoo Linux patches logrotate's source code to make hidden files ignored: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/logrotate/files/logrotate-3.15.0-ignore-hidden.patch?id=42cd5f7e24afe8d23a477e14a90b968dd57334ea

**Comment by th-hummel** [comment]
> Yes, we might consider adding it to the default configuration file upstream. This is a common problem I think.
> 
> For example, Gentoo Linux patches logrotate's source code to make hidden files ignored: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/logrotate/files/logrotate-3.15.0-ignore-hidden.patch?id=42cd5f7e24afe8d23a477e14a90b968dd57334ea

Ok. Thanks. using taboopat is fine for me.

Thanks again for your help

--
Thomas HUMMEL

**Comment by th-hummel** [comment]
Also, slightly related: I cannot find in the man any hint of what pattern grammar/syntax is allowed. I guess this is the same as in the shell ?

Thanks.

--
Thomas HUMMEL

**Comment by kdudka** [comment]
Yes, logrotate uses `fnmatch(3)` with the `FNM_PERIOD` flag for matching the patterns: https://github.com/logrotate/logrotate/blob/d7e45c17c08c1c408f3c63983bdab03e2273cbec/config.c#L477

**Comment by th-hummel** [comment]
Thanks

You can close this issue.

--
Thomas HUMMEL
