### ISSUE TITLE
Logrotate every minute

### ISSUE THREAD

**Issue by th-hummel** [logrotate/logrotate#435]
Hello,

I'm using `logrotate-3.14.0-3.el8.x86_64` on `RHEL 8.2 x86_64` on both stateful (installed on disk) and stateless (`PXE`'d in RAM only) nodes. On the latter for ramdisk space reason rotation criteria is `maxsize` and rotation is `cron`'ed every minute
.
As default distribution is to run `logrotate` through `anacron` and in a daily manner by defaults, I did my setup like this:

- keep the `logrotate` shell wrapper in `/etc/cron.daily/logrotate`
- deny its `run-parts` execution with `/etc/cron.daily/jobs.deny` (`anacontab` instructs to run daily jobs through `run-parts`)
-  set up the regular `crontab` `/etc/cron.d/logrotate` like this:   `* * * * root /etc/cron.daily/logrotate`
 
For some reason I've got a stateful node setup like described above and I **sometime** receive **2** mails with the same date (00:01) complaining about skipping some files because, because of the `dateext` suffix, the destination file already exists (which is true)
ex:`error: destination /var/log/xcat/xcat.log-20220210 already exists, skipping rotation`

I'm having a hard time figuring out why (I don't think rotation takes more than one minute and even if it was the case I'm not sure how it would be supposed to behave). So I've got the following questions to be able to investigate further by myself:

- does `logrotate` have any locking mechanism to prevent multiple instances running concurrently ? (is it technically possible that 2 `logrotate` binaries run at the same time ?)
- is the `satus file` written all at once or updated for each rotated file one at a time when it is rotated ? is it updated before `postrotate` scripts ?
- I may be mistaken but it seems to me that even when skipping because of already existing destination, the `status file` timestamp is updated for the corresponding file (which does not seem to be the case when I tested on an Ubuntu running `3.14.0` too (no -f appears on the RHEL wrapper) where no rotation gave no timestamp update
- I also did a silly test where I
   - manually updated one file timestamp to ensure its rotation
   - ran `logrotate` binary with a `sleep 120` in the postrotate script for that file
   - manually updated another timestamp to ensure another file rotation
   - ran a second `logrotate` instance in the hope it would complain about the first file destination existed but would rotate the second one and, to my surprise this second instance did exit after complaining about the first file already rotated
   - 
  When a file is skipped, other files should be rotated if possible right ? I mean for the same block in config file like:
   ```
   file1
   file2
   {
   ...
   }

Thanks for your help

--
Thomas HUMMEL

**Comment by kdudka** [comment]
Yes ,it looks like there are two instances of logrotate running in parallel sometimes.  The state file is read upon start of logrotate and written upon exit.  We have implemented a locking mechanism exactly for such cases but it was introduced in `logrotate-3.17.0`.  `logrotate-3.14.0-3.el8` does not support any locking.

**Comment by th-hummel** [comment]
I forgot to close the issue.
Thanks again for your answer
