### ISSUE TITLE
switch_user_permanently cause a serious problem

### ISSUE THREAD

**Issue by xhuacmer** [logrotate/logrotate#439]
I installed Ceph in my computer. However, when I run the comand "logrotate -vf /etc/logrotate.conf",  logrotate failed.
After I invenstigate this problem. because there is one configuration item "su root ceph" which is RCA.

I want to know what the backgroud is  testing the "setuid(ROOT_UID" in the switch_user_permanently,which causes this problem。

**Comment by kdudka** [comment]
This was introduced in commit a0b05e42a590efa3e575dd2001b6aa390a79c769 which refers to:
https://wiki.sei.cmu.edu/confluence/display/c/POS37-C.+Ensure+that+privilege+relinquishment+is+successful

**Comment by xhuacmer** [comment]
> This was introduced in commit [a0b05e4](https://github.com/logrotate/logrotate/commit/a0b05e42a590efa3e575dd2001b6aa390a79c769) which refers to: https://wiki.sei.cmu.edu/confluence/display/c/POS37-C.+Ensure+that+privilege+relinquishment+is+successful

Got it, thanks for you clarification!

**Comment by kdudka** [comment]
Does it mean that logrotate works as expected?  Or should we somehow improve its code or documentation?
