### ISSUE TITLE
typo: misinze->minsize

### ISSUE THREAD

**Issue by dagrh** [logrotate/logrotate#44]
Hi,
  See logrotate.c from commit 3d91c5b, this looks like a simple typo to me:

        if (log->minsize && sb.st_size < log->minsize) {
            state->doRotate = 0;
            message(MESS_DEBUG, "  log does not need rotating "
      ----->>>   "('misinze' directive is used and the log "
                     "size is smaller than the minsize value");

s/misinze/minsize/

**Comment by glensc** [comment]
duplicate: #32

**Comment by kdudka** [comment]
Thanks for the report!
