### ISSUE TITLE
[Feature Request] add option to drop rotated file from cache

### ISSUE THREAD

**Issue by Loader009** [logrotate/logrotate#440]
The rotated files are kept in RAM cache after being rotated.
With a system which is online for 30+ days and daily (compressed) logfiles with the size of 70+ MB, it would be about 2.1 GB purely for old cached logfiles.
Currently I use some script in postrotate, to circumvent the caching.

For debugging, use fincore to see if the file is in cache:
https://serverfault.com/questions/278454/is-it-possible-to-list-the-files-that-are-cached

To drop the cached file from cache, use e.g. dd:
https://unix.stackexchange.com/questions/36907/drop-a-specific-file-from-the-linux-filesystem-cache

**Comment by kdudka** [comment]
The operating system kernel will remove the files from cache as soon as it needs the memory for something else.

**Comment by Loader009** [comment]
That's correct - but afaik journald (from systemd) also removes their files from cache.
I think (I haven't experimented on this), in case of VMs the files won't be flushed if the hypervisor is short on memory.
It also ruins the statistics for the VM, to see the overall RAM usage.

Those files won't be needed except for special cases and debugging.
I think an option to remove them from cache is useful to keep a low RAM profile.
