### ISSUE TITLE
logrotate does not ever recover from a corrupted statefile

### ISSUE THREAD

**Issue by khays-biamp** [logrotate/logrotate#45]
Discovered in 3.8.7, confirmed by inspection in 3.9.1.

If the statefile becomes corrupted, for any reason, logrotate immediately exits, and log rotation stops.  This is particularly bad in embedded devices that depend on limiting the sizes of logfiles.

To recreate, edit the statefile with vi, and either set a date to a bad value, or corrupt the first line.

On the next execution of logrotate, it error exits with error=1, and makes no attempt to recover, which means it will continue to error out, forever.

We patched our local version to recreate the statefile with only the version header when this occurs, which seems to workaround the problem in a simple fashion.

It might be better to simply remove the statefile if it is corrupt.

Since the patch is neither elegant, nor against the latest version, I have not attached it.

**Comment by kdudka** [comment]
Thanks for the report!  There has already been an attempt to fix it: https://github.com/logrotate/logrotate/commit/r3-7-8~11

Unfortunately, it did not work correctly in all cases.  So it was reverted a few releases later: https://github.com/logrotate/logrotate/commit/r3-8-5~20

So we need to write a better patch to fix this properly...

Do you have any idea why the file gets corrupted in your case?

**Comment by khays-biamp** [comment]
It appears the metadata for the file was written before the file contents were written, so the file has an appropriate length, but no data sectors were written, so the file file has no extents, and the contents are returned as nulls, which is correct behavior for sparse files.

As for why, we believe it to be a bug in the underlying file system, which is UBIFS.

We’re still chasing it.

Kirk Hays •  Embedded Software Engineer
Biamp Systems  •  9300 SW Gemini Drive, Beaverton, OR 97008
www.biamp.com<http://www.biamp.com/>  •  tel. +1.503.641.9192  •  fax +1.503.626.0281

**Comment by mattghali** [comment]
Please consider recovering automatically from a corrupted statefile. The manual recovery process invariably is to delete the statefile and re-run logrotate; but we find out about the failure by being paged at the middle of the night because a disk has filled.

If you're not completely comfortable with this solution, would you consider making it an opt-in via config or cmdline arg?

thanks!

**Comment by khays-biamp** [comment]
Since others are having the same problem, and in hopes of a better fix, I've attached our kludgy patch.
[biamp_robust_statefile.txt](https://github.com/logrotate/logrotate/files/727710/biamp_robust_statefile.txt)

**Comment by kdudka** [comment]
Please have a look at my proposal in the ```recover-state``` branch:
https://github.com/logrotate/logrotate/compare/recover-state

Any feedback is appreciated!

**Comment by kdudka** [comment]
@khays-biamp @mattghali is there anything I can do to help you with testing the proposal?

**Comment by khays-biamp** [comment]
I am satisfied with my solution, do not have time to help with a more permanent solution, sorry.

Kirk Hays •  Embedded Software Engineer
Biamp Systems  •  9300 SW Gemini Drive, Beaverton, OR 97008
www.biamp.com<http://www.biamp.com/>  •  tel. +1.503.641.9192  •  fax +1.503.626.0281
