### ISSUE TITLE
LOGROTAE PERMISSION DENIED ISSUE when validating the config file.

### ISSUE THREAD

**Issue by Takou-DevAp** [logrotate/logrotate#452]
Hi everyone, 
here is my config file and i did not change anything in the /etc/logrotate.d directory
When i installed logrotate for the first time and executed the command logrotate -f /etc/logrotate.conf
everything worked fine but now that I've changed the config file, even with the old configuration i get the same output
Using a Raspberry pi with Debian distribution.

config file content:
```
#______START______

compress
daily
rotate 24
copytruncate
dateext
missingok
maxsize 10M
include /etc/logrotate.d

//Configuration for docker containers logs on edge devices

/var/lib/docker/containers/*/*-json.log{

//Delay the compression to the next rotation.
delaycompress
do not rotate if the logs file is empty
notifempty

}

//Configuration for aziot-edge runtime logs on edge devices

/var/log/aziot-edged/aziot-edged.log{

 //Delay the compression to the next rotation.
delaycompress
 //Do not rotate if the logs file is empty
notifempty

}

#_____END____________
```

When i execute thefollowing command: logrotate -f /etc/logrotate.conf
Here is the outpout:
```
error: /etc/logrotate.conf:46 duplicate log entry for /var/log/iotedge/iotedge.log
error: /etc/logrotate.conf:57 duplicate log entry for /var/log/aziot-edged/aziot-edged.log
error: error opening /var/log/alternatives.log: Permission denied
error: error opening /var/log/apt/term.log: Permission denied
error: error opening /var/log/apt/history.log: Permission denied
error: error opening /var/log/btmp: Permission denied
error: error opening /var/log/cups/access_log: Permission denied
error: error opening /var/log/dpkg.log: Permission denied
error: error opening /var/log/syslog: Permission denied
error: error opening /var/log/daemon.log: Permission denied
error: error opening /var/log/wtmp: Permission denied
error: error creating output file /var/lib/logrotate/status.tmp: Permission denied
```

Can someone help me out ?

**Comment by kdudka** [comment]
You need to go through the errors one by one and fix them.  In particular, you need to check the ownership and mode on the files and directories that logrotate complains about, and figure out why logrotate fails to access them.

**Comment by Takou-DevAp** [comment]
> You need to go through the errors one by one and fix them. In particular, you need to check the ownership and mode on the files and directories that logrotate complains about, and figure out why logrotate fails to access them.
