### ISSUE TITLE
How to use logrotate for removal of old log files only

### ISSUE THREAD

**Issue by penguinpee** [logrotate/logrotate#453]
I tried to configure logrotate for certbot. Certbot creates a new log file every time it's run and rotates old log files like logrotate does with a numeric extension.

`ls -lt /var/log/letsencrypt`:

```bash
-rw-r--r--. 1 root root  2890 Jul 10 21:04 letsencrypt.log
-rw-r--r--. 1 root root  2890 Jul 10 07:52 letsencrypt.log.1
-rw-r--r--. 1 root root     0 Jul 10 07:52 letsencrypt.log.2
-rw-r--r--. 1 root root  2890 Jul  9 10:37 letsencrypt.log.4
-rw-r--r--. 1 root root  2890 Jul  8 03:23 letsencrypt.log.5
-rw-r--r--. 1 root root  2890 Jul  7 22:28 letsencrypt.log.6
-rw-r--r--. 1 root root  2890 Jul  7 04:37 letsencrypt.log.7
-rw-r--r--. 1 root root  2890 Jul  6 19:03 letsencrypt.log.8
-rw-r--r--. 1 root root  2890 Jul  6 09:55 letsencrypt.log.9
-rw-r--r--. 1 root root  2890 Jul  5 23:42 letsencrypt.log.10
-rw-r--r--. 1 root root  2890 Jul  5 03:42 letsencrypt.log.11
-rw-r--r--. 1 root root  2890 Jul  4 15:35 letsencrypt.log.12
-rw-r--r--. 1 root root  2890 Jul  4 02:46 letsencrypt.log.13
-rw-r--r--. 1 root root  2890 Jul  3 23:36 letsencrypt.log.14
-rw-r--r--. 1 root root  2890 Jul  3 07:31 letsencrypt.log.15
-rw-r--r--. 1 root root     0 Jul  3 07:31 letsencrypt.log.16
-rw-r--r--. 1 root root  2890 Jul  2 09:32 letsencrypt.log.18
```

Initially, I used the following configuration for certbot:

```
/var/log/letsencrypt/*.log {
    rotate 0
    weekly
    missingok
    maxage 14
    nocreate
    nocompress
    nodateext
    start 1
}
```

But that didn't do what I intended. The gaps in the numbering above and the empty log files are result of that configuration and certbot's internal log rotation.

I changed the configuration using `rotate -1`:

```
/var/tmp/letsencrypt/*.log {
    rotate -1
    daily
    missingok
    maxage 14
    nocreate
    nocompress
    nodateext
    start 1
}
```

I tested it on a copy of the directory. That worked almost as intended. Except, the log files are still rotated. `letsencrypt.log` becomes `letsencrypt.log.1`. Using `create` would leave behind an empty `letsencrypt.log`, which would then be rotated immediately by certbot the next time it's run.

The above behavior is acceptable, but I was wondering if there's a way of configuring logrotate to not rotate at all, but just clean old log files based on `maxage`. If not, would it be possible to extend `rotate` to inhibit rotation, but still have the cleaning parts run, like `norotate` or `rotate no`?

**Comment by cgzones** [comment]
The `notifempty` directive stops rotation of empty log files.
Otherwise maybe `find /path/to/logdir/ -mtime +14 -execdir rm {} \;` might be an alternative?

**Comment by penguinpee** [comment]
> The `notifempty` directive stops rotation of empty log files.

Yes. But certbot itself does not leave empty log files. It just likes to write to a new log file whenever it's run, rotating everything in the log directory in the process.

> Otherwise maybe `find /path/to/logdir/ -mtime +14 -execdir rm {} \;` might be an alternative?

Yeah, thinking about it, logrotate might not be the tool for the job, since certbot does the rotating itself. It's just not cleaning up, ever. Maybe I should report this to the developers of certbot instead.
