### ISSUE TITLE
Add option to "wait until lock can be obtained" i.e. `--wait-for-lock`?

### ISSUE THREAD

**Issue by raoulbhatia** [logrotate/logrotate#457]
Following up on #295 and #297 (Thanks for implement this!)
I'd like to ask if an enhancement like `--wait-for-lock` would make sense.

Scenario:
1. We'd like to tap into the global statefile i.e. `/var/lib/logrotate/status` i.e. to avoid confusion and error when having separate status file
2. There might be several cronjobs set up to run every full hour, but managed via separate cronjobs (or systemd timers)
3. It would be OK that they run in sequence, i.e. "as close as possible to the original timestamp".

Think about deploying your config into /etc/logrotate.d/ so that admins find the configuration easily;
but preventing logrotate erroring out due to "lock file exists"; or preventing multiple state files where you can get unexpected results when using
(a) a custom `logrotate -s ...` call vs.
(b) daily logrotate call from the distribution vs.
(c) accidential calls via `logrotate /etc/logrotate.d/someconfig`

Note: I did consider to implement `while locked; do sleep $RANDOM; done && logrotate /etc/logrotate.d/someconfig` i.e. by using "fuser" or "lslocks", but I can still imagine race conditions and/or hard to foresee corner cases.

Thanks,
Raoul

**Comment by kdudka** [comment]
While I suspect some users will shoot themselves in the foot, I am not against introducing such an option if its implementation is reasonably simple to maintain.

**Comment by raoulbhatia** [comment]
Yes, you can then i.e. have logrotates piling up in perhaps an unpredictable way :-)

**Comment by kdudka** [comment]
I have submitted a pull request to implement the option: https://github.com/logrotate/logrotate/pull/465
