### ISSUE TITLE
Logrotate Failures 

### ISSUE THREAD

**Issue by adsharmaroku** [logrotate/logrotate#461]
Hello,

I am facing a weird issue with rotating aerospike log files with logrotate. The logrotate daemon is not able to rotate the log file on its daily run and it is working only when we use the force option manually 

Daily logrotate daemon is showing the below error in /var/log/messages: Even with the below failure, it updates the logrotate status file with the time of rotation and marks it as a success 

**Aug 25 05:46:54  logrotate: ALERT exited abnormally with [1]**
```
# cat /var/lib/logrotate/logrotate.status
logrotate state -- version 2
"/var/log/yum.log" 2022-8-9-19:0:0
"/var/log/aerospike/asgraphite.log" 2022-8-22-8:23:26
"/var/log/spooler" 2022-8-21-4:19:38
"/var/log/btmp" 2022-8-9-19:0:0
"/var/log/maillog" 2022-8-21-4:19:38
"/var/log/aerospike/aerospike.log" 2022-8-26-9:6:7
"/var/log/secure" 2022-8-21-4:19:38
"/var/log/messages" 2022-8-21-4:19:38
"/var/log/cron" 2022-8-21-4:19:38
```

 Below are the environment details:
```
root-01 log]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
root-01 log]#  rpm -qa | grep logrotate
logrotate-3.8.6-19.el7.x86_64
[
# cat /etc/logrotate.d/aerospike 
/var/log/aerospike/aerospike.log {
    daily
    rotate 90
    dateext
    compress
    olddir /var/log/aerospike
    missingok
    notifempty
    postrotate
        (kill -HUP `pgrep asd`) > /dev/null 2>&1 || true
    endscript
}
```
The only way log file rotate is working when we run the below command manually on the server
```
[root@01 aerospike]# sudo logrotate -f -v /etc/logrotate.d/aerospike
reading config file /etc/logrotate.d/aerospike
olddir is now /var/log/aerospike
Allocating hash table for state file, size 15360 B
Handling 1 logs
rotating pattern: /var/log/aerospike/aerospike.log  forced from command line (90 rotations)
olddir is /var/log/aerospike, empty log files are not rotated, old logs are removed
considering log /var/log/aerospike/aerospike.log
  log needs rotating
rotating log /var/log/aerospike/aerospike.log, log->rotateCount is 90
dateext suffix '-20220826'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
fscreate context set to system_u:object_r:unlabeled_t:s0
renaming /var/log/aerospike/aerospike.log to /var/log/aerospike/aerospike.log-20220826
running postrotate script
compressing log with: /bin/gzip
set default create context to system_u:object_r:unlabeled_t:s0
set default create context
[root@01 aerospike]# 
```
The strange part is if I put the same command in a cron or in a script, it is not working again.

There is no error when we run the logrotate in debug mode. You can see below example the run succeeds but log was not rotated
```
[root@02 aerospike]# logrotate -d /etc/logrotate.d/aerospike 
reading config file /etc/logrotate.d/aerospike
olddir is now /var/log/aerospike
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/aerospike/aerospike.log  after 1 days (90 rotations)
olddir is /var/log/aerospike, empty log files are not rotated, old logs are removed
considering log /var/log/aerospike/aerospike.log
  log needs rotating
rotating log /var/log/aerospike/aerospike.log, log->rotateCount is 90
dateext suffix '-20220826'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
fscreate context set to system_u:object_r:unlabeled_t:s0
renaming /var/log/aerospike/aerospike.log to /var/log/aerospike/aerospike.log-20220826
running postrotate script
running script with arg /var/log/aerospike/aerospike.log: "
        (kill -HUP `pgrep asd`) > /dev/null 2>&1 || true
"
compressing log with: /bin/gzip
[root@02 aerospike]# ls -ltr
-rw-rw-rw-. 1 root root  8903219 Aug 25 08:31 asgraphite.log-20220825.gz
-rw-r--r--. 1 root root 45696365 Aug 26 12:04 aerospike.log
[root@02 aerospike]# 
```

**Comment by adsharmaroku** [comment]
Thanks @kdudka , below are the details:

[root@3 aerospike]# logrotate -v /etc/logrotate.d/aerospike
reading config file /etc/logrotate.d/aerospike
olddir is now /var/log/aerospike
Allocating hash table for state file, size 15360 B
Handling 1 logs
rotating pattern: /var/log/aerospike/aerospike.log  after 1 days (90 rotations)
olddir is /var/log/aerospike, empty log files are not rotated, old logs are removed
considering log /var/log/aerospike/aerospike.log
  log does not need rotating (log has been rotated at 2022-8-26 8:51, that is not day ago yet)
set default create context
[root@3 aerospike]# 

This is expected because the logrotate cron tried to rotate in its daily run but failed to rotate the file:

I can see below error comes daily in /var/log/messages
Aug 23 05:46:54 logrotate: ALERT exited abnormally with [1]
Aug 24 05:46:54 logrotate: ALERT exited abnormally with [1]
Aug 25 05:46:54 logrotate: ALERT exited abnormally with [1]

You can see the compressed log files as below - All files were rotated through manual; command

[root@3 aerospike]# ls -ltr
total 597300
drw-r--r--. 2 root root     16384 Aug  9 14:46 lost+found
-rw-r--r--. 1 root root  11692101 Aug 14 12:07 aerospike.log-20220814.gz
-rw-r--r--. 1 root root  11263175 Aug 17 09:46 aerospike.log-20220817.gz
-rw-r--r--. 1 root root  19182846 Aug 22 08:31 aerospike.log-20220822.gz
-rw-rw-rw-. 1 root root 389591360 Aug 26 13:05 asgraphite.log
-rw-r--r--. 1 root root 162127578 Aug 26 13:05 aerospike.log
[root@3 aerospike]#

I have updated manually /var/lib/logrotate/logrotate.status and changed the date to Aug 25 and ran the below command again and it seems like it rotated the file as expected without force option 

[root@p3 aerospike]# logrotate -v /etc/logrotate.d/aerospike
reading config file /etc/logrotate.d/aerospike
olddir is now /var/log/aerospike
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/aerospike/aerospike.log  after 1 days (90 rotations)
olddir is /var/log/aerospike, empty log files are not rotated, old logs are removed
considering log /var/log/aerospike/aerospike.log
  log needs rotating
rotating log /var/log/aerospike/aerospike.log, log->rotateCount is 90
dateext suffix '-20220826'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
fscreate context set to system_u:object_r:unlabeled_t:s0
renaming /var/log/aerospike/aerospike.log to /var/log/aerospike/aerospike.log-20220826
running postrotate script
compressing log with: /bin/gzip
set default create context to system_u:object_r:unlabeled_t:s0
set default create context
[root@3 aerospike]# 


[root@3 aerospike]# ls -ls
total 455488
     4 -rw-r--r--. 1 root root      2720 Aug 26 13:06 aerospike.log
 11420 -rw-r--r--. 1 root root  11692101 Aug 14 12:07 aerospike.log-20220814.gz
 11000 -rw-r--r--. 1 root root  11263175 Aug 17 09:46 aerospike.log-20220817.gz
 18736 -rw-r--r--. 1 root root  19182846 Aug 22 08:31 aerospike.log-20220822.gz
 16488 -rw-r--r--. 1 root root  16880602 Aug 26 13:06 aerospike.log-20220826.gz
380496 -rw-rw-rw-. 1 root root 389621065 Aug 26 13:06 asgraphite.log

Is there a way we can debug and find out why it is failing in the logrotate daily daemon

**Comment by kdudka** [comment]
If you run `logrotate -v ...` in the cron job, it should produce similar output.  I guess the cron daemon captures it and stores somewhere?  If not you can try to redirect the output in the cron job: `logrotate -v ... > /var/log/logrotate.log 2>&1`

**Comment by adsharmaroku** [comment]
Hi @kdudka 
It works as expected but isn't this is different because  it is failing through logrotate daily run 

[root@05 tmp]# crontab -l
1 14 * * * /sbin/logrotate -v /etc/logrotate.d/aerospike > /tmp/logrotate.log 2>&1

[root@05 tmp]# cat /tmp/logrotate.log 
reading config file /etc/logrotate.d/aerospike
olddir is now /var/log/aerospike
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/aerospike/aerospike.log  after 1 days (90 rotations)
olddir is /var/log/aerospike, empty log files are not rotated, old logs are removed
considering log /var/log/aerospike/aerospike.log
  log needs rotating
rotating log /var/log/aerospike/aerospike.log, log->rotateCount is 90
dateext suffix '-20220826'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
fscreate context set to system_u:object_r:unlabeled_t:s0
renaming /var/log/aerospike/aerospike.log to /var/log/aerospike/aerospike.log-20220826
running postrotate script
compressing log with: /bin/gzip
set default create context to system_u:object_r:unlabeled_t:s0
set default create context

[root@05 tmp]# ls -ls /var/log/aerospike/aerospike.log-20220826.gz 
43396 -rw-r--r--. 1 root root 44435593 Aug 26 14:00 /var/log/aerospike/aerospike.log-20220826.gz
[root@05 tmp]#

**Comment by kdudka** [comment]
I am not sure I understand.  If the daily run is triggered by the same script, it should also capture logrotate's output.  By analyzing the output, one can then figure out what happened.  Nevertheless, as I said, `logrotate-3.8.6` is quite old.  Many bugs have been fixed and the verbose output significantly improved since then.
