### ISSUE TITLE
unable to rotate logs with non root conf file

### ISSUE THREAD

**Issue by aakahuja** [logrotate/logrotate#462]
Logs are not rotating if I am using a non root user conf file.

-rw-r--r-- 1 alarmsys alarmsys      400 Aug 26 15:54 logrotate.conf

 logrotate  -f logrotate.conf
error: Ignoring logrotate.conf because the file owner is wrong (should be root or user with uid 0).

But if I change the owner of this to root. Things work fine. Any workaround for this?

**Comment by cgzones** [comment]
This is expected behavior.
Logrotate will execute commands specified in the configuration (e.g. `postrotate`), thus those files must not be able to be modified by foreign users to avoid privilege escalation attacks.
Either don't run logrotate as root or make the configuration files be owned by root (after verifying their content).

**Comment by aakahuja** [comment]
> This is expected behavior. Logrotate will execute commands specified in the configuration (e.g. `postrotate`), thus those files must not be able to be modified by foreign users to avoid privilege escalation attacks. Either don't run logrotate as root or make the configuration files be owned by root (after verifying their content).



Tried with user account also.. Still it is giving errors:
[alarmsys@CFPU-0(AAA129) /root]
# /usr/sbin/logrotate -f /home/alarmsys/logrotate.conf
error: error opening state file /var/lib/logrotate.status: Permission denied

**Comment by cgzones** [comment]
Logrotate needs access to its status file, which is by default */var/lib/logrotate.status*.
To use a different status file, which is recommend when not running as root and not targeting */etc/logrotate.conf*, use the `--state` command line option.
