### ISSUE TITLE
Logrotate wildcard fails on missing files with “missingok” AND “olddir”

### ISSUE THREAD

**Issue by xdsb** [logrotate/logrotate#469]
logrotate version 3.19.0
```
/etc/logrotate.d/ecs.conf
/var/log/ecs_* .log* {
su root root
rotate 3
hourly
olddir /var/log/ecs
size 512k
notifempty
nodateext
missingok
addextension .tmp
compress
}
```
when I ran "logroated -d ecs.conf" ,it returns
```
Mar 13 20:00:02 imx-6ul systemd[1]: Starting Rotate log files...
Mar 13 20:00:02  imx-6ul logrotate[895]: error: ecs.conf:21 error verifying olddir path /var/log/ecs: No such file or directory
Mar 13 20:00:02  imx-6ul logrotate[895]: error: found error in file ecs.conf, skipping
Mar 13 20:00:02  imx-6ul systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Mar 13 20:00:02  imx-6ul systemd[1]: logrotate.service: Failed with result 'exit-code'.
Mar 13 20:00:02  imx-6ul systemd[1]: Failed to start Rotate log files.
```

Also found this "https://github.com/logrotate/logrotate/commit/73493ec38c5e806fa66d8c3f13259775da6282d9" to Fix 'olddir' usage with wildcard in the middle of path in the pattern，but how about the wildcard, missingok and olddir ?

**Comment by kdudka** [comment]
I guess you need to use `createolddir ...` if you want logrotate to create the directory for you?

**Comment by xdsb** [comment]
Hi, kdudka, thank you for your replay, but it seems not working when I change the olddir to createolddir,  do you have any other comment?

**Comment by kdudka** [comment]
You cannot change `olddir` to `createolddir`.  You need to use both:
- `olddir` specifies where logs should be moved after rotation
- `createolddir` tells logrotate to create the directory (with the specified mode, owner, and group) in case it does not exist
