### ISSUE TITLE
Add flag to use zstd compression by default

### ISSUE THREAD

**Issue by eliv** [logrotate/logrotate#472]
Since zstd obsoletes gzip in both cpu & space efficiency it would be nice to have a flag to use zstd by default, and eventually make it the default.

**Comment by kdudka** [comment]
The configure script already takes the following options:
- `--with-compress-command=COMMAND`
- `--with-uncompress-command=COMMAND`
- `--with-compress-extension=EXTENSION`

I do not think we should change the default because it could break existing deployments.  Portability and backward compatibility is more important than performance in this case.

**Comment by cgzones** [comment]
Alternatively one can globally change the compression used, e.g. in */etc/logrotate.conf*, via the directives **compresscmd**, **uncompresscmd**, **compressext** and **compressoptions**.

**Comment by eliv** [comment]
That's why I suggested a new flag to change the default to allow old deployments to migrate at a slower pace. So, for example, for 2 or 3 releases the UseNewZstdDefault flag would be available but off by default, and then after sufficient time has passed this flag would then become the new default. This seems the easiest path to start migrating forward to something better that will effect a large chunk of the Linux ecosystem.

    On Friday, November 4, 2022 at 07:51:03 AM EDT, Kamil Dudka ***@***.***> wrote:  
 
 


The configure script already takes the following options:
   
   - --with-compress-command=COMMAND
   - --with-uncompress-command=COMMAND
   - --with-compress-extension=EXTENSION

I do not think we should change the default because it could break existing deployments. Portability and backward compatibility is more important than performance in this case.

**Comment by kdudka** [comment]
As explained above, you already have both compile-time and run-time options to change the default wherever you need to.  Introducing new options does not make any sense.

**Comment by eliv** [comment]
Let's say I'm a distribution packaging logrotate. I want to get rid of gzip since it's obsolete and a waste of time and money for future deployments, so I compile logroate to use zstd by default. This then works great for new deployments but then creates a lot of work for anyone upgrading an existing deployment if they want to preserve backwards compatibility. So a single flag to enable the new functionality would simultaneously help both use cases. It could be on by default for new deployments and then folks doing upgrades that don't want it can easily disable it in a single place without having to recompile or update dozens of config files. 

    On Friday, November 4, 2022 at 06:27:05 PM EDT, Kamil Dudka ***@***.***> wrote:  
 
 


As explained above, you already have both compile-time and run-time options to change the default wherever you need to. Introducing new options does not make any sense.

**Comment by kdudka** [comment]
@eliv You can put the new default to `/etc/logrotate.conf` provided by your distribution.  Fresh installations (or systems relying on distro-provided configuration) will use the new default whereas systems with a customized `/etc/logrotate.conf` will keep the old configuration until the configuration update is merged by the administrator.  In any case, this is something that needs to be solved on the distribution level.  Each distribution has its own mechanisms to handle changes in configuration files.

**Comment by eliv** [comment]
That's exactly the point, instead of every single distribution that packages logrotate having to make a custom change it would be far less work to provide a flag in a single place in logrotate. Additionally, the needed change would then be uniform across the ecosystem. It would also be far easier for the users to then change the configuration themselves should they want to.

    On Monday, November 7, 2022 at 07:56:32 AM EST, Kamil Dudka ***@***.***> wrote:  
 
 


@eliv You can put the new default to /etc/logrotate.conf provided by your distribution. Fresh installations (or systems relying on distro-provided configuration) will use the new default whereas systems with a customized /etc/logrotate.conf will keep the old configuration until the configuration update is merged by the administrator. In any case, this is something that needs to be solved on the distribution level. Each distribution has its own mechanisms to handle changes in configuration files.

**Comment by arekm** [comment]
btw. will logrotate cleanup old gz compressed files (when the times comes) if config gets changed (via compresscmd, uncompresscmd, compressext) to zstd or will it leave old gz logs there forever?
