### ISSUE TITLE
logrotate creates more rotated files then specified

### ISSUE THREAD

**Issue by GoTeamAnt** [logrotate/logrotate#476]
version: logrotate 3.14.0

These are the logfiles created by logrotate for a custom service called vsavi which writes into /tmp/log/vsavi.log:

```
*/tmp/log/2022-11-30-vsavi.log
*/tmp/log/2022-11-30-vsavi.log-20221201-0001
/tmp/log/vsavi.log
/tmp/log/vsavi.log-20221201-0901
/tmp/log/vsavi.log-20221201-1001
/tmp/log/vsavi.log-20221201-1101
/tmp/log/vsavi.log-20221201-1201
```

The files marked with * are additional unexpected files created by logrotate.

My configuration:

**/etc/logrotate.d/vsavi**
```
/var/log/*vsavi.log
/tmp/log/*vsavi.log
{
    su root root
    copytruncate
    dateformat -%Y%m%d-%H%M
    daily
    missingok
    maxsize 10M
    prerotate
        truncate -s \<10M $1
    endscript
}
```
**/etc/logrotate.conf** 
```
# see "man logrotate" for details
# rotate log files weekly
weekly

# keep 4 weeks worth of backlogs
rotate 4

# create new (empty) log files after rotating old ones
create

# use date as a suffix of the rotated file
dateext

# uncomment this if you want your log files compressed
#compress

# RPM packages drop log rotation information into this directory
include /etc/logrotate.d

# system-specific logs may be also be configured here.
```

logrotate is called every hour by cron.

Expectation: just create the 4 rotated files as specified with `rotate 4` no matter if it is triggered by maxsize or daily.
Is there a way to modify my configuration so that these additional files are not generated anymore?
Also I cannot find any documentation about the generated files with the prefixed date (marked with*).

**Comment by kdudka** [comment]
I do not think that `/tmp/log/2022-11-30-vsavi.log` was created by logrotate.

**Comment by GoTeamAnt** [comment]
Thanks, then the this vsavi service must be at fault.
Closing.
