### ISSUE TITLE
Default rotate count missing in documentation

### ISSUE THREAD

**Issue by sustefil** [logrotate/logrotate#507]
From `man logrotate` on my CentOS machine:

```
       rotate count
              Log files are rotated count times before being removed or mailed to the address specified in a mail directive. If count is 0, old versions are removed rather than rotated.
```

The default value is missing. 

Seems like the default is 1, can you please add it to the docupages?

https://github.com/logrotate/logrotate/blob/master/logrotate.c#L1644

Thanks!

**Comment by cgzones** [comment]
It's actually documented, see https://github.com/logrotate/logrotate/blob/eb94f32dcc585e31c880418d82c38521076e882a/logrotate.8.in#L233 , and set here: https://github.com/logrotate/logrotate/blob/eb94f32dcc585e31c880418d82c38521076e882a/config.c#L787

**Comment by sustefil** [comment]
Ah I see, I have a package older than 3 years ago (when the default was added to docu), sorry for the noise, closing.
