### ISSUE TITLE
Feature Request: Add option to timeout when waiting for state lock

### ISSUE THREAD

**Issue by z-image** [logrotate/logrotate#518]
Hello,

Thank you for your effort in maintaining logrotate :)

I currently have a standard logrotate setup that is invoked from cron.daily. Additionally, I have a cron.hourly script that checks various conditions and, on occasion, rotates one of the logs by calling `logrotate --force /etc/logrotate.d/$logrotate_conf`. Sometimes, this results in a collision with the daily cron, causing the following error:

```
error: state file /var/lib/logrotate/status is already locked
logrotate does not support parallel execution on the same set of logfiles.
```
I don't really require parallel execution; sequential execution would work just fine for my needs.

Currently, logrotate has two options relating to state file locking, -s/--state and --skip-state-lock. To address my situation, I propose a new option: --timeout-state-lock or --wait-state-lock. This would allow logrotate to wait (for a while) for the state file to become available, instead of immediately skipping the lock or exiting if it cannot acquire it.

Implementing this feature would add more flexibility to how logrotate is used and could potentially be beneficial to other users as well.

Best regards.

**Comment by cgzones** [comment]
Since 3.21.0 (c2921422fec73aa4ff128a1671d4bd9fbbca591c) the option `--wait-for-state-lock` is available, which waits indefinitely. Waiting with a timeout is (not yet) supported. Patches are welcome.
