### ISSUE TITLE
postrotate script not getting 2 arguments

### ISSUE THREAD

**Issue by JVD66** [logrotate/logrotate#527]
My postrotage script is definitely NOT getting 2 arguments, using Rocky RHEL8's  
logrotate-3.14.0-6.el8.x86_64 .

Making the script print out "$@" shows only one argument, the absolute pathname
of the Rotated Log .

This could be a manual page niggle - the manual page does state :
         "
              Normally, the absolute path to the log file is passed as the  first
              argument  to  the  script and the absolute path to the final ro‐
              tated log file is passed as the second argument to  the  script
         "    

Please amend the manual page or give postrotate scripts 2 arguments as documented. Thanks!

**Comment by cgzones** [comment]
The second argument is only provided since version 3.15 (see https://github.com/logrotate/logrotate/commit/f8356d6f719613d65a36f4b3779ae956adbc48a7) (and only in the `nosharedscripts` case); so you are probably referring to a manual page not matching your logrotate version.
