### ISSUE TITLE
RFE: Add .new, .old and .orig to `defTabooExts[]`

### ISSUE THREAD

**Issue by opty77** [logrotate/logrotate#528]
Please add .new, .old and .orig to `defTabooExts[]`.

**Comment by kdudka** [comment]
Sounds fine to me.  Could you please submit a pull request for it?  The commit message should explain how the files are created and why we should ignore them by default.

**Comment by opty77** [comment]
I was afraid of that. :-)

I have never created a PR yet nor basically used git manually so it would take some time if I finally decided to jump in.

I'm trying to solve chicken or the egg in [Slackware](https://www.linuxquestions.org/questions/slackware-14/requests-for-current-next-15-0-15-1-a-4175706801/page161.html#post6438882) but given the generality of extensions in question I believe that others might benefit too.

Maybe logrotate could even merge some list members into one like .dpkg-new, .rpmnew, .ucf-new and proposed .new into .*new but that seems rather brave I guess.

**Comment by kdudka** [comment]
I have created #532 to fix this.

**Comment by opty77** [comment]
BTW, what about the manual page?

I also noticed missing .bak there.

**Comment by kdudka** [comment]
Good point.  I have synchronized the man page, too.

**Comment by opty77** [comment]
@cgzones: Too small for [ChangeLog.md](https://github.com/logrotate/logrotate/blob/3.22.0/ChangeLog.md)?
