### ISSUE TITLE
Glob Patterns not function in logrotate

### ISSUE THREAD

**Issue by vincentyrl** [logrotate/logrotate#550]
I have this in /etc/logrotate.d/

I trie the logrotate execute in all but not in chec01

/tmp/echo/!(chec01)*.log

/tmp/echo/chec01.log
/tmp/echo/chec02.log
/tmp/echo/ush.log
/tmp/echo/colo.log

logrotate -fv crontab
I have this
rotating pattern: /tmp/echo/!(chec01)*.log  forced from command line (no old logs will be kept)
empty log files are not rotated, old logs are removed
considering log /tmp/echo/!(chec01)*.log
  log /tmp/echo/!(chec01)*.log does not exist -- skipping

**Comment by cgzones** [comment]
I don't think `!(chec01)` is a valid exemption syntax according to [glob(7)](https://manpages.debian.org/unstable/manpages/glob.7.en.html).
