### ISSUE TITLE
Ability to rotate every 5 minutes

### ISSUE THREAD

**Issue by tomfitzhenry** [logrotate/logrotate#56]
The most frequent logrotate is able to rotate is hourly, using the `hourly` directive.

I'd like to get logs off the box within 5 minutes, rather than 60 minutes, so it would be useful to rotate logs every 5 minutes.

**Comment by tomfitzhenry** [comment]
Workaround: Run `logrotate -f 5` every 5 minutes (via cron, or some such). The problem with this workaround is that it overrides `size`/`minsize`/`maxsize` and other directives.

**Comment by kdudka** [comment]
If I read the code correctly, using the ```size``` directive only should do what you need without having to use ```-f```.  You can run logrotate every 5 minutes and it will rotate the logs if their size exceeds the limit.  Is my analysis correct?
