### ISSUE TITLE
Question: is the main branch stable as a release tarball? 

### ISSUE THREAD

**Issue by flucrezia** [logrotate/logrotate#563]
Hello,
thanks for keeping up with the project.
Can I safely use the main branch for production? I use automatic builds from source code to generate configure and the other build scripts.

Many Thanks,
Francesco

**Comment by kdudka** [comment]
Generating your own configure script from what we maintain in the upstream git repository is fine but I would recommend to always use the snapshot with the latest release tag.  We try to keep the source code in the git repository stable all the time.  Nevertheless some issues are not reported by users (or distribution maintainers) until we publish a new tagged release.  Also security issues are seriously handled in the released versions of logrotate only.

**Comment by flucrezia** [comment]
Ok, you answered my question. I'll go with the release tag XD Thanks.
