### ISSUE TITLE
Error specifying compresscmd as /usr/bin/zip command

### ISSUE THREAD

**Issue by banjiuqingshan** [logrotate/logrotate#582]
When the logrotate is compressed in .zip format, an error message is displayed and the compressed file is renamed as -.The following is an example:
![image](https://github.com/logrotate/logrotate/assets/63209634/342cf0f8-3986-4748-a0a8-0e09f070b538)
![image](https://github.com/logrotate/logrotate/assets/63209634/d62edb7d-6536-4dc2-b0bd-d44b12d453e8)

**Comment by banjiuqingshan** [comment]
I think I got it. It may be that zip outputs the content to stderr.

**Comment by cgzones** [comment]
Any output from the compress command to stderr is treated as failure by logrotate.
