### ISSUE TITLE
Update verification instructions

### ISSUE THREAD

**Issue by atsampson** [logrotate/logrotate#611]
The new 3.22.0 release is signed with a different GPG key from the only one listed in the verification instructions in README.md.

It would be good practice for the project to announce explicitly when the key is being changed, otherwise there's no way to verify that the release is authentic - perhaps add this to the release process?

**Comment by cgzones** [comment]
Thanks for reporting; updated via https://github.com/logrotate/logrotate/commit/959377bb46e1095842b700386ecb79ea142d2d67.
