### ISSUE TITLE
Using renameat2() system call to avoid race?

### ISSUE THREAD

**Issue by piotr-dobrogost** [logrotate/logrotate#62]
Has there been any thought of using [renameat2()](http://man7.org/linux/man-pages/man2/renameat.2.html) system call to avoid race when rotating a file with `copytruncate` option?

**Comment by fumiyas** [comment]
I think `renameat2`(2) with `RENAME_EXCHANGE` exchanges only filenames in directory entries, thus it cannot be used for `copytruncate` replacement.

**Comment by piotr-dobrogost** [comment]
I think you are right. That's astonishing there's no race-free way to move contents of a file...
