### ISSUE TITLE
Question: does logrotate support uid and gid ?

### ISSUE THREAD

**Issue by cwrx777** [logrotate/logrotate#620]
Hi,

Does logrotate support specifying uid and gid numeric value when the username/group do not exist?

e.g.
```
/path/to/log/file.log {
    create 0640 1001 1001 
   ...
}
```

**Comment by cgzones** [comment]
Numeric user and group identifiers are supported since https://github.com/logrotate/logrotate/commit/d457d2b13c21e01725886478aa95dc2f518b8d2e in 3.18.0.

> when the username/group do not exist

The user/group must exist though on the system (checked via `getpwuid(3)`/`getgrgid(3)`).

**Comment by cwrx777** [comment]
I want to use logrotate in a container where the UID and GID are specified  externally, e.g .via Container Security context and I dont want to precreate the user in the image. 
My current work is around is [here.](https://github.com/cwrx777/logrotate/commit/67850d50aea453b4d5753ca99cad7ea78184ed6f)

**Comment by cgzones** [comment]
Could you take a look at #626?

**Comment by ghnp5** [comment]
> Numeric user and group identifiers are supported since [d457d2b](https://github.com/logrotate/logrotate/commit/d457d2b13c21e01725886478aa95dc2f518b8d2e) in 3.18.0.
> 
> > when the username/group do not exist
> 
> The user/group must exist though on the system (checked via `getpwuid(3)`/`getgrgid(3)`).

Hello.

I'm actually having an issue where logrotate is triggering an error because of `unknown user '1000'`, even though the user 1000 (and group 1000) does exist on the host.

Is that not supported in `logrotate 3.14.0` ?  (which is what AlmaLinux 8 has installed, for me)

Many thanks.
