### ISSUE TITLE
Bug when using `copytruncate` and `create` together

### ISSUE THREAD

**Issue by ernaniaz** [logrotate/logrotate#638]
Hello team!

I found a bug where when you use `copytruncate` and `create` together, logrotate ignores the `create` file mode and keeps the same mode the log file had before rotating.

To reproduce this issue:
```bash
echo -e '"./test.log" {\n    rotate 4\n    daily\n    copytruncate\n    create 0640\n}' > conf
echo -e 'logrotate state -- version 2\n"./test.log" 2000-8-9n' > state
rm -f test*
touch test.log
chmod 644 test.log
logrotate -v -s state conf
ls -l test*
```

If `copytruncate` is removed from the configuration, it works:
```bash
echo -e '"./test.log" {\n    rotate 4\n    daily\n    create 0640\n}' > conf
echo -e 'logrotate state -- version 2\n"./test.log" 2000-8-9n' > state
rm -f test*
touch test.log
chmod 644 test.log
logrotate -v -s state conf
ls -l test*
```

**Note**: I tested with logrotate 3.8.6, 3.14.0, 3.18.0 and 3.21.0.

**Comment by kdudka** [comment]
When `copytruncate` is in effect, the existing log file is not moved and a new log file is **not** created.  Hence, the `create` directive does not take any effect.  I do not think that the `create` directive should change permissions on existing log files.  So I am not sure how logrotate could be improved in this regard (other than clarifying this case in the documentation).

**Comment by ernaniaz** [comment]
You're right. I haven't verified newest [man page](https://github.com/logrotate/logrotate/blob/e4a833015eb5590cf86a6a78895ff399174ade4f/logrotate.8.in#L454). It says:
`When this option is used, the create option will have no effect, as the old log file stays in place.`

**Comment by kdudka** [comment]
Actually, the man page already contained this text 27 years ago: https://github.com/logrotate/logrotate/commit/b830ab10b33b94a72b1cf5ac2a27db1d87c3df40#diff-722930fb2346414c4bfdcf6a8257563337c7e8a97e2a03ef26125caf76bd239aR128

My bad that I did not look at the man page before replying...
