### ISSUE TITLE
can't execute a logrotate command in the section of postrotate 

### ISSUE THREAD

**Issue by edwardzxq1986** [logrotate/logrotate#647]
I have a logrotate conf as shown below to rotate the /mnt/pram1/logs/imessages , there is a postrotate in the conf file and a logrotate command is in the postrotate section.

![image](https://github.com/user-attachments/assets/a94fd61d-66bb-4356-bea6-fd38e9a7e65b)

the goal of this conf is rotate the imessages once the size is over 500k, in the postrotate it appends the imessages.2 to /FLASH/persist/logs/boot_current/pram1/logs/imessages, and then run "/usr/sbin/logrotate /etc/logrotate_flash.conf" to compress the imessage which is over 900k in the FLASH. 

![image](https://github.com/user-attachments/assets/03da9069-55f3-49a9-a9c1-2cf013fd0c83)

  It seems the "/usr/sbin/logrotate /etc/logrotate_flash.conf" in the postrotate is NOT executed at all when run "/usr/sbin/logrotate /etc/logrotate.d/logrotate_imessage.conf"  , the commands around the logrotate like 'touch /tmp/postrotate.afterrm' can be executed. 
However,  If I manually run "/usr/sbin/logrotate /etc/logrotate_flash.conf", it can work as expected.
the logrotate version is show below:
![image](https://github.com/user-attachments/assets/517505a9-0e2d-4d72-a6c4-05b6b2806427)

It looks strange why the logrotate in the postrotate can't be executed, anybody can help me on this problem? thanks

**Comment by cgzones** [comment]
These two nested logrotate instances will use the same state file, and the second instance can't acquire the lock on it.
You could run the nested logrotate with a custom state file (`--state`). (There is also `--skip-state-lock`.)

In general logrotate should provide output messages, which can also be enhanced by running with the `-v` option (and `-d` for simulation only).

**Comment by edwardzxq1986** [comment]
thanks @cgzones , I tried both options(--state and --skip-state-lock), and both are working as expected.
