### ISSUE TITLE
Doesn't delete logs with %Y in pattern

### ISSUE THREAD

**Issue by dkrand** [logrotate/logrotate#8]
We name our old logs with the pattern %Y-%m-%d but the old logs never get deleted. I'm pretty sure it is because of 
  https://github.com/logrotate/logrotate/blob/master/logrotate.c#L1256
Shouldn't that be "[0-9][0-9][0-9][0-9]"?  %Y expands to the 4 digit year, and the code only has 2 digits in the glob pattern.

**Comment by hanzz** [comment]
Unfortunately this is not the problem. That switch branch falls through to another case: where [0-9][0-9] is added. Can you provide -v (verbose) output from the case when old logs are not removed?
