### ISSUE TITLE
Request to have Logrotate more gracefully handle errors in its config

### ISSUE THREAD

**Issue by sc-perth** [logrotate/logrotate#81]
Don't get me wrong here, this is all my fault. That said it would have been nice if logrotate had handled this situation more gracefully.

Logrotate v3.10.0 will stop processing logrotate.conf directives after encountering a bad directive. This can (and did) result in large log files. I would like to request that this behavior be changed such that logrotate continues to process the remaining directives, if possible, instead of just exiting. Exit status should probably ?still? indicate an error was encountered.

---

My specific hiccup: 
/etc/logrotate.conf:

```
...
include /etc/logrotate.d
...
/var/log/pm-powersave.log {
    ...
}
...
/var/log/syslog {
...
}
...
```

/etc/logrotate.d/pm-utils:

```
/var/log/pm-suspend.log /var/log/pm-powersave.log {
...
}
```

Because of the above config, syslog would apparently stop processing /etc/logrotate.conf after encountering `error: /etc/logrotate.conf:131 duplicate log entry for /var/log/pm-powersave.log`. This caused /var/log/syslog and other logs to not be rotated resulting in some being well over 100MB (because it took me 2 years to notice -_-;).

Judging from:

<ul><li>The output of a <code>sudo logrotate -f /etc/logrotate.conf</code>:</li><ul>
<li><code>error: /etc/logrotate.conf:131 duplicate log entry for /var/log/pm-powersave.log</code><br>
<code>error: destination /var/log/fail2ban.log-20161022.gz already exists, skipping rotation</code><br>
<code>error: destination /var/log/messages-20161022.gz already exists, skipping rotation</code></li>
</ul><li>The existence of recently rotated logs</li>
<li>The existence of un-rotated logs</li></ul>

It appears that this error in logrotate does not stop logrotate entirely, but it does stop the processing of logrotate's config file.

**Comment by kdudka** [comment]
As far as I understand the code, logrotate exits immediately in case it is unable to read the configuration.  Are you saying that some logs were rotated whereas others were not in a single invocation of logrotate?

**Comment by sc-perth** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

As you can see in the above attached output of a forced logrotate invocation, it does exactly that. First line of output is the error from the duplicate entry in the config, followed by two (correctly aborted) attempts to rotate a log file. Supporting that observation is the presence of many rotated logs on my system, while /var/log/syslog was last rotated in 2014.
- --
Between A & B there's C.
GPG: 0xe818cb04b0a635fc
5b55 a483 138e 69e8 7be1
6bbe e818 cb04 b0a6 35fc
https://sks-keyservers.net/pks/lookup?op=get&search=0xe818cb04b0a635fc
Sent from my phone usind K9 Mail, pardon the typos (I hate autocorrect).

On October 24, 2016 7:59:33 AM EDT, Kamil Dudka <notifications@github.com> wrote:
>As far as I understand the code, logrotate exits immediately in case it
>is unable to read the configuration.  Are you saying that some logs
>were rotated whereas others were not in a single invocation of
>logrotate?
>
>--
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/logrotate/logrotate/issues/81#issuecomment-255720844
-----BEGIN PGP SIGNATURE-----

iQFDBAEBCgAtJhxKb2huIEQuIEhhcmxhbiA8cGVydGhAc2VtaWNvc21pYy5uZXQ+
BQJYDjLzAAoJELHPXx+MTRDUz4MH/2/LCqyeDdUZRXN4KQgb5tBG8ESWPkcCanZD
yjXTJzOIWN0N69AAmlRps84GJLt6JmDeBw/nrA/Z89DEtXkBB2ojtjDiKM7jjY2y
PLN8TgNNUusFymPImHqzZQ/p/ooGNLum64mQrELLew2h6xU2DkZ+uEqtBBaWqn9D
qROMglzDuknefTNBkK7Fb1yjJRtBDKubHoiTtm7BJvMbhyqb7LCkTFVBuBEQ46Hk
xOPnzPr2T3D34/cRuhga4w2TNzKrFt2O01Cj3fw7q6I81h1bcGdY8jZrhBELtmav
IB/73/dWf7eO5Inofkd6t0cPEhit5ww9obA1loz3E3cou2KTCn8=
=O1Nc
-----END PGP SIGNATURE-----

**Comment by kdudka** [comment]
On a second look, the error handling is somewhat inconsistent.  There is one place in ```readConfigPath()``` where it continues after error in a configuration file:

https://github.com/logrotate/logrotate/blob/569dbd4b/config.c#L599

... whereas it breaks immediately on other places.

The ```already exists, skipping rotation``` errors should now be addressed via fc1c3eff.  Could you please try it with logrotate built out of the current master branch?

**Comment by sc-perth** [comment]
Working on getting a 9999 Gentoo ebuild working to do what you are requesting.
Not sure how that addresses this specific bug however.

**Comment by sc-perth** [comment]
OK! A recent push to 3.11 in Gentoo's repository updated the noasprintf patch which unblocked my 9999 (GitHub sourced) ebuild file. I've successfully compiled & installed from HEAD. Now to recreate the situation that caused the interesting behaviour & test.

Thank you for your patience.

**Comment by sc-perth** [comment]
[ls -lAh --group-directories-first /var/log](https://bpaste.net/show/497958bef9b8)

### Broken:
[CLI Output, diagnostic](https://bpaste.net/show/5e32392a40a7)
Added an entry for `/var/log/pm-powersave.log` to `/etc/logrotate.conf` which duplicates an entry in `/etc/logrotate.d/pm-utils`. This entry was added above the entries for:
```
/var/log/mail.err
/var/log/mail.info
/var/log/mail.log
/var/log/mail.warn
/var/log/mediatomb.log
/var/log/syslog
/var/log/tallylog
/var/log/user.log
```
Running `logrotate -d /etc/logrotate.conf` in this situation causes messages identical to the below one for the above list of files.
```
rotating pattern: /var/log/syslog  weekly (4 rotations)
empty log files are not rotated, old logs are removed
No logs found. Rotation not needed.
```
### Unbroken:
[CLI Output, diagnostic](https://bpaste.net/show/d2573791483b)
Removing the entry for `/var/log/pm-powersave.log` in `/etc/logrotate.conf` and running `logrotate -d /etc/logrotate.conf` produces messages similar to:
```
rotating pattern: /var/log/mediatomb.log  weekly (4 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/mediatomb.log
  Now: 2016-12-03 11:50
  Last rotated at 2014-02-09 17:47
  log does not need rotating (log is empty)

rotating pattern: /var/log/syslog  weekly (4 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/syslog
  Now: 2016-12-03 11:50
  Last rotated at 2016-12-01 04:20
  log does not need rotating (log has been rotated at 2016-12-1 4:20, that is not week ago yet)
```

**Comment by kdudka** [comment]
As for the Gentoo patches, the noasprintf patch is useless since 7c42e19bc3852587c7ad3b34436d25baaacdb3e7.  So is the ```logrotate-3.11.0-lfs.patch```, which inserts the ```AC_SYS_LARGEFILE``` line right before the already existing ```AC_SYS_LARGEFILE``` line from usptream's ```configure.ac```.

As for the bug, your testing environment is too complicated for me to reconstruct it locally.  Could you please try the patch from the [duperror branch](https://github.com/logrotate/logrotate/compare/duperror)?

**Comment by sc-perth** [comment]
Sorry about the delay @kdudka; that patch doesn't appear to resolve the issue.
I stopped applying the `...noasprintf.patch` and `...lfs.patch` patches, added in the duperror.patch (coppied everything from `diff --git` on found [here](https://github.com/logrotate/logrotate/compare/duperror.patch)).

The result on the same "broken" logrotate.conf is:
```
/etc: $ sudo logrotate -d ./logrotate.conf.broken 
reading config file ./logrotate.conf.broken
including /etc/logrotate.d
reading config file consolekit
reading config file elog-save-summary
reading config file fail2ban
reading config file mysql
reading config file openrc
reading config file pm-utils
reading config file rsyncd
reading config file squid
reading config file syslog-ng
error: ./logrotate.conf.broken:106 duplicate log entry for /var/log/pm-powersave.log
removing last 32 log configs
```
[Full CLI Output](https://bpaste.net/show/38ba81b66c5a)

**Comment by kdudka** [comment]
Thank you for testing it!  I have pushed one more patch to the ```duperror``` branch: https://github.com/logrotate/logrotate/commit/bd35e34000c5821d075ad07c95b6a08a8f4a65cd

Could you please give it a try with both the patches applied?

**Comment by kdudka** [comment]
I have pushed one more fixup to actually propagate the error code: 341819638c5e16c405bd686e65c834b7bca351e2 Sorry for the mess!

**Comment by sc-perth** [comment]
With all three patches applied (I'm assuming that's safe:) in the order they were posted here, result is the same as with the 1st patch it looks like.
[Build output](https://bpaste.net/show/1ebeafb0f26c)
[logrotate -d output](https://bpaste.net/show/c54392e120e8)
Note that the logrotate.conf.broke and logrotate.conf have not been touched since the last post by me, see above's Build Output for conf file contents.

**Comment by kdudka** [comment]
Thank you for being patient.  I believe I got the error recovery finally working.  Please try the current ```duperror``` branch (rebased on top of master):

https://github.com/logrotate/logrotate/compare/duperror

**Comment by sc-perth** [comment]
BOOM! You got somewhere, and it looks like you might have solved it! :)
[logrotate -d /etc/logrotate.conf.broken](https://bpaste.net/show/4a84abfae721) Excerpt:
```
reading config file syslog-ng
error: /etc/logrotate.conf.broken:106 duplicate log entry for /var/log/pm-powersave.log
Reading state from file: /var/lib/logrotate.status
Allocating hash table for state file, size 64 entries
Creating new state
...
rotating pattern: /var/log/syslog  weekly (4 rotations)
```
The misconfigure point would normally have prevented logrotate from trying to rotate syslog, as than config entry is after the duplicated powersave entry.

[build output](https://bpaste.net/show/9b89832f87a4)
[logrotate.conf.broken contents in here](https://bpaste.net/show/7cada5ad062c)

**Comment by kdudka** [comment]
Thanks for confirmation!  I will merge it into master in a week or so unless someone finds a problem in the proposed fix.
