### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [logrotate/logrotate#83]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by kdudka** [comment]
Sounds like a good idea.  I first need to create and publish a secure enough personal key though...

**Comment by kdudka** [comment]
I have just released ```logrotate-3.11.0```, which is signed by my GPG key (both the git tag and the release tarballs):

https://github.com/logrotate/logrotate/releases/tag/3.11.0

Please let me know if there are any issues with those signatures.

**Comment by g4jc** [comment]
Works great! Thank you for taking a proactive approach to  security. Reported to my upstream distro for inclusion during build.

```
 gpg --keyserver pgp.mit.edu --recv-keys 873DB37572A37B36 
gpg: key 873DB37572A37B36: public key "Kamil Dudka <kdudka@redhat.com>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   3  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: next trustdb check due at 2017-01-10
gpg: Total number processed: 1
gpg:               imported: 1


gpg --verify logrotate-3.11.0.tar.gz.asc
gpg: assuming signed data in 'logrotate-3.11.0.tar.gz'
gpg: Signature made Fri 02 Dec 2016 08:30:39 AM EST
gpg:                using RSA key 873DB37572A37B36
gpg: Good signature from "Kamil Dudka <kdudka@redhat.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 992A 96E0 7505 6E79 CD82  14F9 873D B375 72A3 7B36
```

**Comment by glensc** [comment]
@g4jc do you mind creating PR for README.md how to check for the signatures?

**Comment by g4jc** [comment]
@glensc Done in PR #94
