### ISSUE TITLE
Please clarify how application should react to SIGHUP received from logrotate.

### ISSUE THREAD

**Issue by rofl0r** [logrotate/logrotate#99]
refering to this situation here: https://github.com/tinyproxy/tinyproxy/issues/25#issuecomment-249539946

tinyproxy is blocking in select(), and when it receives the SIGHUP, it currently exits.
but what should it do instead ?
just restart the select loop another time ?
or run `closelog(), openlog()` ?
or should it install a general signal handler ?

please clarify, or if there is already existing documentation that explains it (the logrotate manpage doesn't), point me to it.
thanks.

**Comment by kdudka** [comment]
I guess you already have this answered in the original discussion.  logrotate does not send any signals on its own.  So you cannot find anything about signals (except postrotate scripts examples)  in logrotate's man page.  You need to check logrotate's configuration to find the answer.  For example this is the contents of ```/etc/logrotate.d/tinyproxy``` distributed with Fedora:

```
/var/log/tinyproxy/tinyproxy.log {
    daily
    rotate 10
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        [ ! -f /var/run/tinyproxy/tinyproxy.pid ] || kill -HUP `cat /var/run/tinyproxy/tinyproxy.pid`
    endscript
}
```

**Comment by kdudka** [comment]
Note that the actual answer is here: https://github.com/tinyproxy/tinyproxy/issues/25#issuecomment-268849637
